# Warcraft 3 Minimap Info File (.mmp)
# See mmp.py for type definitions

file_format_version = 0

[[icons]]

icon_type = "PlayerStart"
x = 266
y = 248
colour_blue = 3
colour_green = 3
colour_red = 255
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 62
y = 73
colour_blue = 255
colour_green = 66
colour_red = 0
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 266
y = 248
colour_blue = 129
colour_green = 0
colour_red = 84
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 266
y = 248
colour_blue = 185
colour_green = 230
colour_red = 28
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 40
y = 130
colour_blue = 151
colour_green = 150
colour_red = 149
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 266
y = 245
colour_blue = 241
colour_green = 191
colour_red = 126
colour_alpha = 255