BUILDING_IDS = {
    # Melee
    'htow', 'hkee', 'hcas', 'hhou', 'halt', 'hbar', 'hlum', 'hbla',
    'harm', 'hars', 'hgra', 'hwtw', 'hvlt', 'hgtw', 'hctw', 'hatw',
    'ogre', 'ostr', 'ofrt', 'oalt', 'obar', 'ofor', 'otto', 'osld', 'obea', 'otrb', 'ovln', 'owtw',
    'unpl', 'unp1', 'unp2', 'uzig', 'uaod', 'usep', 'usap', 'ugrv',
    'uslh', 'utod', 'ubon', 'ugol', 'utom', 'uzg1', 'uzg2',
    'etol', 'etoa', 'etoe', 'emow', 'eate', 'eaom', 'eaoe', 'eaow', 'edob', 'edos', 'eden', 'etrp',

    # Neutral passive / Melee
    'ngol', 'ngme', 'nfoh', 'nmoo', 'ngad', 'nwgt', 'ndrk', 'ndru', 'ndrz', 'ndrg', 'ndro', 'ndrr',
    'nmer', 'nmr2', 'nmr3', 'nmr4', 'nmr5', 'nmr6', 'nmr7', 'nmr8', 'nmr9', 'nmr0', 'nmra', 'nmrb',
    'ntav', 'nmrk', 'nmrc', 'nmrd', 'nshp', 'nmre', 'nmrf',

    # Neutral Passive / Melee / Special
    'ncnt', 'nct1', 'nct2', 'ndch', 'ndh0', 'ndh1', 'nfh0', 'nfh1', 'nfr1', 'nfr2', 'ngnh', 'ngt2', 'nhns',
    'nth0', 'nth1', 'nmg0', 'nmg1', 'nmh0', 'nmh1', 'nnzg', 'ntnt', 'ntt2', 'nten', 'ntn2',

    # Neutral Passive / Campaign
    'ncb0', 'ncb1', 'ncb2', 'ncb3', 'ncb4', 'ncb5', 'ncb6', 'ncb7', 'ncb8', 'ncb9', 'ncba', 'ncbb',
    'ncbc', 'ncbd', 'ncbe', 'ncbf',
    'ncbd', 'ncbe', 'ncbf',
    'ncmw', 'ncop', 'ncp2', 'ncp3', 'ndke', 'ndkw', 'nico', 'nbse', 'nbsw', 'nzin',

    # Human / Campaign
    'ngwr', 'negm', 'negf', 'negt', 'ndgt', 'nheb', 'nefm', 'nef0', 'nef1', 'nef2', 'nef3', 'nef4', 'nef5',
    'nef6', 'nef7', 'haro', 'nfrt', 'hshy', 'nitb', 'nmgv', 'nbt2', 'ndt2', 'ntx2', 'net2', 'nft2',
    'nbt1', 'ndt1', 'ntt1', 'net1', 'nft1',

    # Orc / Campaign
    'npgf', 'ndrb', 'nbfl', 'ndfl', 'ocbw', 'oshy', 'npgr', 'nwc1', 'nwc2',

    # Undead / Campaign
    'nshr', 'ndmg', 'ngni', 'nfrm', 'nbsm', 'ushp',

    # Night Elf / Campaign
    'nctl', 'ncta', 'ncte', 'ncap', 'ncaw', 'nfnp', 'nhcn', 'nbwd', 'ngob', 'eshy',
    'nfv0', 'nfv1', 'nfv2', 'nfv3', 'nfv4',
    'nvr0', 'nvr1', 'nvr2',

    # Naga / Campaign
    'nnad', 'nnfm', 'nnsa', 'nnsg', 'nntt', 'nntg',

    # Neutral Hostile
    'nfgo',

}

TILESET_TO_TERRAIN = {
    # Pulled from worldeditdata.txt
    b'L': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'F': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'W': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'B': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'A': r"Environment\\DNC\\DNCAshenvale\\DNCAshenvaleTerrain\\DNCAshenvaleTerrain.mdl",
    b'C': r"Environment\\DNC\\DNCFelwood\\DNCFelwoodTerrain\\DNCFelwoodTerrain.mdl",
    b'N': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'Y': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'X': r"Environment\\DNC\\DNCDalaran\\DNCDalaranTerrain\\DNCDalaranTerrain.mdl",
    b'V': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'D': r"Environment\\DNC\\DNCDungeon\\DNCDungeonTerrain\\DNCDungeonTerrain.mdl",
    b'Q': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'G': r"Environment\\DNC\\DNCUnderground\\DNCUndergroundTerrain\\DNCUndergroundTerrain.mdl",
    b'Z': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'I': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'O': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'K': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
    b'J': r"Environment\\DNC\\DNCDalaran\\DNCDalaranTerrain\\DNCDalaranTerrain.mdl",
}

TILESET_TO_UNIT_MODEL = {
    # Pulled from worldeditdata.txt
    b'L': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'F': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'W': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'B': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'A': r"Environment\\DNC\\DNCAshenvale\\DNCAshenvaleUnit\\DNCAshenvaleUnit.mdl",
    b'C': r"Environment\\DNC\\DNCFelwood\\DNCFelwoodUnit\\DNCFelwoodUnit.mdl",
    b'N': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'Y': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'X': r"Environment\\DNC\\DNCDalaran\\DNCDalaranUnit\\DNCDalaranUnit.mdl",
    b'V': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'D': r"Environment\\DNC\\DNCDungeon\\DNCDungeonUnit\\DNCDungeonUnit.mdl",
    b'Q': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'G': r"Environment\\DNC\\DNCUnderground\\DNCUndergroundUnit\\DNCUndergroundUnit.mdl",
    b'Z': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'I': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'O': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'K': r"Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl",
    b'J': r"Environment\\DNC\\DNCDalaran\\DNCDalaranUnit\\DNCDalaranUnit.mdl",
}

TILESET_TO_SOUND = {
    # Pulled from triggerdata.txt
    b'A': ("AshenvaleDay", "AshenvaleNight",),
    b'B': ("BarrensDay", "BarrensNight",),
    b'K': ("BlackCitadelDay", "BlackCitadelNight",),
    b'Y': ("CityScapeDay", "CityScapeNight",),
    b'X': ("DalaranDay", "DalaranNight",),
    b'J': ("DalaranRuinsDay", "DalaranRuinsNight",),
    b'D': ("DungeonDay", "DungeonNight",),
    b'C': ("FelwoodDay", "FelwoodNight",),
    b'I': ("IceCrownDay", "IceCrownNight",),
    b'F': ("LordaeronFallDay", "LordaeronFallNight",),
    b'L': ("LordaeronSummerDay", "LordaeronSummerNight",),
    b'W': ("LordaeronWinterDay", "LordaeronWinterNight",),
    b'N': ("NorthrendDay", "NorthrendNight",),
    b'O': ("BlackCitadelDay", "BlackCitadelNight",),
    b'Z': ("SunkenRuinsDay", "SunkenRuinsNight",),
    b'V': ("VillageDay", "VillageNight",),
    b'Q': ("VillageFallDay", "VillageFallNight",),
}

# Replacements:
# set \w+=CreateSound\(("[^"]*"), .*\n\s*call SetSoundParamsFromLabel\(\w+, ("[^"]*")\)\n\s*call SetSoundDuration\(\w+, (\d+)\)
# r$1: ($2, $3),

SOUND_DURATION_DATA = {
    (r"Abilities\\Spells\\Human\\CallToArms\\HumanCallToArmsWhat1.wav", 10): 3971,
    (r"Abilities\\Spells\\Human\\Defend\\DefendCaster.wav", 10): 1166,
    (r"Abilities\\Spells\\Human\\DivineShield\\DivineShield.wav", 10): 1955,
    (r"Abilities\\Spells\\Human\\MassTeleport\\MassTeleportTarget.wav", 10): 4899,
    (r"Abilities\\Spells\\Other\\LoadUnload\\Loading.wav", 10): 740,
    (r"Abilities\\Spells\\Undead\\DarkSummoning\\DarkSummoningTarget1.wav", 10): 3320,
    (r"Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorTarget1.wav", 10): 2995,
    (r"Abilities\\Spells\\Undead\\RaiseSkeletonWarrior\\RaiseSkeleton.wav", 10): 2329,
    (r"Abilities\\Weapons\\ColdArrow\\ColdArrow2.wav", 10): 1480,
    (r"Abilities\\Weapons\\Dryadmissile\\DryadMissile2.wav", 10): 539,
    (r"Buildings\\Human\\Blacksmith\\BlacksmithWhat1.wav", 12700): 3059,
    (r"Buildings\\Undead\\Graveyard\\GraveYardWhat1.wav", 12700): 3703,
    (r"Sound\\Ambient\\DoodadEffects\\CityScapeCathedralLoop1.wav", 10): 4133,
    (r"Sound\\Ambient\\DoodadEffects\\CityScapeMagicRunesLoop1.wav", 10): 1149,
    (r"Sound\\Ambient\\DoodadEffects\\DoorSlam1.wav", 10): 485,
    (r"Sound\\Ambient\\DoodadEffects\\FrostmourneChant1.wav", 10): 5039,
    (r"Sound\\Ambient\\DoodadEffects\\FrostmourneLoopUndead01.wav", 10): 3320,
    (r"Sound\\Ambient\\DoodadEffects\\LordaeronSummerFliesLoop1.wav", 10): 1962,
    (r"Sound\\Ambient\\DoodadEffects\\UtherReturns.wav", 10): 6711,
    (r"Sound\\Ambient\\DoodadEffects\\WaterLakeLoop1.wav", 10): 3297,
    (r"Sound\\Ambient\\DoodadEffects\\WaterStreamLoop1.wav", 10): 2008,
    (r"Sound\\Ambient\\DoodadEffects\\WaterWaterFallLoop1.wav", 10): 1021,
    (r"Sound\\Ambient\\DoodadEffects\\WaterWavesLoop1.wav", 10): 7445,
    (r"Sound\\Buildings\\Death\\CityBuildingDeath1.wav", 10): 3505,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Arthas02.mp3", 10): 4493,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Arthas04.mp3", 10): 4101,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Arthas06.mp3", 10): 7497,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Arthas08.mp3", 10): 7784,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Arthas10.mp3", 10): 2664,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Arthas18.mp3", 10): 4153,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Arthas24.mp3", 10): 3422,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Arthas26.mp3", 10): 3239,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Bandit32.mp3", 10): 3709,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01BanditB14.mp3", 10): 3709,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Grunt17.mp3", 10): 2455,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Grunt21.mp3", 10): 1071,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Knight25.mp3", 10): 4257,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Uther01.mp3", 10): 4728,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Uther03.mp3", 10): 4101,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Uther05.mp3", 10): 5224,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Uther07.mp3", 10): 1985,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Uther09.mp3", 10): 5381,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01Uther11.mp3", 10): 6452,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerC23.mp3", 10): 3448,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerC35.mp3", 10): 5799,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerC36.mp3", 10): 4336,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerC37.mp3", 10): 940,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerC38.mp3", 10): 1253,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerF22.mp3", 10): 1724,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerF27.mp3", 10): 9430,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerF39.mp3", 10): 1724,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerF40.mp3", 10): 1280,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerF41.mp3", 10): 914,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerF42.mp3", 10): 2951,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerM28.mp3", 10): 12225,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerM33.mp3", 10): 2873,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01VillagerM43.mp3", 10): 3291,
    (r"Sound\\Dialogue\\HumanCampaign\\Human01\\H01WolfRider19.mp3", 10): 3160,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Arthas03.mp3", 12700): 2089,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Arthas05.mp3", 12700): 1123,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Arthas07.mp3", 12700): 2638,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Arthas09.mp3", 12700): 1201,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Arthas15.mp3", 12700): 2037,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Arthas18.mp3", 12700): 2560,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Arthas20.mp3", 10): 2011,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Arthas24.mp3", 12700): 2847,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Arthas26.mp3", 12700): 6791,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Blademaster11.mp3", 12700): 10919,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Dwarf21.mp3", 12700): 3813,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02DwarfHunter17.mp3", 12700): 3500,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02DwarfHunter18A.mp3", 10): 6504,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02DwarfScout16.mp3", 12700): 6661,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Footman23.mp3", 12700): 3683,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Footman38.mp3", 10): 9534,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Searinox19.mp3", 10): 9221,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Uther01.mp3", 12700): 7575,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Uther02.mp3", 12700): 2873,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Uther04.mp3", 12700): 12225,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Uther06.mp3", 12700): 5146,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Uther08.mp3", 12700): 4075,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Uther10.mp3", 12700): 1671,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Uther12.mp3", 12700): 5250,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Uther13.mp3", 12700): 5041,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Uther25.mp3", 12700): 3213,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Uther27.mp3", 12700): 12695,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02VillagerM39.mp3", 12700): 3813,
    (r"Sound\\Dialogue\\HumanCampaign\\Human02\\H02Warlock22.mp3", 10): 7575,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas02.mp3", 10): 3186,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas04.mp3", 10): 3291,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas05.mp3", 10): 8097,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas06.mp3", 10): 5067,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas08.mp3", 10): 4310,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas11.mp3", 10): 2011,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas12.mp3", 10): 6765,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas14.mp3", 10): 1384,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas16.mp3", 10): 1619,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas17.mp3", 10): 2638,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas19.mp3", 10): 1828,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas24.mp3", 10): 1044,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas25.mp3", 10): 2011,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas27.mp3", 10): 3892,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas31.mp3", 10): 2951,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas35.mp3", 10): 2403,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas36.mp3", 10): 3761,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Arthas38.mp3", 10): 4884,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Bandit51.mp3", 10): 1593,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Bandit52.mp3", 10): 1750,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Captain01.mp3", 10): 5564,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Captain03.mp3", 10): 1071,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Dwarf26.mp3", 10): 5198,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Footman13.mp3", 10): 4205,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Footman15.mp3", 10): 6713,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Footman47.mp3", 10): 940,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Jaina07.mp3", 10): 5146,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Jaina09.mp3", 10): 6426,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Jaina18.mp3", 10): 3840,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Jaina20.mp3", 10): 13008,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Jaina22.mp3", 10): 4310,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Jaina34.mp3", 10): 4205,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Jaina37.mp3", 10): 6164,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03KelThuzad32.mp3", 10): 4493,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03KelThuzad33.mp3", 10): 4153,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Priest21.mp3", 10): 6765,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03Priest23.mp3", 10): 6974,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03VillagerF39.mp3", 10): 3787,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03VillagerF53.mp3", 10): 1985,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03VillagerM10.mp3", 10): 8097,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03VillagerM40.mp3", 10): 9064,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03VillagerM41.mp3", 10): 1253,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03VillagerM43.mp3", 10): 1645,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03VillagerM44.mp3", 10): 1515,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03VillagerM45.mp3", 10): 4075,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03VillagerM49.mp3", 10): 1697,
    (r"Sound\\Dialogue\\HumanCampaign\\Human03\\H03VillagerM50.mp3", 10): 1227,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Acolyte03.mp3", 10): 4754,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas02.mp3", 10): 2638,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas04.mp3", 10): 5381,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas07.mp3", 10): 1776,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas09.mp3", 10): 5407,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas11.mp3", 10): 2951,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas15.mp3", 10): 1854,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas17.mp3", 10): 1541,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas18.mp3", 10): 5903,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas19.mp3", 10): 4466,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas21.mp3", 10): 2560,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas22.mp3", 10): 5276,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Arthas26.mp3", 10): 3213,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Jaina01.mp3", 10): 5355,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Jaina05.mp3", 10): 1358,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04Jaina24.mp3", 10): 992,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04KelThuzad06.mp3", 10): 13139,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04KelThuzad23.mp3", 10): 8777,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04KelThuzad25.mp3", 10): 10866,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04KelThuzad27.mp3", 10): 9351,
    (r"Sound\\Dialogue\\HumanCampaign\\Human04\\H04KelThuzad28.mp3", 10): 12355,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Acolyte22.mp3", 12700): 5564,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas02.mp3", 12700): 2168,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas05.mp3", 12700): 7184,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas07.mp3", 12700): 2717,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas08.mp3", 12700): 3187,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas10.mp3", 12700): 1384,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas11.mp3", 12700): 8699,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas13.mp3", 12700): 3474,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas21.mp3", 12700): 1358,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas23.mp3", 12700): 3370,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas25.mp3", 12700): 4598,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas26.mp3", 12700): 4624,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas28.mp3", 12700): 2508,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas31.mp3", 12700): 5146,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas33.mp3", 12700): 5094,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Arthas35.mp3", 12700): 5669,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Footman03.mp3", 12700): 7027,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Footman04.mp3", 12700): 1594,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Footman09.mp3", 12700): 6818,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Footman12.mp3", 12700): 5904,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Footman16.mp3", 12700): 3213,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Footman18.mp3", 12700): 2795,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Footman20.mp3", 12700): 6896,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Footman24.mp3", 12700): 3082,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Footman51.mp3", 12700): 4833,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Jaina01.mp3", 12700): 4180,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Jaina06.mp3", 12700): 392,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Uther27.mp3", 12700): 2299,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Uther29.mp3", 12700): 3579,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Uther30.mp3", 12700): 5616,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Uther32.mp3", 12700): 10710,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05Uther34.mp3", 12700): 6896,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05VillagerM47.mp3", 10): 1567,
    (r"Sound\\Dialogue\\HumanCampaign\\Human05\\H05VillagerM49.mp3", 10): 1489,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas01.mp3", 12700): 1985,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas03.mp3", 12700): 5460,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas04.mp3", 12700): 9430,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas06.mp3", 12700): 2090,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas08.mp3", 12700): 4859,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas10.mp3", 12700): 2978,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas12.mp3", 12700): 11938,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas14.mp3", 12700): 9456,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas16.mp3", 12700): 575,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas30.mp3", 12700): 4232,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas33.mp3", 12700): 6609,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas43.mp3", 12700): 6452,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Arthas46.mp3", 12700): 4963,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Jaina13.mp3", 12700): 1881,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Jaina17.mp3", 12700): 3814,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06MalGanis31.mp3", 12700): 6687,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06MalGanis32.mp3", 12700): 15151,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06MalGanis41.mp3", 12700): 2456,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06MalGanis42.mp3", 12700): 13401,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06MalGanis44.mp3", 12700): 9926,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06MalGanis45.mp3", 12700): 15151,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Uther02.mp3", 12700): 6452,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Uther05.mp3", 12700): 679,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Uther07.mp3", 12700): 3866,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Uther09.mp3", 12700): 5669,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Uther11.mp3", 12700): 4049,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06Uther15.mp3", 12700): 3579,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06VillagerF24.mp3", 12700): 2429,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06VillagerF57.mp3", 12700): 1776,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06VillagerF58.mp3", 12700): 2064,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06VillagerF59.mp3", 12700): 2769,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06VillagerF61.mp3", 12700): 4833,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06VillagerM23.mp3", 12700): 3631,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06VillagerM25.mp3", 12700): 2194,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06VillagerM26.mp3", 12700): 2874,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06VillagerM27.mp3", 12700): 1358,
    (r"Sound\\Dialogue\\HumanCampaign\\Human06\\H06VillagerM28.mp3", 12700): 1724,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas02.mp3", 10): 2900,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas04.mp3", 10): 8464,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas06.mp3", 10): 1149,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas07.mp3", 10): 3579,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas08.mp3", 10): 1802,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas10.mp3", 10): 3683,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas12.mp3", 10): 3866,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas14.mp3", 10): 4127,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas16.mp3", 10): 2769,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas19.mp3", 10): 2612,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas20.mp3", 10): 3265,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas26.mp3", 10): 3762,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Arthas28.mp3", 10): 7732,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Captain01.mp3", 10): 11363,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Captain03.mp3", 10): 3944,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Knight27.mp3", 10): 3866,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Knight29.mp3", 10): 1228,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Muradin09.mp3", 10): 4937,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Muradin13.mp3", 10): 5120,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Muradin15.mp3", 10): 9221,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Muradin18.mp3", 10): 3553,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Muradin21.mp3", 10): 11964,
    (r"Sound\\Dialogue\\HumanCampaign\\Human07\\H07Muradin22.mp3", 10): 8725,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Arthas06.mp3", 10): 2978,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Arthas08.mp3", 10): 10945,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Arthas10.mp3", 10): 5251,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Arthas11.mp3", 10): 2586,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Arthas13.mp3", 10): 2246,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Arthas18.mp3", 10): 3109,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Arthas19.mp3", 10): 2900,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Arthas21.mp3", 10): 8777,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Arthas25.mp3", 10): 15778,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Captain01.mp3", 10): 6034,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Captain03.mp3", 10): 2664,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Captain05.mp3", 10): 3474,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Captain07.mp3", 10): 4911,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Captain20.mp3", 10): 993,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Emissary02.mp3", 10): 8385,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Emissary04.mp3", 10): 9456,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Footman16.mp3", 10): 4467,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Footman22.mp3", 10): 1515,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Footman24.mp3", 10): 3161,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Knight23.mp3", 10): 1306,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Muradin09.mp3", 10): 1933,
    (r"Sound\\Dialogue\\HumanCampaign\\Human08\\H08Muradin12.mp3", 10): 5904,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas02.mp3", 10): 5094,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas05.mp3", 10): 8202,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas07.mp3", 10): 3997,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas09.mp3", 10): 3788,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas12.mp3", 10): 2273,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas14.mp3", 10): 5982,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas16.mp3", 10): 3579,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas18.mp3", 10): 6296,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas19.mp3", 10): 12669,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas21.mp3", 10): 7628,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas24.mp3", 10): 5851,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas26.mp3", 10): 5355,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas28.mp3", 10): 940,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Arthas28a.mp3", 10): 1228,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Captain20.mp3", 10): 4232,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Guardian08.mp3", 10): 9326,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Guardian10.mp3", 10): 6191,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Guardian11.mp3", 10): 10815,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Guardian13.mp3", 10): 10893,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09MalGanis03.mp3", 10): 15726,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09MalGanis23.mp3", 10): 11468,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09MalGanis25.mp3", 10): 15020,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09MalGanis27.mp3", 10): 4049,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Muradin01.mp3", 10): 9378,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Muradin04.mp3", 10): 3605,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Muradin06.mp3", 10): 6269,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Muradin15.mp3", 10): 24816,
    (r"Sound\\Dialogue\\HumanCampaign\\Human09\\H09Muradin17.mp3", 10): 6400,
    (r"Sound\\Interface\\HeroDropItem1.wav", 12700): 486,
    (r"Sound\\Interface\\Hint.wav", 10): 2006,
    (r"Sound\\Interface\\PickUpItem.wav", 10): 174,
    (r"Sound\\Interface\\QuestCompleted.wav", 10): 5155,
    (r"Sound\\Interface\\QuestFailed.wav", 10): 4690,
    (r"Sound\\Interface\\QuestLog.wav", 10): 2276,
    (r"Sound\\Interface\\QuestNew.wav", 10): 3750,
    (r"Sound\\Interface\\Rescue.wav", 10): 3796,
    (r"Sound\\Units\\Combat\\MetalHeavyBashFlesh1.wav", 10): 662,
    (r"Sound\\Units\\Combat\\MetalMediumBashFlesh1.wav", 10): 604,
    (r"Sound\\Units\\Combat\\MetalMediumBashFlesh2.wav", 10): 580,
    (r"Sound\\Units\\Combat\\MetalMediumBashFlesh3.wav", 10): 450,
    (r"Sound\\Units\\Combat\\MetalMediumBashStone1.wav", 10): 778,
    (r"Sound\\Units\\Combat\\MetalMediumChopFlesh1.wav", 10): 522,
    (r"Sound\\Units\\Combat\\MetalMediumChopFlesh2.wav", 10): 720,
    (r"Sound\\Units\\Combat\\MetalMediumChopFlesh3.wav", 10): 723,
    (r"Sound\\Units\\Combat\\MetalMediumSliceFlesh1.wav", 10): 659,
    (r"Sound\\Units\\Combat\\MetalMediumSliceFlesh2.wav", 10): 601,
    (r"Sound\\Units\\Combat\\MetalMediumSliceFlesh3.wav", 10): 604,
    (r"Sound\\Units\\Combat\\WoodLightBashStone2.wav", 10): 746,
    (r"Sound\\Units\\Combat\\WoodLightBashStone3.wav", 10): 921,
    (r"Sound\\Units\\Combat\\WoodMediumBashMetal1.wav", 10): 1097,
    (r"Sound\\Units\\Combat\\WoodMediumBashMetal2.wav", 10): 726,
    (r"Sound\\Units\\Combat\\WoodMediumBashMetal3.wav", 10): 871,
    (r"Units\\Creeps\\Bandit\\BanditWarcry1.wav", 10): 795,
    (r"Units\\Creeps\\Bandit\\BanditYesAttack2.wav", 10): 1216,
    (r"Units\\Creeps\\Bandit\\BanditYesAttack3.wav", 10): 490,
    (r"Units\\Critters\\Sheep\\Sheep1.wav", 10): 1178,
    (r"Units\\Critters\\VillagerMan\\VillagerM1.wav", 10): 774,
    (r"Units\\Critters\\VillagerMan\\VillagerM2.wav", 10): 1166,
    (r"Units\\Critters\\VillagerMan\\VillagerMaleDeath1.wav", 10): 1590,
    (r"Units\\Critters\\VillagerWoman\\VillagerF1.wav", 10): 606,
    (r"Units\\Critters\\VillagerWoman\\VillagerF2.wav", 10): 1041,
    (r"Units\\Critters\\VillagerWoman\\VillagerF3.wav", 10): 1364,
    (r"Units\\Demon\\DoomGuard\\BalrogAttack1.wav", 10): 1028,
    (r"Units\\Human\\Arthas\\ArthasPissed4.wav", 10): 2000,
    (r"Units\\Human\\Footman\\FootmanDeath.wav", 10): 1245,
    (r"Units\\Human\\Footman\\FootmanYesAttack2.wav", 10): 1085,
    (r"Units\\Human\\HeroMountainKing\\HeroMountainKingDeath.wav", 10): 2680,
    (r"Units\\Human\\HeroPaladin\\HeroPaladinYesAttack1.wav", 10): 1471,
    (r"Units\\Human\\KnightNoRider\\KnightNoRiderWarcry1.wav", 10): 2217,
    (r"Units\\Human\\KnightNoRider\\KnightNoRiderWarcry1.wav", 12700): 2217,
    (r"Units\\Human\\KnightNoRider\\KnightNoRiderWhat1.wav", 10): 969,
    (r"Units\\Human\\KnightNoRider\\KnightNoRiderWhat2.wav", 10): 1973,
    (r"Units\\Human\\KnightNoRider\\KnightNoRiderWhat2.wav", 12700): 1973,
    (r"Units\\Human\\KnightNoRider\\KnightNoRiderWhat3.wav", 10): 1857,
    (r"Units\\Human\\KnightNoRider\\KnightNoRiderWhat3.wav", 12700): 1857,
    (r"Units\\Human\\KnightNoRider\\KnightNoRiderYesAttack1.wav", 10): 1799,
    (r"Units\\Human\\KnightNoRider\\KnightNoRiderYesAttack2.wav", 10): 2879,
    (r"Units\\Human\\Knight\\HorseLoop1.wav", 10): 2101,
    (r"Units\\Human\\Knight\\HorseLoop1.wav", 12700): 2101,
    (r"Units\\Human\\Knight\\HorseLoop2.wav", 10): 3227,
    (r"Units\\Human\\Knight\\HorseLoop3.wav", 10): 5317,
    (r"Units\\Human\\Knight\\HorseLoop3.wav", 12700): 5317,
    (r"Units\\Human\\MortarTeam\\MortarTeamWhat1.wav", 10): 1105,
    (r"Units\\Human\\Peasant\\PeasantYes2.wav", 10): 964,
    (r"Units\\Human\\Rifleman\\RiflemanAttack1.wav", 10): 702,
    (r"Units\\Human\\Rifleman\\RiflemanAttack2.wav", 10): 702,
    (r"Units\\Human\\Sorceress\\SorceressDeath.wav", 10): 1909,
    (r"Units\\Orc\\HeroBladeMaster\\HeroBladeMasterDeath.wav", 12700): 2348,
    (r"Units\\Undead\\Abomination\\AbominationPissed5.wav", 10): 1734,
    (r"Units\\Undead\\Abomination\\AbominationYesAttack2.wav", 10): 1195,
    (r"Units\\Undead\\Gargoyle\\GargoyleWhat1.wav", 10): 3158,
    (r"Units\\Undead\\Gargoyle\\GargoyleWhat2.wav", 10): 3158,
    (r"Units\\Undead\\Necromancer\\NecromancerDeath.wav", 10): 2002,
    (r"Units\\Undead\\Skeleton\\SkeletonYesAttack1.wav", 12700): 1700,
    (r"Units\\Undead\\Skeleton\\SkeletonYesAttack2.wav", 12700): 1114,
    (r"Units\\Undead\\Skeleton\\SkeletonYesAttack3.wav", 12700): 2237,
}
"""Sound path, fadeout -> duration"""

SOUND_LABEL_DATA = {
    "Abilities\\Spells\\Demon\\RainOfFire\\RainOfFireTarget1.wav": 'StarfallTarget',
    "Abilities\\Spells\\Human\\CallToArms\\HumanCallToArmsWhat1.wav": 'TownHallCallToArms',
    "Abilities\\Spells\\Human\\Defend\\DefendCaster.wav": 'Defend',
    "Abilities\\Spells\\Human\\DispelMagic\\DispelMagicTarget.wav": 'DispelMagic',
    "Abilities\\Spells\\Human\\Flare\\FlareTarget1.wav": 'Flare1',
    "Abilities\\Spells\\Human\\Flare\\FlareTarget2.wav": 'Flare2',
    "Abilities\\Spells\\Human\\Flare\\FlareTarget3.wav": 'Flare3',
    "Abilities\\Spells\\Human\\InnerFire\\PriestCastAttack1.wav": 'InnerFireCast',
    "Abilities\\Spells\\Human\\Invisibility\\InvisibilityTarget.wav": 'Invisibility',
    "Abilities\\Spells\\Human\\MassTeleport\\MassTeleportTarget.wav": 'MassTeleport',
    "Abilities\\Spells\\Human\\Resurrect\\ResurrectTarget.wav": 'Resurrect',
    "Abilities\\Spells\\Human\\StormBolt\\ThunderBoltMissileDeath.wav": 'StormBolt',
    "Abilities\\Spells\\NightElf\\Barkskin\\BarkSkinTarget1.wav": 'Barkskin',
    "Abilities\\Spells\\NightElf\\Blink\\BlinkBirth1.wav": 'BlinkCaster',
    "Abilities\\Spells\\NightElf\\CorrosiveBreath\\CorrosiveBreathMissileLaunch1.wav": 'CorrosiveBreathMissileLaunch',
    "Abilities\\Spells\\NightElf\\EatTree\\EatTreeTarget1.wav": 'EatTreeMunch',
    "Abilities\\Spells\\NightElf\\EntangleMine\\TreeOfLifeGoldMineBirth1.wav": 'EntangleMineBirth',
    "Abilities\\Spells\\NightElf\\FaerieFire\\FaerieFireLaunch1.wav": 'FaerieFire',
    "Abilities\\Spells\\NightElf\\Immolation\\ImmolationTarget1.wav": 'ImmolationTarget',
    "Abilities\\Spells\\NightElf\\Rejuvenation\\RejuvenationTarget1.wav": 'Rejuvenation',
    "Abilities\\Spells\\NightElf\\Starfall\\StarfallCaster1.wav": 'StarfallArea',
    "Abilities\\Spells\\Orc\\EarthQuake\\EarthquakeRock.wav": 'Earthquake',
    "Abilities\\Spells\\Orc\\Earthquake\\EarthquakeLoop1.wav": 'EarthquakeLoop',
    "Abilities\\Spells\\Orc\\Ensnare\\EnsnareTarget.wav": 'Ensnare',
    "Abilities\\Spells\\Orc\\EtherealForm\\SpiritWalkerMorph.wav": 'SpiritwalkerMorph',
    "Abilities\\Spells\\Orc\\FeralSpirit\\FeralSpiritTarget1.wav": 'FeralSpiritDone',
    "Abilities\\Spells\\Orc\\HealingWave\\HealingWave.wav": 'HealingWaveTarget',
    "Abilities\\Spells\\Orc\\LightningShield\\LightningShieldTarget.wav": 'LightningShield',
    "Abilities\\Spells\\Orc\\Purge\\PurgeTarget1.wav": 'Purge',
    "Abilities\\Spells\\Orc\\Shockwave\\Shockwave.wav": 'ShockWave',
    "Abilities\\Spells\\Orc\\SpiritLink\\SpiritLink1.wav": 'SpiritLink',
    "Abilities\\Spells\\Other\\BreathOfFrost\\BreathOfFrost1.wav": 'BreathOfFrost',
    "Abilities\\Spells\\Other\\LoadUnload\\Loading.wav": 'LoadUnload',
    "Abilities\\Spells\\Undead\\AntiMagicShell\\AntiMagicShellBirth1.wav": 'AntiMagicShell',
    "Abilities\\Spells\\Undead\\Cripple\\CrippleTarget1.wav": 'Cripple',
    "Abilities\\Spells\\Undead\\DarkRitual\\DarkRitualTarget1.wav": 'DarkRitual',
    "Abilities\\Spells\\Undead\\DarkSummoning\\DarkSummoningLaunch1.wav": 'DarkSummoningMissileLaunch',
    "Abilities\\Spells\\Undead\\DarkSummoning\\DarkSummoningTarget1.wav": 'DarkSummoningTarget',
    "Abilities\\Spells\\Undead\\DeathPact\\DeathPactTargetBirth1.wav": 'DeathPactTarget',
    "Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorTarget1.wav": 'FrostArmor',
    "Abilities\\Spells\\Undead\\Possession\\PossessionMissileHit1.wav": 'PossessionMissileHit',
    "Abilities\\Spells\\Undead\\Possession\\PossessionMissileLaunch1.wav": 'PossessionMissileLaunch',
    "Abilities\\Spells\\Undead\\RaiseSkeletonWarrior\\RaiseSkeleton.wav": 'RaiseSkeletonArcher',
    "Abilities\\Spells\\Undead\\UnholyFrenzy\\UnholyFrenzyBirth1.wav": 'UnholyFrenzy',
    "Abilities\\Weapons\\AncientProtectorMissile\\AncientProtectorMissileLaunch2.wav": 'AncientProtectorMissileLaunch',
    "Abilities\\Weapons\\AncientProtectorMissile\\AncientProtectorMissileLaunch3.wav": 'AncientProtectorMissileLaunch',
    "Abilities\\Weapons\\Arrow\\ArrowAttack1.wav": 'ArrowLaunch',
    "Abilities\\Weapons\\Arrow\\ArrowImpact.wav": 'ArrowHit',
    "Abilities\\Weapons\\Axe\\AxeMissile1.wav": 'AxeMissileHit',
    "Abilities\\Weapons\\BristleBackMissile\\BristleBackMissileLaunch1.wav": 'BristleBackMissileLaunch',
    "Abilities\\Weapons\\BristleBackMissile\\BristleBackMissileLaunch2.wav": 'BristleBackMissileLaunch',
    "Abilities\\Weapons\\BristleBackMissile\\BristleBackMissileLaunch3.wav": 'BristleBackMissileLaunch',
    "Abilities\\Weapons\\Catapult\\CatapultMissile3.wav": 'Catapult',
    "Abilities\\Weapons\\Catapult\\CatapultMissile4.wav": 'Catapult',
    "Abilities\\Weapons\\ChimaeraAcidMissile\\ChimaeraAlternateMissileHit1.wav": 'ChimaeraAcidHit',
    "Abilities\\Weapons\\ColdArrow\\ColdArrow1.wav": 'ColdArrow',
    "Abilities\\Weapons\\ColdArrow\\ColdArrow2.wav": 'ColdArrow',
    "Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissileHit2.wav": 'DemonHunterMissileHit',
    "Abilities\\Weapons\\Dryadmissile\\DryadMissile1.wav": 'DryadMissile',
    "Abilities\\Weapons\\Dryadmissile\\DryadMissile2.wav": 'DryadMissile',
    "Abilities\\Weapons\\FireBallMissile\\FireBallMissileDeath.wav": 'Fireball',
    "Abilities\\Weapons\\KeeperGroveMissile\\KeeperOfTheGroveMissileLaunch3.wav": 'KeeperOfTheGroveMissileLaunch',
    "Abilities\\Weapons\\SentinelMissile\\HuntressMissileLaunch.wav": 'SentinelMissileLaunch',
    "Buildings\\Human\\Blacksmith\\BlacksmithWhat1.wav": 'BlacksmithWhat',
    "Buildings\\Naga\\TidalGuardian\\TidalGuardianWhat1.wav": 'TidalGuardianWhat',
    "Buildings\\NightElf\\AncientOfWind\\AncientOfTheWildYes1.wav": 'AncientOfWindYes',
    "Buildings\\NightElf\\AncientOfWind\\AncientOfTheWildYes2.wav": 'AncientOfWindYes',
    "Buildings\\NightElf\\AncientOfWind\\AncientOfTheWildYes3.wav": 'AncientOfWindYes',
    "Buildings\\NightElf\\AncientOfWind\\AncientOfTheWildYesAttack1.wav": 'AncientOfWindYesAttack',
    "Buildings\\NightElf\\AncientOfWind\\AncientOfTheWildYesAttack2.wav": 'AncientOfWindYesAttack',
    "Buildings\\NightElf\\AncientOfWind\\AncientOfTheWildYesAttack3.wav": 'AncientOfWindYesAttack',
    "Buildings\\NightElf\\ChimaeraRoost\\DenOfShadowsWhat1.wav": 'ChimaeraRoostWhat',
    "Buildings\\NightElf\\EntangledGoldMine\\NightElfGoldMineWhat1.wav": 'EntangledGoldMineWhat',
    "Buildings\\NightElf\\HuntersHall\\HuntersHallWhat1.wav": 'HuntersHallWhat',
    "Buildings\\Other\\GoldMine\\GoldMineDeath1.wav": 'GoldMineDeath',
    "Buildings\\Undead\\GargoyleSpire\\GargoyleSpireWhat1.wav": 'GargoyleSpireWhat',
    "Buildings\\Undead\\Graveyard\\GraveYardWhat1.wav": 'GraveyardWhat',
    "Buildings\\Undead\\HauntedMine\\UndeadMiningWhat1.wav": 'HauntedMineWhat',
    "Buildings\\Undead\\Necropolis\\NecropolisUpgrade2.wav": 'Necropolisu2What',
    "Buildings\\Undead\\SacrificialPit\\SacrificialPitWhat1.wav": 'SacrificialPitWhat',
    "Buildings\\Undead\\SlaughterHouse\\SlaughterHouseWhat1.wav": 'SlaughterHouseWhat',
    "Doodads\\Cinematic\\DungeonLever\\Lever.wav": 'LeverDeath',
    "Doodads\\Cinematic\\Lightningbolt\\LightningBolt1.wav": 'CinematicLightningBolt',
    "Doodads\\LordaeronSummer\\Terrain\\Gate\\GateEpicDeath.wav": 'GateDeath',
    "Doodads\\Northrend\\Water\\Battleship\\BattleShipDeath1.wav": 'BattleShipDeath',
    "Sound\\Ambient\\BattleNetWindStereoLoop1.wav": 'GlueScreenBnetWind',
    "Sound\\Ambient\\CreepSleepLoop1.wav": 'CreepSleepSnoreLoop',
    "Sound\\Ambient\\DoodadEffects\\BlueFireBurstLoop.wav": 'BlueFireLoop',
    "Sound\\Ambient\\DoodadEffects\\CityScapeCathedralLoop1.wav": 'CathedralLoop',
    "Sound\\Ambient\\DoodadEffects\\CityScapeMagicRunesLoop1.wav": 'MagicRunesLoop',
    "Sound\\Ambient\\DoodadEffects\\CityscapeFountainLoop1.wav": 'FountainLoop',
    "Sound\\Ambient\\DoodadEffects\\DoomGuardWhat4.wav": 'DoomGuardHuh1',
    "Sound\\Ambient\\DoodadEffects\\DoomGuardWhat5.wav": 'DoomGuardHuh2',
    "Sound\\Ambient\\DoodadEffects\\DoomGuardWhat6.wav": 'DoomGuardHuh3',
    "Sound\\Ambient\\DoodadEffects\\DoomGuardWhat7.wav": 'DoomGuardHuh4',
    "Sound\\Ambient\\DoodadEffects\\DoorSlam1.wav": 'DoorSlamSound',
    "Sound\\Ambient\\DoodadEffects\\Earthquake.wav": 'EarthquakeWithRocksLoop',
    "Sound\\Ambient\\DoodadEffects\\EyeOfSargeras.wav": 'EyeOfSargerasLoop',
    "Sound\\Ambient\\DoodadEffects\\FrostmourneChant1.wav": 'FrostmourneChantSound',
    "Sound\\Ambient\\DoodadEffects\\FrostmourneLoopUndead01.wav": 'FrostmourneLoop',
    "Sound\\Ambient\\DoodadEffects\\GateEpicBash.wav": 'GateEpicBashSound',
    "Sound\\Ambient\\DoodadEffects\\GateOpen.wav": 'CityEntranceGateOpen',
    "Sound\\Ambient\\DoodadEffects\\HoofSteps1.wav": 'MalfurionHoofSteps',
    "Sound\\Ambient\\DoodadEffects\\KaelReady1_H04X.wav": 'KaelReadyX',
    "Sound\\Ambient\\DoodadEffects\\LadyVashjReady1_H04X.wav": 'LadyVashjReadyX',
    "Sound\\Ambient\\DoodadEffects\\LargeCityGateOpen1.wav": 'GateOpenSound',
    "Sound\\Ambient\\DoodadEffects\\LordaeronSummerBrazierLoop1.wav": 'LordSumBrazierLoop',
    "Sound\\Ambient\\DoodadEffects\\LordaeronSummerFliesLoop1.wav": 'FliesLoop',
    "Sound\\Ambient\\DoodadEffects\\NorthrendBattleshipLoop1.wav": 'BattleshipLoop',
    "Sound\\Ambient\\DoodadEffects\\RollingThunder1.wav": 'RollingThunderSound',
    "Sound\\Ambient\\DoodadEffects\\RunesGlow.wav": 'RunesGlowLoop',
    "Sound\\Ambient\\DoodadEffects\\Seagull1.wav": 'SeagullSound',
    "Sound\\Ambient\\DoodadEffects\\ShimmeringPortalEntrance.wav": 'EnterShimmeringPortal',
    "Sound\\Ambient\\DoodadEffects\\TheHornOfCenarius.wav": 'HornOfCenariusSound',
    "Sound\\Ambient\\DoodadEffects\\UtherReturns.wav": 'UtherReturnsSound',
    "Sound\\Ambient\\DoodadEffects\\WarlockAppears.wav": 'ArchimondeAppearsSound',
    "Sound\\Ambient\\DoodadEffects\\WaterLakeLoop1.wav": 'LakeLoop',
    "Sound\\Ambient\\DoodadEffects\\WaterStreamLoop1.wav": 'StreamLoop',
    "Sound\\Ambient\\DoodadEffects\\WaterWaterFallLoop1.wav": 'WaterfallLoop',
    "Sound\\Ambient\\DoodadEffects\\WaterWavesLoop1.wav": 'WavesLoop',
    "Sound\\Ambient\\RainAmbience.wav": 'AmbientSoundRain',
    "Sound\\Ambient\\UndeadGlueScreenLoop1.wav": 'UndeadGlueScreenLoop',
    "Sound\\Ambient\\WindLoopStereo.wav": 'AmbientSoundTestWind',
    "Sound\\Buildings\\Death\\AncientUprootDeath1.wav": 'DeathWalkingNightElfBuilding',
    "Sound\\Buildings\\Death\\BuildingDeathLargeHuman.wav": 'DeathHumanLargeBuilding',
    "Sound\\Buildings\\Death\\BuildingDeathLargeOrc.wav": 'DeathOrcLargeBuilding',
    "Sound\\Buildings\\Death\\BuildingDeathSmallHuman.wav": 'RockWallDeath',
    "Sound\\Buildings\\Death\\CityBuildingDeath1.wav": 'DeathCityBuilding',
    "Sound\\Buildings\\Death\\CityScapeBridgeDeath1.wav": 'DeathBridge',
    "Sound\\Buildings\\Death\\HCancelBuilding.wav": 'DeathHumanBuildingCancel',
    "Sound\\Buildings\\Death\\NightElfBuildingDeathLarge1.wav": 'DeathNightElfLargeBuilding',
    "Sound\\Buildings\\Death\\NightElfBuildingDeathSmall1.wav": 'DeathNightElfBuildingCancel',
    "Sound\\Buildings\\Death\\OrcBuildingDeathSmall1.wav": 'DeathOrcSmallBuilding',
    "Sound\\Buildings\\Fire\\OrcHumanLargeBuildingFire1.wav": 'HumanFireLarge',
    "Sound\\Buildings\\Fire\\OrcHumanMediumBuildingFire1.wav": 'HumanFireMedium',
    "Sound\\Destructibles\\TreeFall1.wav": 'TreeWallDeath',
    "Sound\\Destructibles\\TreeFall2.wav": 'TreeWallDeath',
    "Sound\\Destructibles\\TreeFall3.wav": 'TreeWallDeath',
    "Sound\\Dialogue\\HumanExpCamp\\Human03x\\Sheep1.wav": 'A03SheepSoundOne',
    "Sound\\Dialogue\\HumanExpCamp\\Human03x\\Sheep2.wav": 'A03SheepSoundTwo',
    "Sound\\Dialogue\\HumanExpCamp\\Human03x\\Sheep3.wav": 'A03SheepSoundThree',
    "Sound\\Dialogue\\HumanExpCamp\\Human06x\\BUTCHER.WAV": 'A06FreshMeat',
    "Sound\\Interface\\BattleNetDoorsStereo2.wav": 'GlueScreenBNetSlam',
    "Sound\\Interface\\BattleNetWooshStereo1.wav": 'GlueScreenBNetExit',
    "Sound\\Interface\\BattlenetBirth1.wav": 'GlueScreenBNetClose',
    "Sound\\Interface\\HeroDropItem1.wav": 'ItemDrop',
    "Sound\\Interface\\PickUpItem.wav": 'ItemGet',
    "Sound\\Interface\\QuestActivateWhat1.wav": 'QuestLogModified',
    "Sound\\Interface\\QuestLog.wav": 'QuestUpdate',
    "Sound\\Interface\\Warning\\NightElf\\SentinelTownAttack1.wav": 'TownAttackNightElf',
    "Sound\\Units\\Footsteps\\Step3.wav": 'DeepFootstep',
    "Sound\\Units\\Footsteps\\Step4.wav": 'DeepFootstep',
    "Units\\Creeps\\BansheeGhost\\BansheeGhostYes2.wav": 'GhostYes',
    "Units\\Creeps\\BansheeGhost\\BansheeGhostYesAttack1.wav": 'GhostYesAttack',
    "Units\\Creeps\\BristleBack\\BristlebackDeath1.wav": 'BristleBackDeath',
    "Units\\Creeps\\FacelessOne\\FacelessOneYes1.wav": 'FacelessOneYesAttack',
    "Units\\Creeps\\FacelessOne\\FacelessOneYes2.wav": 'FacelessOneYesAttack',
    "Units\\Creeps\\Owlbear\\OwlBearYesAttack1.wav": 'OwlbearYesAttack',
    "Units\\Creeps\\RockGolem\\RockGolemAttack2.wav": 'RockGolemAttack2',
    "Units\\Critters\\Sheep\\Sheep1.wav": 'SheepRandomSounds',
    "Units\\Critters\\VillagerMan\\VillagerM1.wav": 'VillagerManWhat',
    "Units\\Critters\\VillagerMan\\VillagerM2.wav": 'VillagerManWhat',
    "Units\\Critters\\VillagerMan\\VillagerMaleDeath1.wav": 'VillagerManDeath',
    "Units\\Critters\\VillagerWoman\\VillagerF1.wav": 'VillagerWomanWhat',
    "Units\\Critters\\VillagerWoman\\VillagerF2.wav": 'VillagerWomanWhat',
    "Units\\Critters\\VillagerWoman\\VillagerF3.wav": 'VillagerWomanWhat',
    "Units\\Demon\\DoomGuard\\BalrogAttack1.wav": 'BalrogAttack1',
    "Units\\Human\\Knight\\HorseLoop1.wav": 'HumanKnightMovement',
    "Units\\Human\\Knight\\HorseLoop2.wav": 'HumanKnightMovement',
    "Units\\Human\\Knight\\HorseLoop3.wav": 'HumanKnightMovement',
    "Units\\Human\\Rifleman\\RiflemanAttack1.wav": 'RiflemanAttack1',
    "Units\\Human\\Rifleman\\RiflemanAttack2.wav": 'RiflemanAttack1',
    "Units\\Human\\Rifleman\\RiflemanReady1.wav": 'RiflemanReady1',
    "Units\\Human\\WaterElemental\\SummonWaterElementalCaster.wav": 'WaterElementalBirth',
    "Units\\NightElf\\HeroKeeperOfTheGrove\\KeeperOfTheGroveWhat3.wav": 'HeroKeeperOfTheGroveWhat',
    "Units\\NightElf\\HeroKeeperOfTheGrove\\KeeperOfTheGroveYesAttack1.wav": 'HeroKeeperOfTheGroveYesAttack',
    "Units\\NightElf\\HeroKeeperOfTheGrove\\KeeperOfTheGroveYesAttack3.wav": 'HeroKeeperOfTheGroveYesAttack',
    "Units\\Orc\\KotoBeast\\KodoBeastPuke1.wav": 'DevourPuke',
    "Units\\Orc\\SpiritWalker\\WhiteTaurenWhat4.wav": 'SpiritWalkerWhat',
    "Units\\Orc\\SpiritWalker\\WhiteTaurenYes2.wav": 'SpiritWalkerYes',
    "Units\\Orc\\SpiritWalker\\WhiteTaurenYes3.wav": 'SpiritWalkerYes',
    "Units\\Undead\\FrostWyrm\\FrostwyrmReady1.wav": 'FrostWyrmReady',
    "Units\\Undead\\FrostWyrm\\FrostwyrmWhat1.wav": 'FrostWyrmWhat',
    "Units\\Undead\\FrostWyrm\\FrostwyrmWhat3.wav": 'FrostWyrmWhat',
    "Units\\Undead\\FrostWyrm\\FrostwyrmYes1.wav": 'FrostWyrmYes',
    "Units\\Undead\\FrostWyrm\\FrostwyrmYesAttack3.wav": 'FrostWyrmYesAttack',
    "Units\\Undead\\Gargoyle\\GargoyleMorph1.wav": 'StoneFormMorph1',
    "Units\\Undead\\Meatwagon\\MeatWagonReady1.wav": 'MeatwagonReady',
    "Units\\Undead\\Meatwagon\\MeatWagonWhat1.wav": 'MeatwagonWhat',
    "Units\\Undead\\Meatwagon\\MeatWagonWhat2.wav": 'MeatwagonWhat',
    "Units\\Undead\\Meatwagon\\MeatWagonWhat3.wav": 'MeatwagonWhat',
    "Units\\Undead\\Meatwagon\\MeatWagonYes1.wav": 'MeatwagonYes',
    "Units\\Undead\\Meatwagon\\MeatWagonYes2.wav": 'MeatwagonYes',
    "Units\\Undead\\Meatwagon\\MeatWagonYes3.wav": 'MeatwagonYes',
    "Units\\Undead\\Meatwagon\\MeatWagonYesAttack2.wav": 'MeatwagonYesAttack',
    "Units\\Undead\\ObsidianStatue\\ObsidianAvengerYes1.wav": 'ObsidianDestroyerYes',
    "Units\\Undead\\ObsidianStatue\\ObsidianAvengerYes2.wav": 'ObsidianDestroyerYes',
    "Units\\Undead\\ObsidianStatue\\ObsidianAvengerYes3.wav": 'ObsidianDestroyerYes',
}
"""
Sound path -> label
Sensible defaults are excluded. Sensible defaults are calculated by:
1. Taking the path's stem
2. Stripping off any trailing digits if:
  1. The first path element is units/
  2. OR the first path element is sounds/ AND the second path element is neither dialog/ nor ambient/
"""

UNIT_TO_COLOUR = {
    'nmer': 0,  # Lordaeron Summer camp
    'nmr2': 12,  # Lordaeron Fall camp
    'nmr3': 1,  # Lordaeron Winter camp
    'nmr4': 11,  # Barrens camp
    'nmr5': 10,  # Ashenvale camp
    'nmr6': 6,  # Felwood camp
    'nmr7': 3,  # Northrend camp
    'nmr8': 9,  # Cityscape camp
    'nmr9': 8,  # Dalaran camp
    'nmr0': 5,  # Village camp
    'nmra': 0,  # Dungeon camp
    'nmrb': 0,  # Underground camp
    'nmrc': 1,  # Sunken Ruins camp
    'nmrd': 9,  # Icecrown Glacier camp
    'nmre': 12,  # Outland camp
    'nmre': 3,  # Black Citadel camp
    'ntav': 0,  # Tavern
    'nmrk': 0,  # Marketplace
}
