# Warcraft 3 Map Objects File (.w3o)
# See w3o.py for type definitions
version = 2
has_levels = false

[blizzard_objects]
entities = []

[map_objects]
[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I010'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_013'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_014'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_007'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_015'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I011'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_016'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_017'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_018'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_019'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I012'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_020'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_021'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_022'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_023'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I013'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_024'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_025'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_026'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_027'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I014'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_028'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_029'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_030'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_031'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I015'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_032'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_033'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_034'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_035'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I016'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_036'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_037'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_038'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_039'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I017'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_040'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_041'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_042'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_043'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I018'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_044'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_045'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_046'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_047'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I019'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_048'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_049'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_050'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_051'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I01A'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_054'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_055'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_056'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'TRIGSTR_057'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'
