# Warcraft 3 Map Objects File (.w3o)
# See w3o.py for type definitions
version = 2
has_levels = false

[blizzard_objects]
entities = []

[map_objects]
[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I010'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 0'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 0.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 0 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'isel'  # ItemData.Can Be Sold By Merchants
data_type = "Integer"
variation_level = 0
table_column = 0
value = 1
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'igol'  # ItemData.Gold Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 500
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I011'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 1'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 1.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 1 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I012'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 2'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 2.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 2 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I013'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 3'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 3.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 3 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I014'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 4'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 4.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 4 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I015'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 5'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 5.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 5 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I016'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 6'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 6.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 6 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I017'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 7'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 7.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 7 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I018'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 8'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 8.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 8 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I019'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 9'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 9.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 9 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'

[[map_objects.entities]]
parent_id = 'lmbr'  # Bundle of Lumber
entity_id = 'I01A'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = 'Archipelago Item 10'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utip'  # Profile.Tooltip - Basic
data_type = "String"
variation_level = 0
table_column = 0
value = 'Purchase a check for map location 10.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utub'  # Profile.Tooltip - Extended
data_type = "String"
variation_level = 0
table_column = 0
value = 'Get a randomized item when used.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ides'  # Profile.Description
data_type = "String"
variation_level = 0
table_column = 0
value = 'Collects map location 10 for the player.'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iico'  # Profile.Interface Icon
data_type = "String"
variation_level = 0
table_column = 0
value = 'ReplaceableTextures\CommandButtons\BTNSelectHeroOn.blp'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ifil'  # ItemData.Model Used
data_type = "String"
variation_level = 0
table_column = 0
value = 'war3mapImported\questionmark_item.mdl'
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'iabi'  # ItemData.Abilities
data_type = "String"
variation_level = 0
table_column = 0
value = ''
object_id = 'null'
