# Warcraft 3 Map Info File(.w3i)
# See w3i.py for type definitions

version = "TFT"
map_revision = 445
editor_version = 6061
map_name = 'TRIGSTR_004'
map_author = 'TRIGSTR_060'
map_description = 'TRIGSTR_156'
players_recommended = 'TRIGSTR_027'
camera_bounds = [-5632.0, -6144.0, 4608.0, 5632.0, -5632.0, 5632.0, 4608.0, -6144.0]
map_padding_left = 8
map_padding_right = 32
map_padding_top = 22
map_padding_bottom = 10
map_playable_width = 88
map_playable_height = 96
flags = "HIDE_MINIMAP|FIXED_FORCES|CUSTOM_FORCES|CUSTOM_TECH_TREE|CUSTOM_ABILITIES|CUSTOM_UPGRADES|PROPERTIES_MENU_OPENED|WAVES_ON_CLIFFS|WAVES_ON_SHORES|REQUIRES_EXPANSION"
tileset = { type = "bytes", value = "V" }
campaign_background = 6
tft_loading_screen_model_path = ''
map_loading_screen_text = 'TRIGSTR_029'
map_loading_screen_title = 'TRIGSTR_061'
map_loading_screen_subtitle = 'TRIGSTR_082'
map_game_data_set = 0
tft_prologue_screen_path = ''
prologue_screen_text = ''
prologue_screen_title = ''
prologue_screen_subtitle = ''
tft_uses_terrain_fog = 0
tft_fog_start_z = 0.0
tft_fog_end_z = 0.0
tft_fog_density = 0.0
tft_fog_red = 0
tft_fog_green = 0
tft_fog_blue = 0
tft_fog_alpha = 0
tft_weather = 'null'
tft_custom_sound_environment = ''
tft_custom_light_tileset = { type = "bytes", value = "0" }
tft_water_tint_red = 0
tft_water_tint_green = 0
tft_water_tint_blue = 0
tft_water_tint_alpha = 0
random_entities = []
random_items = []

[[players]]

player_id = 0
player_type = "Neutral"
player_faction = "Human"
fixed_start_position = true
name = 'TRIGSTR_087'
start_pos = [-1280.0, 1984.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[players]]

player_id = 1
player_type = "Human"
player_faction = "Human"
fixed_start_position = true
name = 'TRIGSTR_135'
start_pos = [-2048.0, -4288.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[players]]

player_id = 5
player_type = "Computer"
player_faction = "Orc"
fixed_start_position = true
name = 'TRIGSTR_036'
start_pos = [3072.0, 3008.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[players]]

player_id = 6
player_type = "Computer"
player_faction = "Undead"
fixed_start_position = true
name = 'TRIGSTR_036'
start_pos = [-4928.0, 576.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[players]]

player_id = 7
player_type = "Neutral"
player_faction = "Human"
fixed_start_position = true
name = 'TRIGSTR_019'
start_pos = [-256.0, 2752.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[forces]]

force_flags = "None"
player_mask_flags = 0xffffff9e
name = 'TRIGSTR_135'

[[forces]]

force_flags = "None"
player_mask_flags = 0x61
name = 'TRIGSTR_036'

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhme'  # Iron Forged Swords,Steel Forged Swords,Mithril Forged Swords
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhme'  # Iron Forged Swords,Steel Forged Swords,Mithril Forged Swords
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhra'  # Black Gunpowder,Refined Gunpowder,Imbued Gunpowder
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhra'  # Black Gunpowder,Refined Gunpowder,Imbued Gunpowder
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhaa'
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhaa'
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhar'  # Iron Plating,Steel Plating,Mithril Plating
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhar'  # Iron Plating,Steel Plating,Mithril Plating
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhmi'
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhac'  # Improved Masonry,Advanced Masonry,Imbued Masonry
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhac'  # Improved Masonry,Advanced Masonry,Imbued Masonry
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhss'  # Control Magic
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhan'  # Animal War Training
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhpt'  # Priest Adept Training,Priest Master Training
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhst'  # Sorceress Adept Training,Sorceress Master Training
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhst'  # Sorceress Adept Training,Sorceress Master Training
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhla'  # Studded Leather Armor,Reinforced Leather Armor,Dragonhide Armor
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhla'  # Studded Leather Armor,Reinforced Leather Armor,Dragonhide Armor
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhlh'  # Improved Lumber Harvesting,Advanced Lumber Harvesting
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhse'  # Magic Sentry
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhsr'
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhfl'  # Flare
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhgb'  # Flying Machine Bombs
level = 0
availability = "Unavailable"

[[technologies]]

player_flags = 0x2
tech_id = 'Stpr'

[[technologies]]

player_flags = 0x2
tech_id = 'Stpm'

[[technologies]]

player_flags = 0x2
tech_id = 'hkni'  # Knight

[[technologies]]

player_flags = 0x2
tech_id = 'hgyr'  # Flying Machine

[[technologies]]

player_flags = 0x2
tech_id = 'hgry'  # Gryphon Rider

[[technologies]]

player_flags = 0x2
tech_id = 'hsor'  # Sorceress

[[technologies]]

player_flags = 0x2
tech_id = 'Hamg'  # Archmage

[[technologies]]

player_flags = 0x2
tech_id = 'Hmkg'  # Mountain King

[[technologies]]

player_flags = 0x2
tech_id = 'Hpal'  # Paladin

[[technologies]]

player_flags = 0x2
tech_id = 'hcas'  # Castle

[[technologies]]

player_flags = 0x2
tech_id = 'hgra'  # Gryphon Aviary

[[technologies]]

player_flags = 0x2
tech_id = 'hctw'  # Cannon Tower

[[technologies]]

player_flags = 0x2
tech_id = 'hmtt'  # Siege Engine

[[technologies]]

player_flags = 0x2
tech_id = 'hstt'

[[technologies]]

player_flags = 0xf
tech_id = 'Hblm'  # Blood Mage

[[technologies]]

player_flags = 0xf
tech_id = 'Oshd'  # Shadow Hunter

[[technologies]]

player_flags = 0xf
tech_id = 'Ucrl'  # Crypt Lord

[[technologies]]

player_flags = 0xf
tech_id = 'Ewar'  # Warden