# Warcraft 3 Map Info File(.w3i)
# See w3i.py for type definitions

version = "ROC"
map_revision = 391
editor_version = 4444
map_name = 'TRIGSTR_000'
map_author = 'TRIGSTR_003'
map_description = 'TRIGSTR_002'
players_recommended = 'TRIGSTR_001'
camera_bounds = [-6144.0, -6656.0, 4864.0, 4864.0, -6144.0, 4864.0, 4864.0, -6656.0]
map_padding_left = 12
map_padding_right = 22
map_padding_top = 12
map_padding_bottom = 22
map_playable_width = 94
map_playable_height = 94
flags = "HIDE_MINIMAP|FIXED_FORCES|CUSTOM_FORCES|CUSTOM_TECH_TREE|CUSTOM_UPGRADES|PROPERTIES_MENU_OPENED|WAVES_ON_CLIFFS|WAVES_ON_SHORES"
tileset = { type = "bytes", value = "L" }
campaign_background = 3
tft_loading_screen_model_path = ''
map_loading_screen_text = 'TRIGSTR_006'
map_loading_screen_title = 'TRIGSTR_004'
map_loading_screen_subtitle = 'TRIGSTR_005'
map_loading_screen_number = 0
tft_prologue_screen_path = ''
prologue_screen_text = ''
prologue_screen_title = ''
prologue_screen_subtitle = ''
tft_uses_terrain_fog = 0
tft_fog_start_z = 0.0
tft_fog_end_z = 0.0
tft_fog_density = 0.0
tft_fog_red = 0
tft_fog_green = 0
tft_fog_blue = 0
tft_fog_alpha = 0
tft_weather = ''
tft_custom_sound_environment = ''
tft_custom_light_tileset = { type = "bytes", value = "0" }
tft_water_tint_red = 0
tft_water_tint_green = 0
tft_water_tint_blue = 0
tft_water_tint_alpha = 0
random_entities = []
random_items = []

[[players]]

player_id = 0
player_type = "Computer"
player_faction = "Orc"
fixed_start_position = true
name = 'TRIGSTR_039'
start_pos = [-768.0, 2240.0]
ally_low_priorities_flags = 0xc5b80000
ally_high_priorities_flags = 0xc5c00000

[[players]]

player_id = 1
player_type = "Human"
player_faction = "Human"
fixed_start_position = true
name = 'TRIGSTR_293'
start_pos = [-3776.0, -4096.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[players]]

player_id = 2
player_type = "Neutral"
player_faction = "Human"
fixed_start_position = true
name = 'TRIGSTR_294'
start_pos = [-5888.0, -6144.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[players]]

player_id = 3
player_type = "Computer"
player_faction = "Orc"
fixed_start_position = true
name = 'TRIGSTR_039'
start_pos = [-4288.0, 4096.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[players]]

player_id = 4
player_type = "Computer"
player_faction = "Orc"
fixed_start_position = true
name = 'TRIGSTR_039'
start_pos = [-4032.0, -3520.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[players]]

player_id = 8
player_type = "Neutral"
player_faction = "Human"
fixed_start_position = true
name = 'TRIGSTR_393'
start_pos = [-5888.0, -6144.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[players]]

player_id = 9
player_type = "Computer"
player_faction = "Human"
fixed_start_position = true
name = 'TRIGSTR_391'
start_pos = [-3712.0, -4096.0]
ally_low_priorities_flags = 0x0
ally_high_priorities_flags = 0x0

[[forces]]

force_flags = "None"
player_mask_flags = 0xfffffee2
name = 'TRIGSTR_392'

[[forces]]

force_flags = "None"
player_mask_flags = 0x100
name = 'TRIGSTR_393'

[[forces]]

force_flags = "Allied|ShareVision"
player_mask_flags = 0x19
name = 'TRIGSTR_039'

[[forces]]

force_flags = "Allied|ShareVision"
player_mask_flags = 0x4
name = 'TRIGSTR_294'

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Rome'  # Steel Melee Weapons,Thorium Melee Weapons,Arcanite Melee Weapons
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Rome'  # Steel Melee Weapons,Thorium Melee Weapons,Arcanite Melee Weapons
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Rora'  # Steel Ranged Weapons,Thorium Ranged Weapons,Arcanite Ranged Weapons
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Rora'  # Steel Ranged Weapons,Thorium Ranged Weapons,Arcanite Ranged Weapons
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Rora'  # Steel Ranged Weapons,Thorium Ranged Weapons,Arcanite Ranged Weapons
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Roaa'
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Roaa'
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Roaa'
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Roar'  # Steel Armor,Thorium Armor,Arcanite Armor
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Roar'  # Steel Armor,Thorium Armor,Arcanite Armor
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Romi'
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Romi'
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Roac'
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Roac'
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Ross'
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x7
upgrade_id = 'Ross'
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhme'  # Iron Forged Swords,Steel Forged Swords,Mithril Forged Swords
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhme'  # Iron Forged Swords,Steel Forged Swords,Mithril Forged Swords
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhra'  # Black Gunpowder,Refined Gunpowder,Imbued Gunpowder
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhra'  # Black Gunpowder,Refined Gunpowder,Imbued Gunpowder
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhaa'
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhaa'
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhaa'
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhar'  # Iron Plating,Steel Plating,Mithril Plating
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhar'  # Iron Plating,Steel Plating,Mithril Plating
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhmi'
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhmi'
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhac'  # Improved Masonry,Advanced Masonry,Imbued Masonry
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhac'  # Improved Masonry,Advanced Masonry,Imbued Masonry
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhac'  # Improved Masonry,Advanced Masonry,Imbued Masonry
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhss'  # Control Magic
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhss'  # Control Magic
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhde'  # Defend
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhan'  # Animal War Training
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhpt'  # Priest Adept Training,Priest Master Training
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhpt'  # Priest Adept Training,Priest Master Training
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhst'  # Sorceress Adept Training,Sorceress Master Training
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhst'  # Sorceress Adept Training,Sorceress Master Training
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhla'  # Studded Leather Armor,Reinforced Leather Armor,Dragonhide Armor
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhla'  # Studded Leather Armor,Reinforced Leather Armor,Dragonhide Armor
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhri'  # Long Rifles
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhlh'  # Improved Lumber Harvesting,Advanced Lumber Harvesting
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhlh'  # Improved Lumber Harvesting,Advanced Lumber Harvesting
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhse'  # Magic Sentry
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xe
upgrade_id = 'Rhsr'
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xc
upgrade_id = 'Rhra'  # Black Gunpowder,Refined Gunpowder,Imbued Gunpowder
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rows'  # Pulverize
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Roen'  # Ensnare
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rowt'  # Spirit Walker Adept Training,Spirit Walker Master Training
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rovs'  # Envenomed Spears
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rowd'  # Witch Doctor Adept Training,Witch Doctor Master Training
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rowd'  # Witch Doctor Adept Training,Witch Doctor Master Training
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rost'  # Shaman Adept Training,Shaman Master Training
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rost'  # Shaman Adept Training,Shaman Master Training
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rolh'
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rolh'
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Ronv'
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rosp'  # Spiked Barricades,Improved Spiked Barricades,Advanced Spiked Barricades
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rosp'  # Spiked Barricades,Improved Spiked Barricades,Advanced Spiked Barricades
level = 2
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rosp'  # Spiked Barricades,Improved Spiked Barricades,Advanced Spiked Barricades
level = 1
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Rome'  # Steel Melee Weapons,Thorium Melee Weapons,Arcanite Melee Weapons
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Roar'  # Steel Armor,Thorium Armor,Arcanite Armor
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x5
upgrade_id = 'Robs'  # Berserker Strength
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xc
upgrade_id = 'Rhme'  # Iron Forged Swords,Steel Forged Swords,Mithril Forged Swords
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xc
upgrade_id = 'Rhar'  # Iron Plating,Steel Plating,Mithril Plating
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0xc
upgrade_id = 'Rhla'  # Studded Leather Armor,Reinforced Leather Armor,Dragonhide Armor
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x2
upgrade_id = 'Rhfl'  # Flare
level = 0
availability = "Unavailable"

[[upgrades]]

player_flags = 0x1
upgrade_id = 'Rotr'  # Troll Regeneration,Improved Troll Regeneration,Advanced Troll Regeneration
level = 0
availability = "Unavailable"

[[technologies]]

player_flags = 0xc
tech_id = 'hpea'  # Peasant

[[technologies]]

player_flags = 0xc
tech_id = 'hfoo'  # Footman

[[technologies]]

player_flags = 0xe
tech_id = 'hkni'  # Knight

[[technologies]]

player_flags = 0xe
tech_id = 'hrif'  # Rifleman

[[technologies]]

player_flags = 0xe
tech_id = 'hmtm'  # Mortar Team

[[technologies]]

player_flags = 0xe
tech_id = 'hgyr'  # Flying Machine

[[technologies]]

player_flags = 0xe
tech_id = 'hgry'  # Gryphon Rider

[[technologies]]

player_flags = 0xe
tech_id = 'hmpr'  # Priest

[[technologies]]

player_flags = 0xe
tech_id = 'hsor'  # Sorceress

[[technologies]]

player_flags = 0xe
tech_id = 'hwat'  # Water Elemental

[[technologies]]

player_flags = 0xe
tech_id = 'Hamg'  # Archmage

[[technologies]]

player_flags = 0xe
tech_id = 'Hmkg'  # Mountain King

[[technologies]]

player_flags = 0xe
tech_id = 'Hpal'  # Paladin

[[technologies]]

player_flags = 0xc
tech_id = 'htow'  # Town Hall

[[technologies]]

player_flags = 0xe
tech_id = 'hkee'  # Keep

[[technologies]]

player_flags = 0xe
tech_id = 'hcas'  # Castle

[[technologies]]

player_flags = 0xc
tech_id = 'hhou'  # Farm

[[technologies]]

player_flags = 0xc
tech_id = 'halt'  # Altar of Kings

[[technologies]]

player_flags = 0xc
tech_id = 'hbar'  # Barracks

[[technologies]]

player_flags = 0xc
tech_id = 'hlum'  # Lumber Mill

[[technologies]]

player_flags = 0xe
tech_id = 'hbla'  # Blacksmith

[[technologies]]

player_flags = 0xe
tech_id = 'harm'  # Workshop

[[technologies]]

player_flags = 0xe
tech_id = 'hars'  # Arcane Sanctum

[[technologies]]

player_flags = 0xe
tech_id = 'hgra'  # Gryphon Aviary

[[technologies]]

player_flags = 0xc
tech_id = 'hwtw'  # Scout Tower

[[technologies]]

player_flags = 0xc
tech_id = 'hgtw'  # Guard Tower

[[technologies]]

player_flags = 0xe
tech_id = 'hctw'  # Cannon Tower

[[technologies]]

player_flags = 0x1
tech_id = 'otau'  # Tauren

[[technologies]]

player_flags = 0x1
tech_id = 'ocat'  # Demolisher

[[technologies]]

player_flags = 0x1
tech_id = 'okod'  # Kodo Beast

[[technologies]]

player_flags = 0x1
tech_id = 'owyv'  # Wind Rider

[[technologies]]

player_flags = 0x1
tech_id = 'odoc'  # Troll Witch Doctor

[[technologies]]

player_flags = 0x1
tech_id = 'oshm'  # Shaman

[[technologies]]

player_flags = 0x1
tech_id = 'oeye'  # Sentry Ward

[[technologies]]

player_flags = 0x1
tech_id = 'otot'  # Stasis Trap

[[technologies]]

player_flags = 0x1
tech_id = 'oang'  # Ancestral Guardian

[[technologies]]

player_flags = 0x1
tech_id = 'Obla'  # Blademaster

[[technologies]]

player_flags = 0x1
tech_id = 'Ofar'  # Far Seer

[[technologies]]

player_flags = 0x1
tech_id = 'Otch'  # Tauren Chieftain

[[technologies]]

player_flags = 0x1
tech_id = 'ofrt'  # Fortress

[[technologies]]

player_flags = 0x1
tech_id = 'oalt'  # Altar of Storms

[[technologies]]

player_flags = 0x1
tech_id = 'otto'  # Tauren Totem

[[technologies]]

player_flags = 0x1
tech_id = 'osld'  # Spirit Lodge

[[technologies]]

player_flags = 0x1
tech_id = 'otrb'  # Orc Burrow

[[technologies]]

player_flags = 0x1
tech_id = 'Ogrh'  # Blademaster

[[technologies]]

player_flags = 0x1
tech_id = 'Opgh'  # Blademaster

[[technologies]]

player_flags = 0x1
tech_id = 'Ocbh'  # Tauren Chieftain

[[technologies]]

player_flags = 0x1
tech_id = 'Othr'  # Far Seer

[[technologies]]

player_flags = 0x2
tech_id = 'hmtt'  # Siege Engine

[[technologies]]

player_flags = 0x1
tech_id = 'owtw'  # Watch Tower

[[technologies]]

player_flags = 0xe
tech_id = 'hstt'

[[technologies]]

player_flags = 0xe
tech_id = 'htws'

[[technologies]]

player_flags = 0x1
tech_id = 'Obbc'