# Warcraft 3 Minimap Info File (.mmp)
# See mmp.py for type definitions

file_format_version = 0

[[icons]]

icon_type = "GoldMine"
x = 40
y = 191
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 61
y = 197
colour_blue = 255
colour_green = 66
colour_red = 0
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 16
y = 240
colour_blue = 185
colour_green = 230
colour_red = 28
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 16
y = 240
colour_blue = 4
colour_green = 42
colour_red = 78
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 125
y = 62
colour_blue = 3
colour_green = 3
colour_red = 255
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 16
y = 240
colour_blue = 151
colour_green = 150
colour_red = 149
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 50
y = 22
colour_blue = 3
colour_green = 3
colour_red = 255
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 50
y = 22
colour_blue = 129
colour_green = 0
colour_red = 84
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 62
y = 197
colour_blue = 241
colour_green = 191
colour_red = 126
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 55
y = 184
colour_blue = 1
colour_green = 252
colour_red = 255
colour_alpha = 255