# Warcraft 3 Region file (.w3r)
# See w3r.py for type definitions

version = 5

[[regions]]

left = -3040.0
bottom = -4256.0
right = -2944.0
top = -4160.0
region_name = 'Arthas Destination'
region_id = 0
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -4608.0
bottom = -2848.0
right = -4512.0
top = -2752.0
region_name = 'ArthasFinal'
region_id = 30
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -2400.0
bottom = -5792.0
right = -2304.0
top = -5696.0
region_name = 'ArthasStart'
region_id = 26
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 3168.0
bottom = 2048.0
right = 3232.0
top = 2112.0
region_name = 'Blademaster00'
region_id = 8
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 3232.0
bottom = 2080.0
right = 3296.0
top = 2144.0
region_name = 'Blademaster01'
region_id = 11
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 3264.0
bottom = 2016.0
right = 3328.0
top = 2080.0
region_name = 'Blademaster02'
region_id = 13
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 3040.0
bottom = 2048.0
right = 3168.0
top = 2176.0
region_name = 'BlademasterOrigin'
region_id = 18
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -4640.0
bottom = -3296.0
right = -4576.0
top = -3232.0
region_name = 'Crate01'
region_id = 37
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -2144.0
bottom = -4832.0
right = -2080.0
top = -4768.0
region_name = 'Crate02'
region_id = 38
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 2336.0
bottom = -6176.0
right = 2880.0
top = -5536.0
region_name = 'Dragon 001'
region_id = 15
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 3296.0
bottom = -6880.0
right = 3456.0
top = -4896.0
region_name = 'DragonAttack01'
region_id = 16
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 160.0
bottom = -2880.0
right = 256.0
top = -2784.0
region_name = 'Dwarf Pan Point'
region_id = 32
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 0
colour_g = 255
colour_r = 0

[[regions]]

left = -448.0
bottom = -2976.0
right = 320.0
top = -2304.0
region_name = 'Dwarves'
region_id = 14
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -64.0
bottom = -2592.0
right = 0.0
top = -2528.0
region_name = 'Feranor Destination'
region_id = 39
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -3488.0
bottom = -4256.0
right = -3296.0
top = -4064.0
region_name = 'Firepit01'
region_id = 6
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 128
colour_g = 128
colour_r = 128

[[regions]]

left = -192.0
bottom = -3136.0
right = -64.0
top = -3008.0
region_name = 'Firepit02'
region_id = 7
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 128
colour_g = 128
colour_r = 128

[[regions]]

left = -1120.0
bottom = -1312.0
right = -928.0
top = -1120.0
region_name = 'Firepit03'
region_id = 9
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 128
colour_g = 128
colour_r = 128

[[regions]]

left = -2816.0
bottom = -4224.0
right = -2752.0
top = -4160.0
region_name = 'HandlerDestination'
region_id = 36
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -2368.0
bottom = -4032.0
right = -2304.0
top = -3968.0
region_name = 'HandlerStart'
region_id = 21
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -1792.0
bottom = -3232.0
right = -1696.0
top = -3136.0
region_name = 'Horse 1'
region_id = 1
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -2880.0
bottom = -4032.0
right = -2784.0
top = -3936.0
region_name = 'Horse 1 Destination'
region_id = 5
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -1504.0
bottom = -3392.0
right = -1408.0
top = -3296.0
region_name = 'Horse 2'
region_id = 2
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -2816.0
bottom = -4160.0
right = -2720.0
top = -4064.0
region_name = 'Horse 2 Destination'
region_id = 4
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -3136.0
bottom = -2368.0
right = -3008.0
top = -2240.0
region_name = 'MirrorImage01'
region_id = 10
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 0
colour_r = 0

[[regions]]

left = -3872.0
bottom = -2656.0
right = -3744.0
top = -2528.0
region_name = 'MirrorImage02'
region_id = 20
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 0
colour_r = 0

[[regions]]

left = -2688.0
bottom = -5888.0
right = -2176.0
top = -5664.0
region_name = 'Remove Horses'
region_id = 3
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 2560.0
bottom = -5504.0
right = 2624.0
top = -5440.0
region_name = 'Skeleton01'
region_id = 40
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 2784.0
bottom = -5440.0
right = 2848.0
top = -5376.0
region_name = 'Skeleton02'
region_id = 41
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 2496.0
bottom = -6208.0
right = 2560.0
top = -6144.0
region_name = 'Skeleton03'
region_id = 43
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 2688.0
bottom = -6368.0
right = 2752.0
top = -6304.0
region_name = 'Skeleton04'
region_id = 42
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 3648.0
bottom = 4640.0
right = 3744.0
top = 4736.0
region_name = 'SpawnMirrorImage'
region_id = 45
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -5056.0
bottom = -5344.0
right = -1664.0
top = -2432.0
region_name = 'Starting Base 01'
region_id = 23
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 768.0
bottom = -4512.0
right = 1984.0
top = -3072.0
region_name = 'TriggerDwarves'
region_id = 19
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 128
colour_g = 0
colour_r = 0

[[regions]]

left = -3744.0
bottom = -96.0
right = -3072.0
top = 128.0
region_name = 'TriggerMurlocs'
region_id = 44
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -3136.0
bottom = -4032.0
right = -3040.0
top = -3936.0
region_name = 'Uther Destination'
region_id = 34
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -4032.0
bottom = -2880.0
right = -3872.0
top = -2720.0
region_name = 'Uther Patrol 01'
region_id = 22
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -2144.0
bottom = -3776.0
right = -1984.0
top = -3616.0
region_name = 'Uther Patrol 02'
region_id = 27
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -4512.0
bottom = -3072.0
right = -4384.0
top = -2944.0
region_name = 'Uther01'
region_id = 28
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 0
colour_r = 0

[[regions]]

left = -4192.0
bottom = -2816.0
right = -4064.0
top = -2688.0
region_name = 'Uther02'
region_id = 12
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 0
colour_r = 0

[[regions]]

left = -4768.0
bottom = -3040.0
right = -4672.0
top = -2944.0
region_name = 'UtherFinal'
region_id = 29
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 3136.0
bottom = 1920.0
right = 3456.0
top = 2208.0
region_name = 'Villagers'
region_id = 17
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -4928.0
bottom = 32.0
right = -2592.0
top = 1536.0
region_name = 'LakeLoop01'
region_id = 24
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = 3488.0
bottom = -1376.0
right = 4352.0
top = -256.0
region_name = 'LakeLoop02'
region_id = 25
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -4608.0
bottom = -3328.0
right = -3712.0
top = -2592.0
region_name = 'CinematicHide02'
region_id = 31
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 255
colour_r = 255

[[regions]]

left = -4256.0
bottom = -2944.0
right = -2464.0
top = -1376.0
region_name = 'CinematicHide01'
region_id = 33
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 255
colour_r = 255

[[regions]]

left = 1632.0
bottom = 576.0
right = 4576.0
top = 4544.0
region_name = 'BM Cinematic Hide Player Units Here'
region_id = 35
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -4640.0
bottom = -4032.0
right = -4544.0
top = -3680.0
region_name = 'Gold Turnaround'
region_id = 46
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128

[[regions]]

left = -4032.0
bottom = -4160.0
right = -3968.0
top = -3776.0
region_name = 'Gold Dropoff'
region_id = 47
weather_effect_id = 'null'
ambient_sound = ''
colour_b = 255
colour_g = 128
colour_r = 128