# Warcraft 3 Minimap Info File (.mmp)
# See mmp.py for type definitions

file_format_version = 0

[[icons]]
icon_type = "GoldMine"
x = 67
y = 80
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 212
y = 235
colour_blue = 0
colour_green = 252
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 212
y = 228
colour_blue = 3
colour_green = 3
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 212
y = 230
colour_blue = 255
colour_green = 66
colour_red = 0
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 212
y = 231
colour_blue = 185
colour_green = 230
colour_red = 28
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 227
y = 184
colour_blue = 129
colour_green = 0
colour_red = 84
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 212
y = 236
colour_blue = 0
colour_green = 192
colour_red = 32
colour_alpha = 255