# Warcraft 3 Sound file (.w3s)
# See w3s.py for type definitions

version = 1

[[sounds]]

name = 'gg_snd_H06Arthas01'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas01.mp3'
effects = 'DefaultEAXON'
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas03'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas03.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas04'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas04.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas06'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas06.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas08'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas08.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas10'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas10.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas12'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas12.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas14'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas14.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas16'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas16.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas30'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas30.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas33'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas33.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas43'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas43.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Arthas46'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Arthas46.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Jaina13'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Jaina13.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Jaina17'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Jaina17.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06MalGanis31'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06MalGanis31.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06MalGanis32'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06MalGanis32.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06MalGanis41'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06MalGanis41.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06MalGanis42'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06MalGanis42.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06MalGanis44'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06MalGanis44.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06MalGanis45'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06MalGanis45.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Uther02'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Uther02.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Uther05'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Uther05.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Uther07'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Uther07.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Uther09'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Uther09.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Uther11'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Uther11.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06Uther15'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06Uther15.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06VillagerF24'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06VillagerF24.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06VillagerF57'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06VillagerF57.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06VillagerF58'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06VillagerF58.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06VillagerF59'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06VillagerF59.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06VillagerF61'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06VillagerF61.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06VillagerM23'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06VillagerM23.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06VillagerM25'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06VillagerM25.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06VillagerM26'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06VillagerM26.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06VillagerM27'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06VillagerM27.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H06VillagerM28'
file = 'Sound\Dialogue\HumanCampaign\Human06\H06VillagerM28.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_HumanDefeat'
file = 'Sound\Music\mp3Music\HumanDefeat.mp3'
effects = ''
flags = "Music"
fade_in = 0
fade_out = 0
volume = 0
pitch = 0.0
channel = "General"
min_distance = 0.0
max_distance = 0.0
distance_cutoff = 0.0

[[sounds]]

name = 'gg_snd_DoorSlam1'
file = 'Sound\Ambient\DoodadEffects\DoorSlam1.wav'
effects = 'DefaultEAXON'
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_DoorSlam101'
file = 'Sound\Ambient\DoodadEffects\DoorSlam1.wav'
effects = 'DefaultEAXON'
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 1.100000023841858
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_HorseLoop3'
file = 'Units\Human\Knight\HorseLoop3.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_HorseLoop2'
file = 'Units\Human\Knight\HorseLoop2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_KnightNoRiderWhat3'
file = 'Units\Human\KnightNoRider\KnightNoRiderWhat3.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_KnightNoRiderYesAttack1'
file = 'Units\Human\KnightNoRider\KnightNoRiderYesAttack1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_KnightNoRiderWhat2'
file = 'Units\Human\KnightNoRider\KnightNoRiderWhat2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_KnightNoRiderYesAttack2'
file = 'Units\Human\KnightNoRider\KnightNoRiderYesAttack2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_CityScapeCathedralLoop1'
file = 'Sound\Ambient\DoodadEffects\CityScapeCathedralLoop1.wav'
effects = 'DoodadsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_CityBuildingDeath1'
file = 'Sound\Buildings\Death\CityBuildingDeath1.wav'
effects = 'DefaultEAXON'
flags = "NONE"
fade_in = 10
fade_out = 10
volume = 60
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_DarkSummoningTarget1'
file = 'Abilities\Spells\Undead\DarkSummoning\DarkSummoningTarget1.wav'
effects = 'SpellsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_MassTeleportTarget'
file = 'Abilities\Spells\Human\MassTeleport\MassTeleportTarget.wav'
effects = 'SpellsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_WaterStreamLoop1'
file = 'Sound\Ambient\DoodadEffects\WaterStreamLoop1.wav'
effects = 'DoodadsEAX'
flags = "Looping|Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0