# Warcraft 3 Sound file (.w3s)
# See w3s.py for type definitions

version = 1

[[sounds]]
name = 'gg_snd_U03AArthas01'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03AArthas01.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03AKelThuzad02'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03AKelThuzad02.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03AArthas03'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03AArthas03.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03AKelThuzad04'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03AKelThuzad04.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03AArthas05'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03AArthas05.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03AArthas06'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03AArthas06.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03BPriest07'
file = 'Sound\Dialogue\UndeadCampaign\Undead03B\U03BPriest07.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03BArthas08'
file = 'Sound\Dialogue\UndeadCampaign\Undead03B\U03BArthas08.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03AKelThuzad09'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03AKelThuzad09.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03AArthas10'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03AArthas10.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03AElfArcher11'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03AElfArcher11.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03ASylvanas12'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03ASylvanas12.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03AArthas13'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03AArthas13.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03BSylvanas14'
file = 'Sound\Dialogue\UndeadCampaign\Undead03B\U03BSylvanas14.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03BArthas16'
file = 'Sound\Dialogue\UndeadCampaign\Undead03B\U03BArthas16.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03BSylvanas17'
file = 'Sound\Dialogue\UndeadCampaign\Undead03B\U03BSylvanas17.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03BSylvanas18'
file = 'Sound\Dialogue\UndeadCampaign\Undead03B\U03BSylvanas18.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03BArthas19'
file = 'Sound\Dialogue\UndeadCampaign\Undead03B\U03BArthas19.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03ANecromancer31'
file = 'Sound\Dialogue\UndeadCampaign\Undead03A\U03ANecromancer31.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03BHighElfVillager31'
file = 'Sound\Dialogue\UndeadCampaign\Undead03B\U03BHighElfVillager31.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U03BHighElfVillager32'
file = 'Sound\Dialogue\UndeadCampaign\Undead03B\U03BHighElfVillager32.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_SecretFound'
file = 'Sound\Interface\SecretFound.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_GateEpicBash'
file = 'Sound\Ambient\DoodadEffects\GateEpicBash.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_OrcBuildingDeathSmall1'
file = 'Sound\Buildings\Death\OrcBuildingDeathSmall1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_MeatWagonYes1'
file = 'Units\Undead\Meatwagon\MeatWagonYes1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_MeatWagonYes3'
file = 'Units\Undead\Meatwagon\MeatWagonYes3.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_MeatWagonYes2'
file = 'Units\Undead\Meatwagon\MeatWagonYes2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_HorseLoop1'
file = 'Units\Human\Knight\HorseLoop1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_HorseLoop2'
file = 'Units\Human\Knight\HorseLoop2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_HorseLoop3'
file = 'Units\Human\Knight\HorseLoop3.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_GhoulWarcry1'
file = 'Units\Undead\Ghoul\GhoulWarcry1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_GhoulWhat1'
file = 'Units\Undead\Ghoul\GhoulWhat1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_GhoulWhat3'
file = 'Units\Undead\Ghoul\GhoulWhat3.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_WaterLakeLoop1'
file = 'Sound\Ambient\DoodadEffects\WaterLakeLoop1.wav'
effects = 'DoodadsEAX'
flags = "Looping|Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_WaterStreamLoop1'
file = 'Sound\Ambient\DoodadEffects\WaterStreamLoop1.wav'
effects = 'DoodadsEAX'
flags = "Looping|Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_WaterWaterFallLoop1'
file = 'Sound\Ambient\DoodadEffects\WaterWaterFallLoop1.wav'
effects = 'DoodadsEAX'
flags = "Looping|Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1