# Warcraft 3 Minimap Info File (.mmp)
# See mmp.py for type definitions

file_format_version = 0

[[icons]]

icon_type = "House"
x = 35
y = 81
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]

icon_type = "House"
x = 22
y = 81
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 164
y = 104
colour_blue = 3
colour_green = 3
colour_red = 255
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 27
y = 20
colour_blue = 255
colour_green = 66
colour_red = 0
colour_alpha = 255