# Warcraft 3 Doodad placement file (.doo)
# See doo.py for type definitions

version = 8
sub_version = 11
describes_units = true
doodads = []
immobile_doodads = []

[[units]]

type_id = 'sloc'  # Start Location
variation = 0
x = 1536.0
y = 768.0
z = 0.0
facing = 4.71238899230957
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 0
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 0
target_acquisition = 0.0
hero_level = 0
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 3

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Eill'  # Demon Hunter
variation = 0
x = -1669.357666015625
y = 4348.408203125
z = 0.0
facing = 3.399596929550171
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 19

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'e000'
variation = 0
x = 1536.0
y = 768.0
z = 0.0
facing = 0.3601129949092865
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 0
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 0

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'haro'  # Arcane Observatory
variation = 0
x = -1024.0
y = 1024.0
z = 0.0
facing = 4.71238899230957
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 0
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 7

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'nmrk'  # Marketplace
variation = 0
x = -3904.0
y = 1728.0
z = 0.0
facing = 4.71238899230957
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 27
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 4

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'n000'
variation = 0
x = -4416.0
y = 1728.0
z = 0.0
facing = 4.71238899230957
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 27
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 6

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Hart'  # Paladin
variation = 0
x = -4323.470703125
y = 4300.19140625
z = 0.0
facing = 4.79383659362793
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 2

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Hmbr'  # Mountain King
variation = 0
x = -4118.6220703125
y = 4312.11474609375
z = 0.0
facing = 4.075911521911621
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 5

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Hjai'  # Archmage
variation = 0
x = -4234.162109375
y = 4458.30126953125
z = 0.0
facing = 4.6774821281433105
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 8

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Uear'  # Death Knight
variation = 0
x = -3784.064453125
y = 4283.5439453125
z = 0.0
facing = 0.23739078640937805
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 9

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Uktl'  # Lich
variation = 0
x = -3653.92626953125
y = 4417.0302734375
z = 0.0
facing = 4.959702968597412
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 10

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Othr'  # Far Seer
variation = 0
x = -3272.588623046875
y = 4282.009765625
z = 0.0
facing = 5.679737567901611
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 11

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Ocbh'  # Tauren Chieftain
variation = 0
x = -3168.8232421875
y = 4410.5283203125
z = 0.0
facing = 4.188790321350098
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 12

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Ogrh'  # Blademaster
variation = 0
x = -2704.147705078125
y = 4341.69091796875
z = 0.0
facing = 4.1035237312316895
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 13

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Etyr'  # Priestess of the Moon
variation = 0
x = -2264.121337890625
y = 4364.328125
z = 0.0
facing = 4.8869218826293945
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 14

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Efur'  # Keeper of the Grove
variation = 0
x = -2125.900634765625
y = 4360.2880859375
z = 0.0
facing = 4.450589656829834
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 15

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Ewrd'  # Warden
variation = 0
x = -3710.60205078125
y = 3716.07470703125
z = 0.0
facing = 4.690289497375488
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 16

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Etyr'  # Priestess of the Moon
variation = 0
x = -3621.752685546875
y = 3926.7177734375
z = 0.0
facing = 3.4997341632843018
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 17

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Emfr'  # Keeper of the Grove
variation = 0
x = -3823.3779296875
y = 3880.466796875
z = 0.0
facing = 6.021385669708252
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 18

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Eevi'  # Demon Hunter
variation = 0
x = -3225.39599609375
y = 3701.66796875
z = 0.0
facing = 4.71238899230957
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 1

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Hkal'  # Blood Mage
variation = 0
x = -3323.68310546875
y = 3893.69970703125
z = 0.0
facing = 4.566225051879883
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 20

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Hvsh'  # Naga Sea Witch
variation = 0
x = -3101.76953125
y = 3888.47216796875
z = 0.0
facing = 5.323254108428955
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 21

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Uear'  # Death Knight
variation = 0
x = -2712.84912109375
y = 3925.30126953125
z = 0.0
facing = 4.537856101989746
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 22

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Uktl'  # Lich
variation = 0
x = -2794.916748046875
y = 3751.35791015625
z = 0.0
facing = 1.3962633609771729
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 23

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Uanb'  # Crypt Lord
variation = 0
x = -2618.40625
y = 3788.04443359375
z = 0.0
facing = 2.349555015563965
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 24

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Usyl'  # Dark Ranger
variation = 0
x = -2235.521728515625
y = 3777.43896484375
z = 0.0
facing = 4.720417499542236
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 25

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Uvar'  # Dreadlord
variation = 0
x = -2108.143310546875
y = 3892.435546875
z = 0.0
facing = 4.6993021965026855
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 26

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'Naka'  # Elder Sage
variation = 0
x = -3219.50634765625
y = 3890.92431640625
z = 0.0
facing = 4.71238899230957
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = -1
mana_points = -1
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 12500
target_acquisition = -1.0
hero_level = 1
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 27

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0

[[units]]

type_id = 'sloc'  # Start Location
variation = 1
x = -4224.0
y = 4288.0
z = 0.0
facing = 4.71238899230957
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
flags = "ENABLED"
player_owner = 1
hit_points = 0
mana_points = 0
random_item_table_id = -1
item_drops = []
goldmine_gold_amount = 0
target_acquisition = 0.0
hero_level = 0
hero_strength = 0
hero_agility = 0
hero_intelligence = 0
inventory_items = []
modified_abilities = []
custom_colour = -1
waygate_destination = -1
entity_id = 28

[units.random_unit_info]

random_type = 'class'
level = 1
item_class = 0