
# Units
UNIT_IRREGULAR = 'hA00'

# Abilities
ABIL_SELECT_TRANSFORM_CAPTAIN = 'AP00'
ABIL_SELECT_TRANSFORM_FOOTMAN = 'AP01'
ABIL_SELECT_TRANSFORM_RIFLEMAN = 'AP02'
ABIL_SELECT_TRANSFORM_BLOOD_ELF_ARCHER = 'AP03'
ABIL_SELECT_TRANSFORM_KNIGHT = 'AP04'
ABIL_SELECT_TRANSFORM_PRIEST = 'AP05'
ABIL_SELECT_TRANSFORM_SORCERESS = 'AP06'
ABIL_SELECT_TRANSFORM_SPELL_BREAKER = 'AP07'
ABIL_SELECT_TRANSFORM_MORTAR_TEAM = 'AP08'

ABIL_EXECUTE_TRANSFORM_CAPTAIN = 'AP0a'
ABIL_EXECUTE_TRANSFORM_FOOTMAN = 'AP0b'
ABIL_EXECUTE_TRANSFORM_RIFLEMAN = 'AP0c'
ABIL_EXECUTE_TRANSFORM_BLOOD_ELF_ARCHER = 'AP0d'
ABIL_EXECUTE_TRANSFORM_KNIGHT = 'AP0e'
ABIL_EXECUTE_TRANSFORM_PRIEST = 'AP0f'
ABIL_EXECUTE_TRANSFORM_SORCERESS = 'AP0g'
ABIL_EXECUTE_TRANSFORM_SPELL_BREAKER = 'AP0h'
ABIL_EXECUTE_TRANSFORM_MORTAR_TEAM = 'AP0i'

# Upgrades
UPGRADE_HAS_CAPTAIN = 'RP00'
UPGRADE_HAS_FOOTMAN = 'RP01'
UPGRADE_HAS_RIFLEMAN = 'RP02'
UPGRADE_HAS_BLOOD_ELF_ARCHER = 'RP03'
UPGRADE_HAS_KNIGHT = 'RP04'
UPGRADE_HAS_PRIEST = 'RP05'
UPGRADE_HAS_SORCERESS = 'RP06'
UPGRADE_HAS_SPELL_BREAKER = 'RP07'
UPGRADE_HAS_MORTAR_TEAM = 'RP08'
