
# Abilities
ABIL_SPELL_BOOK = 'Aspb'  # Abilities/Special/Items

## Human
ABIL_AERIAL_SHACKLES = 'Amls'
ABIL_BARRAGE = 'Aroc'
ABIL_CALL_TO_ARMS_TOWN_HALL = 'Amic'
ABIL_CALL_TO_ARMS_PEASANT = 'Amil'
ABIL_CARGO_HOLD_TANK = 'Sch4'
ABIL_CHAOS = 'Srtt'  # Turns siege engines into AA siege engines
ABIL_CLOUD = 'Aclf'
ABIL_CONTROL_MAGIC = 'Acmg'
ABIL_DEFEND = 'Adef'
ABIL_DISPEL_MAGIC = 'Adis'
ABIL_FEEDBACK_ARCANE_TOWER = 'Afbt'
ABIL_FEEDBACK_SPELL_BREAKER = 'Afbk'
ABIL_FLAK_CANNONS = 'Aflk'
ABIL_FLARE = 'Afla'
ABIL_FLYING_MACHINE_BOMBS = 'Agyb'
ABIL_FRAGMENTATION_SHARDS = 'Afsh'
ABIL_HEAL = 'Ahea'
ABIL_INNER_FIRE = 'Ainf'
ABIL_INVISIBILITY = 'Aivs'
ABIL_MAGIC_DEFENSE = 'Amdf'  # Unused spell breaker ability
ABIL_MAGIC_SENTRY_HUMAN_TOWERS = 'Adts'
ABIL_PHOENIX_FIRE = 'Apxf'
ABIL_PHOENIX_MORPHING_EGG_RELATED = 'Aphx'
ABIL_POLYMORPH = 'Aply'
ABIL_REPAIR_HUMAN = 'Ahrp'
ABIL_REVEAL = 'AHta'
ABIL_SLOW = 'Aslo'
ABIL_SPELL_STEAL = 'Asps'
ABIL_SPHERE = 'Asph'  # ???
ABIL_STORM_HAMMERS = 'Asth'
ABIL_TRUE_SIGHT_FLYING_MACHINE = 'Agyv'

ABIL_AVATAR = 'AHav'
ABIL_BANISH = 'AHbn'
ABIL_BASH = 'AHbh'
ABIL_BLIZZARD = 'AHbz'
ABIL_BRILLIANCE_AURA = 'AHab'
ABIL_DEVOTION_AURA = 'AHad'
ABIL_DIVINE_SHIELD = 'AHds'
ABIL_FLAME_STRIKE = 'AHfs'
ABIL_HOLY_LIGHT = 'AHhb'
ABIL_MASS_TELEPORT = 'AHmt'
ABIL_PHOENIX = 'AHpx'
ABIL_RESURRECTION = 'AHre'
ABIL_SIPHON_MANA = 'AHdr'
ABIL_STORM_BOLT = 'AHtb'
ABIL_SUMMON_WATER_ELEMENTAL = 'AHwe'
ABIL_THUNDER_CLAP = 'AHtc'

## Orc
ABIL_ANCESTRAL_SPIRIT = 'Aast'
ABIL_BATTLE_STATIONS = 'Abtl'
ABIL_BATTLE_STATIONS_CHAOS_ORC_BURROW = 'Sbtl'
ABIL_BERSERK = 'Absk'
ABIL_BERSERKER_UPGRADE = 'Sbsk'
ABIL_BLOODLUST = 'Ablo'
ABIL_BURNING_OIL = 'Abof'
ABIL_CARGO_HOLD_ORC_BURROW = 'Abun'
ABIL_CHAOS_GROM = 'Sca6'
ABIL_CHAOS_GRUNT = 'Sca1'
ABIL_CHAOS_KODO_BEAST = 'Sca4'
ABIL_CHAOS_PEON = 'Sca5'
ABIL_CHAOS_RAIDER = 'Sca2'
ABIL_CHAOS_SHAMAN = 'Sca3'
ABIL_CHAOS_CARGO_HOLD = 'Achl'
ABIL_CORPOREAL_FORM = 'Acpf'
ABIL_DETECTOR_SENTRY_WARD = 'Adt1'
ABIL_DEVOUR = 'Adev'
ABIL_DEVOUR_CARGO = 'Advc'
ABIL_DISENCHANT = 'Adcn'
ABIL_DISENCHANT_OLD = 'Adch'
ABIL_ENSNARE = 'Aens'
ABIL_ENVENOMED_SPEARS = 'Aven'
ABIL_ETHEREAL_FORM = 'Aetf'
ABIL_HEALING_WARD_WITCH_DOCTOR = 'Ahwd'
ABIL_HEALING_WARD_AURA_HEALING_WARD = 'Aor'
ABIL_LIGHTNING_SHIELD = 'Alsh'
ABIL_LIQUID_FIRE = 'Aliq'
ABIL_LOAD_ORC_BURROW = 'Sloa'
ABIL_PACK_MULE = 'Apak'
ABIL_PILLAGE = 'Asal'
ABIL_PULVERIZE = 'Awar'
ABIL_PURGE = 'Apg2'
ABIL_PURGE_OLD = 'Aprg'
ABIL_REINFORCED_BURROWS_UPGRADE = 'Arbr'
ABIL_REPAIR_ORC = 'Arep'
ABIL_SENTRY_WARD = 'Aeye'
ABIL_SPIKED_BARRICADES = 'Aspi'
ABIL_SPIRIT_LINK = 'Aspl'
ABIL_STAND_DOWN = 'Astd'
ABIL_STASIS_TRAP = 'Asta'
ABIL_UNSTABLE_CONCOCTION = 'Auco'
ABIL_WAR_DRUMS = 'Aakb'

ABIL_BIG_BAD_VOODOO = 'AOvd'
ABIL_BLADESTORM = 'AOww'
ABIL_CHAIN_LIGHTNING = 'AOcl'
ABIL_CRITICAL_STRIKE = 'AOcr'
ABIL_EARTHQUAKE = 'AOeq'
ABIL_ENDURANCE_AURA = 'AOae'
ABIL_ENDURANCE_AURA_CAIRNE = 'AOr2'
ABIL_FAR_SIGHT = 'AOfs'
ABIL_FERAL_SPIRIT = 'AOsf'
ABIL_HEALING_WAVE = 'AOhw'
ABIL_HEALING_WAVE_ROKHAN = 'ANhw'
ABIL_HEX = 'AOhx'
ABIL_HEX_ROKHAN = 'ANhx'
ABIL_MIRROR_IMAGE = 'AOmi'
ABIL_REINCARNATION = 'AOre'
ABIL_REINCARNATION_CAIRNE = 'AOr3'
ABIL_SERPENT_WARD = 'AOsw'
ABIL_SERPEND_WARD_ROKHAN = 'Arsw'
ABIL_SHOCKWAVE = 'AOsh'
ABIL_SHOCKWAVE_CAIRNE = 'AOs2'
ABIL_VOODOO_SPIRITS = 'AOIs'
ABIL_WAR_STOMP = 'AOws'
ABIL_WAR_STOMP_CAIRNE = 'AOw2'
ABIL_WIND_WALK = 'AOwk'

## Undead
ABIL_ABSORB_MANA = 'Aabs'
ABIL_ANTI_MAGIC_SHELL = 'Aams'
ABIL_ANTI_MAGIC_SHELL_MAGIC_RESISTANCE = 'Aam2'
ABIL_AURA_OF_BLIGHT = 'Aabr'
ABIL_BLIGHT_GROWTH_LARGE = 'Abgl'
ABIL_BLIGHT_GROWTH_SMALL = 'Abgs'
ABIL_BLIGHTED_GOLD_MINE_ABILITY = 'Abgm'
ABIL_BURROW_CRYPT_FIEND = 'Abur'
ABIL_BURROW_SCARAB_LEVEL_2 = 'Abu2'
ABIL_BURROW_SCARAB_LEVEL_3 = 'Abu3'
ABIL_CANNIBALIZE_ABOMINATION = 'Acn2'
ABIL_CANNIBALIZE_GHOUL = 'Acan'
ABIL_CARGO_HOLD_MEAT_WAGON = 'Sch2'
ABIL_CREATE_CORPSE = 'Agyd'
ABIL_CRIPPLE = 'Acri'
ABIL_CRIPPLE_WARLOCK = 'Scri'
ABIL_CURSE = 'Acrs'
ABIL_DESTROYER_FORME = 'Aave'
ABIL_DEVOUR_MAGIC = 'Advm'
ABIL_DISEASE_CLOUD_ABOMINATION = 'Aap1'
ABIL_DISEASE_CLOUD_MEAT_WAGON = 'Apts'
ABIL_DISEASE_CLOUD_PLAGUE_WARD = 'Aap2'
ABIL_DROP_CORPSE = 'Amed'
ABIL_ESSENCE_OF_BLIGHT = 'Arpl'
ABIL_EXHUME_CORPSES = 'Aexh'
ABIL_FREEZING_BREATH = 'Afrz'
ABIL_FROST_ATTACK_UNUSED = 'Afr2'
ABIL_FROST_ATTACK_NERUBIAN_TOWER = 'Afra'
ABIL_FROST_BREATH = 'Afrb'
ABIL_GATHER_ACOLYTE_GOLD = 'Aaha'
ABIL_GET_CORPSE = 'Amel'
ABIL_GHOST = 'Agho'
ABIL_GHOST_VISIBLE = 'Aeth'
ABIL_HARVEST_GHOUL_LUMBER = 'Ahrl'
ABIL_ORB_OF_ANNIHILATION = 'Afak'
ABIL_POSSESSION = 'Apos'
ABIL_POSSESSION_CHANNELING = 'Aps2'
ABIL_RAISE_DEAD = 'Arai'
ABIL_REPLENISH = 'Arpb'
ABIL_REPLENISH_MANA = 'Amb2'
ABIL_RESTORE = 'Arst'
ABIL_SACRIFICE_ACOLYTE = 'Alam'
ABIL_SACRIFICE_SACRIFICIAL_PIT = 'Asac'
ABIL_SPIDER_ATTACK = 'Aspa'
ABIL_SPIRIT_TOUCH = 'Arpm'
ABIL_STONE_FORM = 'Astn'
ABIL_TRUE_SIGHT_SHADE = 'Atru'
ABIL_UNHOLY_FRENZY = 'Auhf'
ABIL_UNSUMMON_BUILDING = 'Auns'
ABIL_WEB = 'Aweb'

ABIL_ANIMATE_DEAD = 'AUan'
ABIL_CARRION_BEETLES = 'AUcb'
ABIL_CARRION_SWARM = 'AUcs'
ABIL_DARK_RITUAL = 'AUdr'
ABIL_DEATH_AND_DECAY = 'AUdd'
ABIL_DEATH_COIL = 'AUdc'
ABIL_DEATH_PACT = 'AUdp'
ABIL_FROST_ARMOR = 'AUfa'
ABIL_FROST_ARMOR_AUTOCAST = 'AUfu'
ABIL_FROST_NOVA = 'AUfn'
ABIL_IMPALE = 'AUim'
ABIL_INFERNO = 'AUin'
ABIL_LOCUST_SWARM = 'AUls'
ABIL_SLEEP = 'AUsl'
ABIL_UNHOLY_AURA = 'AUau'
ABIL_VAMPIRIC_AURA = 'AUav'

## Night Elf
ABIL_ABOLISH_MAGIC = 'Aadm'
ABIL_BAER_FORM = 'Abrf'
ABIL_CORROSIVE_BREATH = 'Acor'
ABIL_CYCLONE = 'Acyc'
ABIL_DETONATE = 'Adtn'
ABIL_DISMOUNT = 'Adec'
ABIL_EAT_TREE = 'Aeat'
ABIL_ELUNES_GRACE = 'Aegr'
ABIL_ENTANGLE_GOLD_MINE = 'Aent'
ABIL_ENTANGLED_GOLD_MINE_ABILITY = 'Aegm'
ABIL_ETHEREAL = 'Aetl'
ABIL_FAERIE_FIRE = 'Afae'
ABIL_FAERIE_FIRE_MORPH = 'Afa2'
ABIL_GATHER_WISP_GOLD_AND_LUMBER = 'Awha'
ABIL_HARDENED_SKIN = 'Assk'
ABIL_LIGHTNING_ATTACK = 'Alit'
ABIL_LOAD_ENTANGLED_GOAL_MINE = 'Aenc'
ABIL_LOAD_WISP = 'Slo2'
ABIL_MANA_FLARE = 'Amfl'
ABIL_MOON_GLAIVE = 'Amgl'
ABIL_MOON_GLAIVE_NAISHA = 'Amgr'
ABIL_MOUNT_HIPPOGRYPH = 'Aco2'
ABIL_MOUNT_HIPPOGRYPH_OLD = 'Acoa'
ABIL_PHASE_SHIFT = 'Apsh'
ABIL_PICK_UP_ARCHER = 'Ac03'
ABIL_PICK_UP_ARCHER_OLD = 'Acoh'
ABIL_REJUVENATION = 'Arej'
ABIL_RENEW = 'Aren'
ABIL_REPLENISH_MANA_AND_LIFE = 'Ambt'
ABIL_RESISTANT_SKIN = 'Arsk'
ABIL_ROAR = 'Aroa'
ABIL_ROAR_MORPH = 'Ara2'
ABIL_ROOT_ANCIENT_PROTECTOR = 'Aro2'
ABIL_ROOT_ANCIENTS = 'Aro1'
ABIL_SENTINEL = 'Aesn'
ABIL_SENTINEL_NAISHA = 'Aesr'
ABIL_SHADOW_MELD = 'Ashm'
ABIL_SHADOW_MELD_INSTANT = 'Sshm'
ABIL_SLOW_POISON = 'Aspo'
ABIL_SPELL_IMMUNITY = 'Amim'
ABIL_SPHERE_VENGEANCE_LEVEL_1 = 'Asp1'
ABIL_SPHERE_VENGEANCE_LEVEL_2 = 'Asp2'
ABIL_SPHERE_VENGEANCE_LEVEL_3 = 'Asp3'
ABIL_SPHERE_VENGEANCE_LEVEL_4 = 'Asp4'
ABIL_SPHERE_VENGEANCE_LEVEL_5 = 'Asp5'
ABIL_SPHERE_VENGEANCE_LEVEL_6 = 'Asp6'
ABIL_SPIRIT_OF_VENGEANCE = 'Avng'
ABIL_STORM_CROW_FORM = 'Arav'
ABIL_TAUNT = 'Atau'
ABIL_ULTRAVISION = 'Ault'
ABIL_VORPAL_BLADES = 'Aimp'
ABIL_WAR_CLUB = 'Agra'

ABIL_BLINK = 'AEbl'
ABIL_BLINK_NEUTRAL = 'ANbl'
ABIL_ENTANGLING_ROOTS = 'AEer'
ABIL_EVASION = 'AEev'
ABIL_FAN_OF_KNIVES = 'AEfk'
ABIL_FORCE_OF_NATURE = 'AEfn'
ABIL_IMMOLATION = 'AEim'
ABIL_MANA_BURN = 'AEmb'
ABIL_METAMORPHOSIS = 'AEme'
ABIL_SCOUT = 'AEst'
ABIL_SEARING_ARROWS = 'AHfa'
ABIL_SHADOW_STRIKE = 'AEsh'
ABIL_STARFALL = 'AEsf'
ABIL_THORNS_AURA = 'AEah'
ABIL_TRANQUILITY = 'AEtq'
ABIL_TRUESHOT_AURA = 'AEar'
ABIL_VENGEANCE = 'AEsv'

## Neutral Hostile
ABIL_BANISH_NEUTRAL_HOSTILE = 'ACbn'
ABIL_MONSOON_UNIT = 'ACmo'
ABIL_SUMMON_SEA_ELEMENTAL = 'ACwe'
ABIL_ABOLISH_MAGIC_NEUTRAL_HOSTILE = 'ACdm'
ABIL_ABOLISH_MAGIC_NEUTRAL_HOSTILE_2 = 'ACd2'
ABIL_ANIMATE_DEAD_NEUTRAL_HOSTILE = 'ACad'
ABIL_ANTI_MAGIC_SHELL_NEUTRAL_HOSTILE = 'ACam'
ABIL_BASH_NEUTRAL_HOSTILE_1 = 'ACbh'
ABIL_BASH_NEUTRAL_HOSTILE_2 = 'ANbh'
ABIL_BLACK_ARROW_UNIT = 'ACbk'
ABIL_BLIZZARD_NEUTRAL_HOSTILE = 'ACbz'
ABIL_BLOODLUST_NEUTRAL_HOSTILE_1 = 'ACbl'
ABIL_BLOODLUST_NEUTRAL_HOSTILE_2 = 'ACbb'
ABIL_BREATH_OF_FIRE_UNIT = 'ACbc'
ABIL_BREATH_OF_FROST = 'ACbf'
ABIL_BRILLIANCE_AURA_NEUTRAL_HOSTILE = 'ACba'
ABIL_BURROW_NEUTRAL_HOSTILE = 'Abu5'
ABIL_CANNIBALIZE_NEUTRAL_HOSTILE = 'ACcn'
ABIL_CARRION_SWARM_NEUTRAL_HOSTILE = 'ACca'
ABIL_CHAIN_LIGHTNING_NEUTRAL_HOSTILE = 'ACcl'
ABIL_CHARGE_GOLD_AND_LUMBER = 'AAns'
ABIL_CHARM_NEUTRAL_HOSTILE = 'ACch'
ABIL_CLEAVING_ATTACK_NEUTRAL_HOSTILE = 'ACce'
ABIL_COLD_ARROW_NEUTRAL_HOSTILE = 'ACcw'
ABIL_COMMAND_AURA = 'ACac'
ABIL_CRIPPLE_NEUTRAL_HOSTILE = 'ACcr'
ABIL_CRITICAL_STRIKE_NEUTRAL_HOSTILE = 'ACct'
ABIL_CROW_FORM_MEDIVH = 'Amrf'
ABIL_CRUSHING_WAVE = 'ACcv'
ABIL_CURSHING_WAVE_LESSER_2 = 'ACc2'
ABIL_CURSHING_WAVE_LESSER_3 = 'ACc3'
ABIL_CURSE_NEUTRAL_HOSTILE = 'ACcs'
ABIL_CYCLONE_CENARIUS = 'SCc1'
ABIL_CYCLONE_NEUTRAL_HOSTILE = 'ACcy'
ABIL_DEATH_COIL_NEUTRAL_HOSTILE = 'ACdc'
ABIL_DEVOTION_AURA_NEUTRAL_HOSTILE = 'ACav'
ABIL_DEVOUR_NEUTRAL_HOSTILE = 'ACdv'
ABIL_DEVOUR_MAGIC_NEUTRAL_HOSTILE = 'ACde'
ABIL_DISEASE_CLOUD_NEUTRAL_HOSTILE_NO_DAMAGE = 'Aap4'
ABIL_DISEASE_CLOUD_NEUTRAL_HOSTILE = 'Aap3'
ABIL_DISPEL_MAGIC_NEUTRAL_HOSTILE = 'Adsm'
ABIL_DIVINE_SHIELD_NEUTRAL_HOSTILE = 'ACds'
ABIL_ENDURANCE_AURA_NEUTRAL_HOSTILE = 'ACae'
ABIL_ENSNARE_NEUTRAL_HOSTILE = 'ACen'
ABIL_ENTANGLING_ROOTS_NEUTRAL_HOSTILE_1 = 'Aenr'
ABIL_ENTANGLING_ROOTS_NEUTRAL_HOSTILE_2 = 'Aenw'
ABIL_ENVENOMED_SPEARS_NEUTRAL_HOSTILE = 'ACvs'
ABIL_EVASION_NEUTRAL_HOSTILE_100_PERCENT = 'ACes'
ABIL_EVASION_NEUTRAL_HOSTILE = 'ACev'
ABIL_FACTORY = 'ANfy'
ABIL_FAERIE_FIRE_NEUTRAL_HOSTILE = 'ACff'
ABIL_FEEDBACK_NEUTRAL_HOSTILE = 'Afbb'
ABIL_FERAL_SPIRIT_NEUTRAL_HOSTILE_UNIT = 'ACsf'
ABIL_FERAL_SPIRIT_NEUTRAL_HOSTILE_PIG = 'ACs9'
ABIL_FINGER_OF_DEATH_NEUTRAL_HOSTILE = 'Afod'
ABIL_FINGER_OF_PAIN = 'ACfd'
ABIL_FINGER_OF_PAIN_2 = 'ACf3'
ABIL_FIREBOLT_NEUTRAL_HOSTILE_UNIT = 'ACfb'
ABIL_FIREBOLT_WARLOCK = 'Awfb'
ABIL_FORCE_OF_NATURE_NEUTRAL_HOSTILE = 'ACfr'
ABIL_FORKED_LIGHTNING_UNIT = 'ACfl'
ABIL_FRENZY = 'Afzy'
ABIL_FROST_ARMOR_AUTOCAST_NEUTRAL_HOSTILE = 'ACf2'
ABIL_FORST_ARMOR_NEUTRAL_HOSTILE = 'ACfa'
ABIL_FROST_BOLT = 'ACcb'
ABIL_FROST_NOVA_NEUTRAL_HOSTILE = 'ACfn'
ABIL_GATHER_WISP_GOLD_AND_LUMBER_ANCIENT_SPIRITS = 'Awh2'
ABIL_HARVEST_ARCHIMONDES_GHOULS_LUMBER = 'Ahr2'
ABIL_HARVEST_GOBLIN_SHREDDERS_LUMBER = 'Ahr3'
ABIL_HEAL_NEUTRAL_HOSTILE_1 = 'ANhe'
ABIL_HEAL_NEUTRAL_HOSTILE_2 = 'ANh1'
ABIL_HEAL_NEUTRAL_HOSTILE_3 = 'ANh2'
ABIL_HEALING_WARD_NEUTRAL_HOSTILE = 'AChw'
ABIL_HEALING_WAVE_NEUTRAL_HOSTILE = 'AChv'
ABIL_HEX_NEUTRAL_HOSTILE = 'AChx'
ABIL_HOWL_OF_TERROR_UNIT = 'Acht'
ABIL_HURL_BOULDER = 'ACtb'
ABIL_IMMOLATION_NEUTRAL_HOSTILE = 'ACim'
ABIL_IMPALE_NEUTRAL_HOSTILE = 'ACmp'
ABIL_INNER_FIRE_NEUTRAL_HOSTILE = 'ACif'
ABIL_KABOOM_CLOCKWERK_LEVEL_1 = 'Asdg'
ABIL_KABOOM_CLOCKWERK_LEVEL_2 = 'Asd2'
ABIL_KABOOM_CLOCKWERK_LEVEL_3 = 'Asd3'
ABIL_KABOOM_GOBLIN_SAPPER = 'Asds'
ABIL_LIFE_DRAIN_UNIT = 'ACdr'
ABIL_LIFE_REGENERATION_AURA = 'ACnr'
ABIL_LIFE_STEAL_FROSTMOURNE = 'SCva'
ABIL_LIGHTNING_SHIELD_NEUTRAL_HOSTILE = 'ACls'
ABIL_MANA_BURN_NEUTRAL_HOSTILE_1 = 'Ambd'
ABIL_MANA_BURN_NEUTRAL_HOSTILE_2 = 'Amnb'
ABIL_MANA_BURN_NEUTRAL_HOSTILE_3 = 'Ambb'
ABIL_MANA_REGENERATION = 'ANre'
ABIL_MANA_SHIELD_UNIT = 'ACmf'
ABIL_MAUL = 'ANb2'
ABIL_MIND_ROT = 'ANmr'
ABIL_PARASITE_UNIT = 'ACpa'
ABIL_POLYMORPH_NEUTRAL_HOSTILE = 'ACpy'
ABIL_POSSESSION_NEUTRAL_HOSTILE = 'ACps'
ABIL_PULVERIZE_NEUTRAL_HOSTILE = 'ACpv'
ABIL_PURGE_NEUTRAL_HOSTILE = 'ACpu'
ABIL_QUILL_SPRAY = 'ANak'
ABIL_RAIN_OF_FIRE_UNIT_1 = 'ACrg'
ABIL_RAIN_OF_FIRE_UNIT_2 = 'ACrf'
ABIL_RAISE_DEAD_NEUTRAL_HOSTILE = 'ACrd'
ABIL_RAY_OF_DISRUPTION = 'Ache'
ABIL_REINCARNATION_NEUTRAL_HOSTILE_UNIT = 'ACrn'
ABIL_REJUVENATION_FURBOLG = 'ACr2'
ABIL_REJUVENATION_NEUTRAL_HOSTILE = 'ACrj'
ABIL_RESISTANT_SKIN_NEUTRAL_HOSTILE_1 = 'ACrk'
ABIL_RESISTANT_SKIN_NEUTRAL_HOSTILE_2 = 'ACsk'
ABIL_REVEAL = 'Andt'
ABIL_ROAR_NEUTRAL_HOSTILE = 'ACro'
ABIL_ROAR_SKELETAL_ORC_CHAMPION = 'ACr1'
ABIL_SEARING_ARROWS_NEUTRAL_HOSTILE = 'ACsa'
ABIL_SHADOW_MELD_AKAMA = 'Ahid'
ABIL_SHADOW_STRIKE_NEUTRAL_HOSTILE = 'ACss'
ABIL_SHOCKWAVE_NEUTRAL_HOSTILE = 'ACsh'
ABIL_SHOCKWAVE_TRAP = 'ACst'
ABIL_SILENCE_UNIT = 'ACsi'
ABIL_SIPHON_MANA_NEUTRAL_HOSTILE = 'ACsm'
ABIL_SLAM_NEUTRAL_HOSTILE = 'ACtc'
ABIL_SLAM_THUNDER_LIZARD = 'ACt2'
ABIL_SLEEP_NEUTRAL_HOSTILE = 'ACsl'
ABIL_SLEEP_ALWAYS = 'Asla'
ABIL_SLOW_NEUTRAL_HOSTILE = 'ACsw'
ABIL_SPAWN_HYDRA = 'Aspy'
ABIL_SPAWN_HYDRA_HATCHLING = 'Aspt'
ABIL_SPAWN_SKELETON_PROBABLY_BLACK_ARROW = 'Asod'
ABIL_SPAWN_SPIDERLINGS = 'Aspd'
ABIL_SPAWN_TENTACLE = 'ACtn'
ABIL_SPELL_IMMUNITY_ARCHIMONDE = 'ACm2'
ABIL_SPELL_IMMUNITY_DRAGON = 'ACm3'
ABIL_SPELL_IMMUNITY_NEUTRAL_HOSTILE = 'ACmi'
ABIL_SPIKED_SHELL = 'ANth'
ABIL_SPIKED_SHELL_2_2_BUTTOM_POS = 'ANt2'
ABIL_SPY = 'Ansp'
ABIL_SUBMERGE_MYRMIDON = 'Asb1'
ABIL_SUBMERGE_ROYAL_GUARD = 'Asb2'
ABIL_SUBMERGE_SNAP_DRAGON = 'Asb3'
ABIL_TAUNT_NEUTRAL_HOSTILE = 'ANta'
ABIL_THORNS_AURA_NEUTRAL_HOSTILE = 'ACah'
ABIL_TRUESHOT_AURA_NEUTRAL_HOSTILE = 'ACat'
ABIL_UNHOLY_AURA_NEUTRAL_HOSTILE = 'ACua'
ABIL_UNHOLY_FRENZY_NEUTRAL_HOSTILE = 'ACuf'
ABIL_UNHOLY_FRENZY_WARLOCK = 'Suhf'
ABIL_VAMPIRIC_AURA_NEUTRAL_HOSTILE = 'ACvp'
ABIL_WAR_STOMP_NEUTRAL_HOSTILE_1 = 'Awrs'
ABIL_WAR_STOMP_NEUTRAL_HOSTILE_2 = 'Awrh'
ABIL_WAR_STOMP_NEUTRAL_HOSTILE_3 = 'Awrg'
ABIL_WEB_NEUTRAL_HOSTILE = 'ACwb'

ABIL_ACID_BOMB = 'ANab'
ABIL_ATTRIBUTE_BONUS = 'Aamk'
ABIL_BATTLE_ROAR = 'ANbr'
ABIL_BLACK_ARROW = 'ANba'
ABIL_BREATH_OF_FIRE = 'ANbf'
ABIL_BREATH_OF_FIRE_CHEN = 'ANcf'
ABIL_CHANNEL = 'ANcl'
ABIL_CHARM = 'ANch'
ABIL_CHEMICAL_RAGE = 'ANcr'
ABIL_CLEAVING_ATTACK = 'ANca'
ABIL_CLUSTER_ROCKETS = 'ANcs'
ABIL_CLUSTER_ROCKETS_UP1 = 'ANc1'
ABIL_CLUSTER_ROCKETS_UP2 = 'ANc2'
ABIL_CLUSTER_ROCKETS_UP3 = 'ANc3'
ABIL_COLD_ARROWS = 'AHca'
ABIL_DARK_CONVERSION_MALGANIS = 'ANdc'
ABIL_DARK_CONVERSION_MALGANIS_FAST = 'SNdc'
ABIL_DARK_PORTAL_ARCHIMONDE = 'ANdp'
ABIL_DEATH_AND_DECAY_NEUTRAL_HOSTILE = 'SNdd'
ABIL_DEMOLISH = 'ANde'
ABIL_DEMOLISH_UP1 = 'ANd1'
ABIL_DEMOLISH_UP2 = 'ANd2'
ABIL_DEMOLISH_UP3 = 'ANd3'
ABIL_DOOM = 'ANdo'
ABIL_DRUNKEN_BRAWLER = 'ANdb'
ABIL_DRUNKEN_BRAWLER_CHEN = 'Acdb'
ABIL_DRUNKEN_HAZE = 'ANdh'
ABIL_DRUNKEN_HAZE_CHEN = 'Acdh'
ABIL_EARTHQUAKE_NEUTRAL_HOSTILE = 'SNeq'
ABIL_ENGINEERING_UPGRADE = 'ANeg'
ABIL_FERAL_SPIRIT_NEUTRAL_HOSTILE = 'ACs7'
ABIL_FINGER_OF_DEATH_ARCHIMONDE = 'ANfd'
ABIL_FIREBOLT_NEUTRAL_HOSTILE = 'ANfb'
ABIL_FORKED_LIGHTNING = 'ANfl'
ABIL_FROST_ARROWS = 'ANfa'
ABIL_HEALING_SPRAY = 'ANhs'
ABIL_HOWL_OF_TERROR = 'ANht'
ABIL_INCINERATE = 'ANic'
ABIL_INCINERATE_ARROW = 'ANia'
ABIL_INFERNO_NEUTRAL_HOSTILE = 'ANin'
ABIL_INFERNO_TICHONRIUS = 'SNin'
ABIL_LIFE_DRAIN = 'ANdr'
ABIL_MANA_SHIELD = 'ANms'
ABIL_METAMORPHOSIS_EVIL_ILLIDAN = 'AEvi'
ABIL_METAMORPHOSIS_ILLIDAN = 'AEIl'
ABIL_MONSOON = 'ANmo'
ABIL_POCKET_FACTORY = 'ANsy'
ABIL_POCKET_FACTORY_UP1 = 'ANs1'
ABIL_POCKET_FACTORY_UP2 = 'ANs2'
ABIL_POCKET_FACTORY_UP3 = 'ANs3'
ABIL_POISON_ARROWS = 'AEpa'
ABIL_RAIN_OF_CHAOS_ARCHIMONDE = 'ANrc'
ABIL_RAIN_OF_CHAOS_BALNAZZAR = 'ANr3'
ABIL_RAIN_OF_FIRE = 'ANrf'
ABIL_REINCARNATION_NEUTRAL_HOSTILE = 'ANr2'
ABIL_REINCARNATION_MANNOROTH = 'ANrn'
ABIL_ROBO_GOBLIN = 'ANrg'
ABIL_ROBO_GOBLIN_UP1 = 'ANg1'
ABIL_ROBO_GOBLIN_UP2 = 'ANg2'
ABIL_ROBO_GOBLIN_UP3 = 'ANg3'
ABIL_SILENCE = 'ANsi'
ABIL_SOUL_BURN = 'ANso'
ABIL_SOUL_PRESERVATION_MALGANIS = 'ANsl'
ABIL_SPIRIT_BEAST = 'ACs8'
ABIL_STAMPEDE = 'ANst'
ABIL_STAMPEDE_REXXAR = 'Arsp'
ABIL_STARFALL_MORE_POWERFUL = 'AEsb'
ABIL_STORM_BOLT_NEUTRAL_HOSTILE = 'ANsb'
ABIL_STORM_EARTH_AND_FIRE = 'ANef'
ABIL_STORM_EARTH_AND_FIRE_CHEN = 'Acef'
ABIL_SUMMON_BEAR = 'ANsg'
ABIL_SUMMON_HAWK = 'ANsw'
ABIL_SUMMON_LAVA_SPAWN = 'ANlm'
ABIL_SUMMON_MISHA_REXXAR = 'Arsg'
ABIL_SUMMON_PRAWNS = 'Aslp'
ABIL_SUMMON_QUILBEAST = 'ANsq'
ABIL_SUMMON_QUILBEAST_REXXAR = 'Arsq'
ABIL_TORNADO = 'ANto'
ABIL_TRANSMUTE = 'ANtm'
ABIL_VOLCANO = 'ANvc'
ABIL_WATERY_MINION = 'ANwm'
ABIL_WIND_WALK_NEUTRAL_HOSTILE = 'ANwk'

## Neutral Passive
ABOL_ABOLISH_MAGIC_NEUTRAL = 'Andm'
ABIL_BUILDING_DAMAGE_AURA_TORNADO = 'Atdg'
ABIL_CYCLONE_NEUTRAL = 'Acny'
ABIL_ENSNARE_NEUTRAL = 'ANen'
ABIL_FROST_ARMOR_NEUTRAL = 'ACfu'
ABIL_HARDENED_SKIN_NEUTRAL = 'Ansk'
ABIL_PARASITE = 'ANpa'
ABIL_SLOW_AURA_TORNADO = 'Aasl'
ABIL_SUMMONING_RITUAL = 'Ahnl'
ABIL_TORNADO_SPIN = 'Atsp'
ABIL_TORNADO_WANDER = 'Atwa'

## Special
ABIL_AOE_DAMAGE_ON_DEATH_BIG_MINE = 'Amnz'
ABIL_AOE_DAMAGE_ON_DEATH_GOBLIN_MINE = 'Amnx'
ABIL_AOE_DAMAGE_ON_DEATH_SAPPER = 'Adda'
ABIL_BLIGHT_DISPEL_LARGE = 'Abdl'
ABIL_BLIGHT_DISPEL_SMALL = 'Abds'
ABIL_BURROW_DETECTION_FLIERS = 'Abdt'
ABIL_CARGO_HOLD_GOBLIN_ZEPPELIN = 'Sch3'
ABIL_CARGO_HOLD_SHIP = 'Sch5'
ABIL_CARGO_HOLD_DEATH_NEUTRAL_HOSTILE = 'Achd'
ABIL_GOLD_MINE = 'Agld'
ABIL_HARVEST_GOLD_AND_LUMBER = 'Ahar'
ABIL_HARVEST_NEUTRAL = 'ANha'
ABIL_INVENTORY_HERO = 'AInv'
ABIL_INVULNERABLE_NEUTRAL = 'Avul'
ABIL_LOAD_GOBLIN_ZEPPELIN = 'Aloa'
ABIL_LOAD_SHIP = 'Slo3'
ABIL_MINE_EXPLODING_GOBLIN_LAND_MINE = 'Amin'
ABIL_PERMANENT_IMMOLATION_NEUTRAL_HOSTILE_1 = 'ANpi'
ABIL_PERMANENT_IMMOLATION_NEUTRAL_HOSTILE_2 = 'Apig'
ABIL_PERMANENT_INVISIBILITY = 'Apiv'
ABIL_PHOENIX_FIRE_FLYER = 'Apmf'
ABIL_POISON_STING = 'Apoi'
ABIL_RALLY = 'Aral'
ABIL_RETURN_GOLD = 'Argd'
ABIL_RETURN_GOLD_AND_LUMBER = 'Argl'
ABIL_RETURN_LUMBER = 'Arlm'
ABIL_REVENGE = 'Arng'
ABIL_REVIVE_HERO = 'Arev'
ABIL_REVIVE_HERO_INSTANTLY = 'Aawa'
ABIL_SELECT_HERO = 'Aneu'
ABIL_SELECT_UNIT = 'Ane2'
ABIL_SELL_ITEMS = 'Asid'
ABIL_SELL_UNITS = 'Asud'
ABIL_SHOP_PURCHASE_ITEM = 'Apit'
ABIL_SHOP_SHARING = 'Aall'
ABIL_TRUE_SIGHT_NEUTRAL_1 = 'Adtg'
ABIL_TRUE_SIGHT_NEUTRAL_2 = 'ANtr'
ABIL_UNIT_INVENTORY_HUMAN = 'Aihn'
ABIL_UNIT_INVENTORY_NIGHT_ELF = 'Aien'
ABIL_UNIT_INVENTORY_ORC = 'Aion'
ABIL_UNIT_INVENTORY_UNDEAD = 'Aiun'
ABIL_UNLOAD_AIR_TRANSPORTS = 'Adro'
ABIL_UNLOAD_SEA_TRANSPORTS = 'Sdro'
ABIL_UNLOAD_INSTANT_ENTANGLED_MINE = 'Wdri'
ABIL_WANDER_NEUTRAL = 'Wwan'
ABIL_WAYGATE_ABILITY = 'Awrp'

ABIL_AVATAR_NEUTRAL = 'ANav'
ABIL_SHOCKWAVE_NEUTRAL = 'ANsh'

ABIL_ITEM_BASH = 'AIbx'
ABIL_ITEM_BERSERK = 'AIxk'
ABIL_ITEM_BLIGHT_PLACEMENT = 'Ablp'
ABIL_ITEM_BLINK = 'AIbk'
ABIL_ITEM_BRILLIANCE_AURA = 'AIba'
ABIL_ITEM_TINY_ALTAR_OF_KINGS = 'AIbh'
ABIL_ITEM_TINY_BARRACKS = 'AIbs'
ABIL_ITEM_TINY_CASTLE = 'AIbl'
ABIL_ITEM_TINY_FARM = 'AIbf'
ABIL_ITEM_TINY_GRAET_HALL = 'AIbg'
ABIL_ITEM_TINY_LUMBER_MILL = 'AIbr'
ABIL_ITEM_TINY_SCOUT_TOWER = 'AIbt'
ABIL_ITEM_BUNDLE_OF_LUMBER = 'AIlu'
ABIL_ITEM_CHAIN_LIGHTNING = 'AIcl'
ABIL_ITEM_CHANGE_TIME_OF_DAY = 'AIct'
ABIL_ITEM_CHEST_OF_GOLD = 'AIgo'
ABIL_ITEM_CLARITY_POTION = 'AIpr'
ABIL_ITEM_CLOUD_OF_FOG = 'AIfg'
ABIL_ITEM_COMMAND_AURA = 'AIcd'
ABIL_ITEM_CONTROL_MAGIC = 'AIcm'
ABIL_ITEM_CRITICAL_STRIKE = 'AIcs'
ABIL_ITEM_CYCLONE = 'AIcy'
ABIL_ITEM_DARK_SUMMONING = 'AUds'
ABIL_ITEM_DEATH_PACT = 'AIdp'
ABIL_ITEM_DEFEND = 'AIdd'
ABIL_ITEM_DEVOTION_AURA = 'AIad'
ABIL_ITEM_DUST_OF_APPEARANCE = 'AItb'
ABIL_ITEM_ENDURANCE_AURA = 'AIae'
ABIL_ITEM_EVASION = 'AIev'
ABIL_ITEM_FINGER_OF_DEATH = 'AIfz'
ABIL_ITEM_FLARE_GUN = 'AIfa'
ABIL_ITEM_GENERIC_REJUV_EFFECT_1 = 'AIp1'
ABIL_ITEM_GENERIC_REJUV_EFFECT_2 = 'AIp2'
ABIL_ITEM_GENERIC_REJUV_EFFECT_3 = 'AIp3'
ABIL_ITEM_GENERIC_REJUV_EFFECT_4 = 'AIp4'
ABIL_ITEM_GENERIC_REJUV_EFFECT_5 = 'AIp5'
ABIL_ITEM_GENERIC_REJUV_EFFECT_6 = 'AIp6'
ABIL_ITEM_GLYPH_OF_FORTIFICATION = 'AIgf'
ABIL_ITEM_GLYPH_OF_ULTRAVISION = 'AIgu'
ABIL_ITEM_GREATER_RUNE_OF_RESURRECTION = 'APrr'
ABIL_ITEM_HEALING_SALVE = 'AIrl'
ABIL_ITEM_HEALING_WARD = 'AIhw'
ABIL_ITEM_HOLY_LIGHT = 'AIhl'
ABIL_ITEM_INFERNO = 'AIin'
ABIL_ITEM_AGILITY_GAIN = 'AIam'
ABIL_ITEM_AGILITY_GAIN_2 = 'AIgm'
ABIL_ITEM_ANTI_MAGIC_SHELL = 'AIxs'
ABIL_ITEM_AREA_DETECTION = 'AIta'
ABIL_ITEM_AREA_HEAL_MANA_REGAIN = 'AIra'
ABIL_ITEM_AREA_HEALING = 'AIha'
ABIL_ITEM_AREA_MANA_REGAIN = 'AImr'
ABIL_ITEM_AREA_TREE_WALL_DAMAGE = 'AIdm'
ABIL_ITEM_ARMOUR_BONUS_1 = 'AId1'
ABIL_ITEM_ARMOUR_BONUS_10 = 'AId0'
ABIL_ITEM_ARMOUR_BONUS_2 = 'AId2'
ABIL_ITEM_ARMOUR_BONUS_3 = 'AId3'
ABIL_ITEM_ARMOUR_BONUS_4 = 'AId4'
ABIL_ITEM_ARMOUR_BONUS_5 = 'AId5'
ABIL_ITEM_ARMOUR_BONUS_6 = 'AId6'
ABIL_ITEM_ARMOUR_BONUS_7 = 'AId7'
ABIL_ITEM_ARMOUR_BONUS_8 = 'AId8'
ABIL_ITEM_ATTACK_BLACK_ARROW_BONUS = 'AIdf'
ABIL_ITEM_ATTACK_CORRUPTION_BONUS = 'AIcb'
ABIL_ITEM_ATTACK_FIRE_BONUS = 'AIfb'
ABIL_ITEM_ATTACK_FIRE_BONUS_GULDAN = 'AIgd'
ABIL_ITEM_ATTACK_FROST_BONUS = 'AIob'
ABIL_ITEM_ATTACK_LIGHTNING_BONUS = 'AIlb'
ABIL_ITEM_ATTACK_POISON_BONUS = 'AIpb'
ABIL_ITEM_ATTACK_SPEED_BONUS_GLOVES_OF_HASTE = 'AIsx'
ABIL_ITEM_ATTACK_SPEED_BONUS_GREATER = 'AIs2'
ABIL_ITEM_CAPTURE_THE_FLAG = 'AIfl'
ABIL_ITEM_CAPTURE_THE_FLAG_HUMAN = 'AIfm'
ABIL_ITEM_CAPTURE_THE_FLAG_NIGHT_ELF = 'AIfn'
ABIL_ITEM_CAPTURE_THE_FLAG_ORC = 'AIfo'
ABIL_ITEM_CAPTURE_THE_FLAG_UNDEAD = 'AIfe'
ABIL_ITEM_CHAIN_DISPEL = 'AIdc'
ABIL_ITEM_COMMAND = 'AIco'
ABIL_ITEM_DAMAGE_BONUS_1 = 'AItg'
ABIL_ITEM_DAMAGE_BONUS_2 = 'AIth'
ABIL_ITEM_DAMAGE_BONUS_3 = 'AIat'
ABIL_ITEM_DAMAGE_BONUS_4 = 'AIti'
ABIL_ITEM_DAMAGE_BONUS_5 = 'AItj'
ABIL_ITEM_DAMAGE_BONUS_6 = 'AIt6'
ABIL_ITEM_DAMAGE_BONUS_7 = 'AItk'
ABIL_ITEM_DAMAGE_BONUS_8 = 'AItl'
ABIL_ITEM_DAMAGE_BONUS_9 = 'AIt9'
ABIL_ITEM_DAMAGE_BONUS_10 = 'AItn'
ABIL_ITEM_DAMAGE_BONUS_12 = 'AItc'
ABIL_ITEM_DAMAGE_BONUS_15 = 'AItf'
ABIL_ITEM_DAMAGE_BONUS_20 = 'AItx'
ABIL_ITEM_DISPEL = 'AIdi'
ABIL_ITEM_DISPEL_WITH_COOLDOWN = 'AIds'
ABIL_ITEM_DIVINE_SHIELD = 'AIdv'
ABIL_ITEM_DOOM_GUARD_SUMMON = 'AIfu'
ABIL_ITEM_EXPERIENCE_GAIN = 'AIem'
ABIL_ITEM_EXPERIENCE_GAIN_GREATER = 'AIe2'
ABIL_ITEM_FELHOUND_SUMMON = 'AIfh'
ABIL_ITEM_FREEZE_DAMAGE_BONUS = 'AIzb'
ABIL_ITEM_FURBOLG_SUMMON = 'AIff'
ABIL_ITEM_HEAL_MANA_REGAIN = 'AIre'
ABIL_ITEM_HEALING_GRATER = 'AIh2'
ABIL_ITEM_HEALING_LESSER = 'AIh1'
ABIL_ITEM_HEALING_LEAST = 'AIhx'
ABIL_ITEM_HERO_STAT_BONUS_RING_OF_THE_ARCHMAGI = 'AIx3'
ABIL_ITEM_HERO_STAT_BONUS = 'AIx4'
ABIL_ITEM_HERO_STAT_BONUS_1_AGILITY = 'AIa1'
ABIL_ITEM_HERO_STAT_BONUS_1_ALL_STATS = 'AIx1'
ABIL_ITEM_HERO_STAT_BONUS_1_INTELLIGENCE = 'AIi1'
ABIL_ITEM_HERO_STAT_BONUS_1_STRENGTH = 'AIs1'
ABIL_ITEM_HERO_STAT_BONUS_10_AGILITY = 'AIaz'
ABIL_ITEM_HERO_STAT_BONUS_2_ALL_STATS = 'AIx2'
ABIL_ITEM_HERO_STAT_BONUS_3_AGILITY = 'AIa3'
ABIL_ITEM_HERO_STAT_BONUS_3_INTELLIGENCE = 'AIi3'
ABIL_ITEM_HERO_STAT_BONUS_3_STRENGTH = 'AIs3'
ABIL_ITEM_HERO_STAT_BONUS_4_AGILITY = 'AIa4'
ABIL_ITEM_HERO_STAT_BONUS_4_INTELLIGENCE = 'AIi4'
ABIL_ITEM_HERO_STAT_BONUS_4_STRENGTH = 'AIs4'
ABIL_ITEM_HERO_STAT_BONUS_5_ALL_STATS = 'AIx5'
ABIL_ITEM_HERO_STAT_BONUS_6_AGILITY = 'AIa6'
ABIL_ITEM_HERO_STAT_BONUS_6_INTELLIGENCE = 'AIi6'
ABIL_ITEM_HERO_STAT_BONUS_6_STRENGTH = 'AIs6'
ABIL_ITEM_ICE_REVENANT_SUMMON = 'AIir'
ABIL_ITEM_ILLUSIONS = 'AIil'
ABIL_ITEM_IMMOLATION = 'AIcf'
ABIL_ITEM_INT_AGI_STR_GAIN = 'AIxm'
ABIL_ITEM_INTELLIGENCE_GAIN = 'AIim'
ABIL_ITEM_INTELLIGENCE_GAIN_2 = 'AItm'
ABIL_ITEM_LEVEL_GAIN = 'AIlm'
ABIL_ITEM_LIFE_BONUS_GREATER = 'AIl2'
ABIL_ITEM_LIFE_BONUS_LEAST = 'AIlf'
ABIL_ITEM_LIFE_BONUS_LESSER = 'AIl1'
ABIL_ITEM_LIFE_REGENERATION = 'Arel'
ABIL_ITEM_LIFE_REGENERATION_LESSER = 'Arll'
ABIL_ITEM_LIFE_STEAL = 'AIva'
ABIL_ITEM_MANA_BONUS_100 = 'AImz'
ABIL_ITEM_MANA_BONUS_200 = 'AI2m'
ABIL_ITEM_MANA_BONUS_75 = 'AImv'
ABIL_ITEM_MANA_BONUS_GREATER = 'AIbm'
ABIL_ITEM_MANA_BONUS_LEAST = 'AImb'
ABIL_ITEM_MANA_REGAIN_GREATER = 'AIm2'
ABIL_ITEM_MANA_REGAIN_LESSER = 'AIm1'
ABIL_ITEM_MANA_REGENERATION = 'AIrm'
ABIL_ITEM_MANA_REGENERATION_LESSER = 'AIrn'
ABIL_ITEM_MOVE_SPEED_BONUS = 'AIms'
ABIL_ITEM_ORCISH_BATTLE_STANDARD = 'AIfx'
ABIL_ITEM_PERMANENT_DAMAGE_GAIN = 'AIaa'
ABIL_ITEM_PERMANENT_LIFE_GAIN_50 = 'AImh'
ABIL_ITEM_PERMANENT_LIFE_GAIN_LESSER = 'AIpx'
ABIL_ITEM_PLACE_GOBLIN_LAND_MINE = 'AIpm'
ABIL_ITEM_PURGE_1 = 'AIlp'
ABIL_ITEM_PURGE_2 = 'AIpg'
ABIL_ITEM_PURGE_3 = 'AIps'
ABIL_ITEM_RECALL = 'AIrt'
ABIL_ITEM_RED_DRAKE_SUMMON = 'AIfd'
ABIL_ITEM_REINCARNATION = 'AIrc'
ABIL_ITEM_RESURRECTION = 'AIrs'
ABIL_ITEM_RESURRECTION_COOLDOWN = 'AIrx'
ABIL_ITEM_REVEAL_ENTIRE_MAP = 'AIrv'
ABIL_ITEM_ROCK_GOLEM_SUMMON = 'AIfr'
ABIL_ITEM_SIGHT_RANGE_BONUS = 'AIsi'
ABIL_ITEM_SILENCE = 'AIse'
ABIL_ITEM_SKELETON_SUMMON = 'AIfs'
ABIL_ITEM_SOUL_POSSESSION = 'Asou'
ABIL_ITEM_SOUL_THEFT = 'AIso'
ABIL_ITEM_STRENGTH_GAIN = 'AIsm'
ABIL_ITEM_STRENGTH_GAIN_2 = 'AInm'
ABIL_ITEM_TEMPORARY_AREA_ARMOUR_BONUS = 'AIda'
ABIL_ITEM_TEMPORARY_AREA_ARMOUR_BONUS_WITH_LIFE_AND_MANA_HEALING = 'AIdb'
ABIL_ITEM_TEMPORARY_INVISIBILITY_GREATER = 'AIv2'
ABIL_ITEM_TEMPORARY_INVISIBILITY_LESSER = 'AIv1'
ABIL_ITEM_TEMPORARY_INVULNERABILITY = 'AIvu'
ABIL_ITEM_TEMPORARY_INVULNERABILITY_LESSER = 'AIvl'
ABIL_ITEM_TEMPORARY_SPEED_BONUS = 'AIsp'
ABIL_ITEM_TOWN_PORTAL = 'AItp'
ABIL_ITEM_URSA_WARRIOR_SUMMON = 'AIuw'
ABIL_ITEM_WEB = 'AIwb'
ABIL_ITEM_LEAST_HEALING_SLOW_COOLDOWN = 'AIh3'
ABIL_ITEM_LESSER_CLARITY_POTION = 'AIpl'
ABIL_ITEM_LESSER_RUNE_RESURRECTION = 'APrl'
ABIL_ITEM_LIGHTNING_SHIELD = 'AIls'
ABIL_ITEM_MECHANICAL_CRITTER = 'Amec'
ABIL_ITEM_MELEE_COLD_DAMAGE_BONUS = 'AIft'
ABIL_ITEM_MELEE_FIRE_DAMAGE_BONUS = 'AIfw'
ABIL_ITEM_MELEE_LIGHTNING_DAMAGE_BONUS = 'AIlx'
ABIL_ITEM_MONSTER_LURE = 'AImo'
ABIL_ITEM_ORB_OF_DARKNESS = 'ANbs'
ABIL_ITEM_ORB_OF_LIGHTNING_NEW = 'AIll'
ABIL_ITEM_ORB_OF_SLOW = 'AIsb'
ABIL_ITEM_PENGUIN_SQUEAK = 'AIpz'
ABIL_ITEM_POISON_STING_ORB_OF_VENOM = 'Apo2'
ABIL_ITEM_POWERUP_AREA_HEALING = 'APh2'
ABIL_ITEM_POWERUP_AREA_HEALING_GREATER = 'APh3'
ABIL_ITEM_POWERUP_AREA_HEALING_LESSER = 'APh1'
ABIL_ITEM_POWERUP_DISPEL = 'APdi'
ABIL_ITEM_RAISE_DEAD = 'AIrd'
ABIL_ITEM_RANDOM = 'AIri'
ABIL_ITEM_REANIMATION_SPECIAL_CAMPAIGN_ITEM = 'AInd'
ABIL_ITEM_REBIRTH = 'AIrb'
ABIL_ITEM_REGENERATION_AURA = 'AIgx'
ABIL_ITEM_ROAR = 'AIrr'
ABIL_ITEM_RUNE_AREA_HEAL_MANA_REGAIN = 'APra'
ABIL_ITEM_RUNE_AREA_MANA_REGAIN = 'APmr'
ABIL_ITEM_RUNE_AREA_MANA_REGAIN_GREATER = 'APmg'
ABIL_ITEM_RUNE_OF_SPEED = 'APsa'
ABIL_ITEM_RUNE_OF_THE_WATCHER = 'APwt'
ABIL_ITEM_SCROLL_OF_HASTE = 'AIsa'
ABIL_ITEM_SCROLL_OF_REGENERATION = 'AIsl'
ABIL_ITEM_SENTRY_WARD = 'AIsw'
ABIL_ITEM_SHADOW_ORB_ABILITY = 'AIdn'
ABIL_ITEM_SLOW_ORB_VERSION = 'AIos'
ABIL_ITEM_SLOW_POISON = 'AIsz'
ABIL_ITEM_SPELL_BOOK = 'Aspb'
ABIL_ITEM_SPELL_DAMAGE_REDUCTION = 'AIsr'
ABIL_ITEM_SPELL_IMMUNITY = 'AImx'
ABIL_ITEM_SPELL_SHIELD_AMULET = 'ANss'
ABIL_ITEM_SPELL_SHIELD_RUNE = 'ANse'
ABIL_ITEM_SPIRIT_LINK_AREA = 'Aspp'
ABIL_ITEM_STAFF_OF_SANCTUARY = 'ANsa'
ABIL_ITEM_STAFF_OF_TELEPORTATION = 'AImt'
ABIL_ITEM_STEAL_MANA = 'Aste'
ABIL_ITEM_SUMMON_HEADHUNTER = 'AIsh'
ABIL_ITEM_TOME_OF_RETRAINING = 'Aret'
ABIL_ITEM_TRUESHOT_AURA = 'AIar'
ABIL_ITEM_ULTRAVISION = 'AIuv'
ABIL_ITEM_UNHOLY_AURA = 'AIau'
ABIL_ITEM_UNHOLY_FRENZY = 'AIuf'
ABIL_ITEM_VAMPIRIC_AURA = 'AIav'
ABIL_ITEM_VAMPIRIC_POTION = 'AIpv'
ABIL_ITEM_WAND_OF_SHADOWSIGHT = 'Ashs'
ABIL_ITEM_WATERY_MINION = 'AIwm'

# Buffs + Effects
## Human
BUFF_AVATAR = 'BHav'
BUFF_BANISH = 'BHbn'
BUFF_BLIZZARD = 'BHbd'
BUFF_BLIZZARD_CASTER = 'BHbz'
BUFF_BRILLIANCE_AURA = 'BHab'
BUFF_DEVOTION_AURA = 'BHad'
BUFF_DIVINE_SHIELD = 'BHds'
BUFF_DRAIN_LIFE_AND_MANA_CASTER = 'Bdcb'
BUFF_DRAIN_LIFE_AND_MANA_TARGET = 'Bdtb'
BUFF_DRAIN_LIFE_CASTER = 'Bdcl'
BUFF_DRAIN_LIFE_TARGET = 'Bdtl'
BUFF_DRAIN_MANA_CASTER = 'Bdcm'
BUFF_DRAIN_MANA_TARGET = 'Bdtm'
BUFF_FLAME_STRIKE = 'BHfs'
BUFF_THUNDER_CLAP = 'BHtc'
BUFF_WATER_ELEMENTAL = 'BHwe'
BUFF_AERIAL_SHACKLES = 'Bmlt'
BUFF_AERIAL_SHACKLES_CASTER = 'Bmlc'
BUFF_CLOUD = 'Bclf'
BUFF_CONTROL_MAGIC = 'Bcmg'
BUFF_HEAL = 'Bhea'
BUFF_INNER_FIRE = 'Binf'
BUFF_INVISIBILITY = 'Binv'
BUFF_INVISIBILITY_EXTRA = 'Bivs'
BUFF_MILITIA = 'Bmil'
BUFF_PHOENIX = 'Bphx'
BUFF_PHOENIX_FIRE = 'Bpxf'
BUFF_POLYMORPH = 'Bply'
BUFF_SLOW = 'Bslo'

EFFECT_BLIZZARD = 'XHbz'
EFFECT_FLAME_STRIKE = 'XHfs'
EFFECT_BUILDING_DAMAGE_HUMAN_LARGE = 'Xfhl'
EFFECT_BUILDING_DAMAGE_HUMAN_MEDIUM = 'Xfhm'
EFFECT_BUILDING_DAMAGE_HUMAN_SMALL = 'Xfhs'
EFFECT_CLOUD = 'Xclf'
EFFECT_FLARE = 'Xfla'

## Orc
BUFF_BIG_BAD_VOODOO = 'BOvd'
BUFF_BIG_BAD_VOODOO_CASTER = 'BOvc'
BUFF_BLADESTORM_CASTER = 'BOww'
BUFF_COMMAND_AURA = 'BOac'
BUFF_EARTHQUAKE = 'BOeq'
BUFF_EARTHQUAKE_CASTER = 'BOea'
BUFF_ENDURANCE_AURA = 'BOae'
BUFF_FERAL_SPIRIT = 'BOsf'
BUFF_HEX = 'BOhx'
MIRROR_IMAGE = 'BOmi'
BUFF_SHOCKWAVE_CASTER = 'BOsh'
BUFF_WARD = 'BOwd'
BUFF_WIND_WALK = 'BOwk'
BUFF_BERSERK = 'Bbsk'
BUFF_BLOODLUST = 'Bblo'
BUFF_BURNING_OIL = 'Bbof'
BUFF_DEVOUR = 'Bdvv'
BUFF_DEVOUR_CASTER = 'Bdig'
BUFF_ENSNARE_AIR = 'Bena'
BUFF_ENSNARE_GENERAL = 'Bens'
BUFF_ENSNARE_GROUND = 'Beng'
BUFF_HEALING_WARD = 'Bhwd'
BUFF_HEALING_WARD_AURA = 'Boar'
BUFF_LIGHTNING_SHIELD = 'Blsh'
BUFF_LIGHTNING_SHIELD_CASTER = 'Blsa'
BUFF_LIQUID_FIRE = 'Bliq'
BUFF_MANA_REGENERATION_AURA = 'Barm'
BUFF_PURGE = 'Bprg'
BUFF_SENTRY_WARD = 'Beye'
BUFF_SPIRIT_LINK = 'Bspl'
BUFF_STASIS_TRAP = 'Bstt'
BUFF_WAR_DRUMS = 'Bakb'

EFFECT_EARTHQUAKE = 'XOeq'
EFFECT_REINCARNATION = 'XOre'
EFFECT_BUILDING_DAMAGE_ORC_LARGE = 'Xfol'
EFFECT_BUILDING_DAMAGE_ORC_MEDIUM = 'Xfom'
EFFECT_BUILDING_DAMAGE_ORC_SMALL = 'Xfos'
EFFECT_BURNING_OIL = 'Xbof'

## Undead
BUFF_ANIMATE_DEAD = 'AUan'
BUFF_ANIMATE_DEAD_EXTRA = 'AUad'
BUFF_CARRION_BEETLES = 'BUcb'
BUFF_CARRION_SWARM_CASTER = 'BUcs'
BUFF_DEATH_AND_DECAY = 'BUdd'
BUFF_FROST_ARMOUR = 'BUfa'
BUFF_IMPALE = 'BUim'
BUFF_SLEEP = 'BUsl'
BUFF_SLEEP_PAUSE = 'BUsp'
BUFF_SLEEP_STUN = 'BUst'
BUFF_SPIKED_CARAPACE = 'BUts'
BUFF_UNHOLY_AURA = 'BUau'
BUFF_VAMPIRIC_AURA = 'BUav'
BUFF_ANTI_MAGIC_SHELL = 'Bams'
BUFF_ANTI_MAGIC_SHELL_EXTRA = 'Bam2'
BUFF_AURA_OF_BLIGHT = 'Babr'
BUFF_CRIPPLE = 'Bcri'
BUFF_CURSE = 'Bcrs'
BUFF_DISEASE = 'Bapl'
BUFF_DISEASE_CLOUD = 'Bplg'
BUFF_ESSENCE_OF_BLIGHT = 'Brpl'
BUFF_FREEZING_BREATH = 'Bfrz'
BUFF_POSSESSION = 'Bpos'
BUFF_POSSESSION_CASTER = 'Bpoc'
BUFF_REPLENISH = 'Brpb'
BUFF_SKELETAL_MINION = 'Brai'
BUFF_SPIDERLING = 'Bspa'
BUFF_SPIRIT_TOUCH = 'Brpm'
BUFF_UNHOLY_FRENZY = 'Buhf'
BUFF_UNSUMMON = 'Buns'
BUFF_WEB_AIR = 'Bwea'
BUFF_WEB_GROUND = 'Bweb'

EFFECT_DEATH_AND_DECAY = 'Xudd'
EFFECT_BUILDING_DAMAGE_UNDEAD_LARGE = 'Xful'
EFFECT_BUILDING_DAMAGE_UNDEAD_MEDIUM = 'Xfum'
EFFECT_BUILDING_DAMAGE_UNDEAD_SMALL = 'Xfus'

## Night Elf

## Special

# Upgrades
## Human
UPGRADE_ANIMAL_WAR_TRAINING = 'Rhan'
UPGRADE_BACKPACK_HUMAN = 'Rhpm'
UPGRADE_BARRAGE = 'Rhrt'
UPGRADE_BLACK_GUNPOWDER = 'Rhra'
UPGRADE_CLOUD = 'Rhcd'
UPGRADE_CONTROL_MAGIC = 'Rhss'
UPGRADE_DEFEND = 'Rhde'
UPGRADE_FLAK_CANNONS = 'Rhfc'
UPGRADE_FLARE = 'Rhfl'
UPGRADE_FLYING_MACHINE_BOMBS = 'Rhgb'
UPGRADE_FRAGMENTATION_SHARDS = 'Rhfs'
UPGRADE_IMPROVED_LUMBER_HARVESTING = 'Rhlh'
UPGRADE_IMPROVED_MASONRY = 'Rhac'
UPGRADE_IRON_FORGED_SWORDS = 'Rhme'
UPGRADE_IRON_PLATING = 'Rhar'
UPGRADE_LONG_RIFLES = 'Rhri'
UPGRADE_MAGIC_SENTRY = 'Rhse'
UPGRADE_PRIEST_ADEPT_TRAINING = 'Rhpt'
UPGRADE_SORCERESS_ADEPT_TRAINING = 'Rhst'
UPGRADE_STORM_HAMMERS = 'Rhhb'
UPGRADE_STUDDED_LEATHER_ARMOR = 'Rhla'

## Orc
UPGRADE_BACKPACK_ORC = 'Ropm'
UPGRADE_BERSERKER_STRENGTH = 'Robs'
UPGRADE_BERSERKER_UPGRADE = 'Robk'
UPGRADE_BURNING_OIL = 'Robf'
UPGRADE_ENSNARE = 'Roen'
UPGRADE_ENVENOMED_SPEARS = 'Rovs'
UPGRADE_LIQUID_FIRE = 'Rolf'
UPGRADE_PILLAGE = 'Ropg'
UPGRADE_PULVERIZE = 'Rows'
UPGRADE_REINFORCED_DEFENSES = 'Rorb'
UPGRADE_SHAMAN_ADEPT_TRAINING = 'Rost'
UPGRADE_SPIKED_BARRICADES = 'Rosp'
UPGRADE_SPIRIT_WALKIER_ADEPT_TRAINING = 'Rowt'
UPGRADE_STEEL_ARMOR = 'Roar'
UPGRADE_STEEL_MELEE_WEAPONS = 'Rome'
UPGRADE_STEEL_RANGED_WEAPONS = 'Rora'
UPGRADE_TROLL_REGENERATION = 'Rotr'
UPGRADE_WAR_DRUMS_DAMAGE_INCREASE = 'Rwdm'
UPGRADE_WITCH_DOCTOR_ADEPT_TRAINING = 'Rowd'

## Undead
UPGRADE_BACKPACK_UNDEAD = 'Rupm'
UPGRADE_BANSHEE_ADEPT_TRAINING = 'Ruba'
UPGRADE_BURROW = 'Rubu'
UPGRADE_CANNIBALIZE = 'Ruac'
UPGRADE_CREATURE_ATTACK = 'Rura'
UPGRADE_CREATURE_CARAPACE = 'Rucr'
UPGRADE_DESTROYER_FORM = 'Rusp'
UPGRADE_DISEASE_CLOUD = 'Dupc'
UPGRADE_EXHUME_CORPSES = 'Ruex'
UPGRADE_FREEZING_BREATH = 'Rufb'
UPGRADE_GHOUL_FRENZY = 'Rugf'
UPGRADE_NECROMANCER_ADEPT_TRAINING = 'Rune'
UPGRADE_SKELETAL_LONGEVITY = 'Rusl'
UPGRADE_SKELETAL_MASTERY = 'Rusm'
UPGRADE_STONE_FORM = 'Rusf'
UPGRADE_UNHOLY_ARMOR = 'Ruar'
UPGRADE_UNHOLY_STRENGTH = 'Rume'
UPGRADE_WEB = 'Ruwb'

## Night Elf
UPGRADE_ABOLISH_MAGIC = 'Resi'
UPGRADE_BACKPACK_NIGHT_ELF = 'Repm'
UPGRADE_CORROSIVE_BREATH = 'Recb'
UPGRADE_DRUID_OF_THE_CLAW_ADEPT_TRAINING = 'Redc'
UPGRADE_DRUID_OF_THE_TALON_ADEPT_TRAINING = 'Redt'
UPGRADE_HARDENED_SKIN = 'Rehs'
UPGRADE_HIPPOGRYPH_TRAINING = 'Reht'
UPGRADE_IMPROVED_BOWS = 'Reib'
UPGRADE_MARK_OF_THE_CLAW = 'Reeb'
UPGRADE_MARK_OF_THE_TALON = 'Reec'
UPGRADE_MARKSMANSHIP = 'Remk'
UPGRADE_MOON_ARMOR = 'Rema'
UPGRADE_NATURES_BLESSING = 'Renb'
UPGRADE_REINFORCED_HIDES = 'Rerh'
UPGRADE_RESISTANT_SKIN = 'Rers'
UPGRADE_SENTINEL = 'Resc'
UPGRADE_STRENGTH_OF_THE_MOON = 'Resm'
UPGRADE_STRENGTH_OF_THE_WILD = 'Resw'
UPGRADE_ULTRAVISION = 'Reuv'
UPGRADE_MOON_GLAIVE = 'Remb'
UPGRADE_VORPAL_BLADES = 'Repb'
UPGRADE_WELL_SPRING = 'Rews'

## Special
UPGRADE_ABOLISH_MAGIC_NEUTRAL = 'Rnsi'
UPGRADE_CHAS = 'Roch'
UPGRADE_CORAL_BLADES = 'Rnat'
UPGRADE_CORAL_SCALES = 'Rnam'
UPGRADE_ENSNARE = 'Rnen'
UPGRADE_GLYPH_OF_FORTIFICATION = 'Rgfo'
UPGRADE_GLYPH_OF_ULTRAVISION = 'Rguv'
UPGRADE_NAGA_SIREN_ADEPT_TRAINING = 'Rnsw'
UPGRADE_SUBMERGE = 'Rnsb'

# Destructibles
DESTRUCTIBLE_ASHENVALE_TREE_WALL = 'ATtr'
DESTRUCTIBLE_BARRENS_TREE_WALL = 'BTtw'
DESTRUCTIBLE_BLACK_CITADEL_TREE_WALL = 'KTtw'
DESTRUCTIBLE_CITYSCAPE_FALL_TREE_WALL = 'YTft'
DESTRUCTIBLE_CITYSCAPE_RUINED_TREE_WALL = 'JTct'
DESTRUCTIBLE_CITYSCAPE_SNOWY_TREE_WALL = 'YTst'
DESTRUCTIBLE_CITYSCAPE_SUMMER_TREE_WALL = 'YTct'
DESTRUCTIBLE_CITYSCAPE_WINTER_TREE_WALL = 'YTwt'
DESTRUCTIBLE_DALARAN_RUINS_TREE_WALL = 'JTtw'
DESTRUCTIBLE_DUNGEON_TREE_WALL = 'FTtw'
DESTRUCTIBLE_FALL_TREE_WALL = 'FTtw'
DESTRUCTIBLE_FELWOOD_TREE_WALL = 'CTtr'
DESTRUCTIBLE_ICECROWN_TREE_WALL = 'ITtw'
DESTRUCTIBLE_NORTHREND_TREE_WALL = 'NTtw'
DESTRUCTIBLE_OUTLAND_TREE_WALL = 'OTtw'
DESTRUCTIBLE_RUINS_TREE_WALL = 'ZTtw'
DESTRUCTIBLE_SNOWY_TREE_WALL = 'WTst'
DESTRUCTIBLE_SUMMER_TREE_WALL = 'LTlt'
DESTRUCTIBLE_UNDERGROUND_TREE_WALL = 'GTsh'
DESTRUCTIBLE_VILLAGE_TREE_WALL = 'VTlt'
DESTRUCTIBLE_WINTER_TREE_WALL = 'WTtw'
DESTRUCTIBLE_ASHENVALE_CANOPY_TREE = 'ATtc'
DESTRUCTIBLE_BARRENS_CANOPY_TREE = 'BTtc'
DESTRUCTIBLE_FELWOOD_CANOPY_TREE = 'CTtc'
DESTRUCTIBLE_ICECROWN_CANOPY_TREE = 'ITtc'
DESTRUCTIBLE_NORTHREND_CANOPY_TREE = 'NTtc'
DESTRUCTIBLE_RUINS_CANOPY_TREE = 'ZTtc'
DESTRUCTIBLE_BARREL = 'LTbx'
DESTRUCTIBLE_BARREL_2 = 'LTbs'
DESTRUCTIBLE_BARREL_3 = 'LTbr'
DESTRUCTIBLE_BARREL_OF_EXPLOSIVES = 'LTex'
DESTRUCTIBLE_BARRICADE = 'LTba'
DESTRUCTIBLE_BUILDING = 'XTbd'
DESTRUCTIBLE_CAGE = 'LOcg'
DESTRUCTIBLE_CITY_ENTRANCE = 'YTcx'
DESTRUCTIBLE_CITY_ENTRANCE_2 = 'YTce'
DESTRUCTIBLE_CLIFF_CAVE_GATE_1 = 'DTc1'
DESTRUCTIBLE_CLIFF_CAVE_GATE_2 = 'DTc2'
DESTRUCTIBLE_CRATES = 'LTcr'
DESTRUCTIBLE_DALARAN_VIOLET_CITADEL = 'XTvt'
DESTRUCTIBLE_DEMON_STORM = 'OTds'
DESTRUCTIBLE_DEMONIC_GATE_DIAGONAL_1 = 'ATg2'
DESTRUCTIBLE_DEMONIC_GATE_DIAGONAL_2 = 'ATg4'
DESTRUCTIBLE_DEMONIC_GATE_HORIZONTAL = 'ATg1'
DESTRUCTIBLE_DEMONIC_GATE_VERTICAL = 'ATg3'
DESTRUCTIBLE_DUNGEON_GATE_DIAGONAL_1 = 'DTg2'
DESTRUCTIBLE_DUNGEON_GATE_DIAGONAL_2 = 'DTg4'
DESTRUCTIBLE_DUNGEON_GATE_HORIZONTAL = 'DTg1'
DESTRUCTIBLE_DUNGEON_GATE_VERTICAL = 'DTg3'
DESTRUCTIBLE_DUNGEON_SPIKES = 'DTsp'
DESTRUCTIBLE_EGG_SACK = 'DTes'
DESTRUCTIBLE_ELVEN_GATE_DIAGONAL_1 = 'LTe2'
DESTRUCTIBLE_ELVEN_GATE_DIAGONAL_2 = 'LTe4'
DESTRUCTIBLE_ELVEN_GATE_HORIZONTAL = 'LTe1'
DESTRUCTIBLE_ELVEN_GATE_VERTICAL = 'LTe3'
DESTRUCTIBLE_FORCE_WALL_1 = 'Dofv'
DESTRUCTIBLE_FORCE_WALL_2 = 'Dofw'
DESTRUCTIBLE_FROZEN_THRONE_GATE = 'ITtg'
DESTRUCTIBLE_GATE_DIAGONAL_1 = 'LTg2'
DESTRUCTIBLE_GATE_DIAGONAL_2 = 'LTg4'
DESTRUCTIBLE_GATE_HORIZONTAL = 'LTg1'
DESTRUCTIBLE_GATE_VERTICAL = 'LTg3'
DESTRUCTIBLE_ICE_FLOE_1 = 'ITf1'
DESTRUCTIBLE_ICE_FLOE_2 = 'ITf2'
DESTRUCTIBLE_ICE_FLOE_3 = 'ITf3'
DESTRUCTIBLE_ICE_FLOE_4 = 'ITf4'

DESTRUCTIBLE_LEVER = 'DTlv'

DESTRUCTIBLE_LINE_OF_SIGHT_BLOCKER = 'YTlb'
DESTRUCTIBLE_LINE_OF_SIGHT_BLOCKER_LARGE = 'Ytlc'
DESTRUCTIBLE_PATHING_BLOCKER_AIR = 'YTab'
DESTRUCTIBLE_PATHING_BLOCKER_AIR_LARGE = 'YTac'
DESTRUCTIBLE_PATHING_BLOCKER_BOTH = 'YTfb'
DESTRUCTIBLE_PATHING_BLOCKER_BOTH_LARGE = 'YTfc'
DESTRUCTIBLE_PATHING_BLOCKER_GROUND = 'YTpb'
DESTRUCTIBLE_PATHING_BLOCKER_GROUND_LARGE = 'YTpc'

# Fields
## Abilities
FIELD_ABIL_NAME = 'anam'  # string
FIELD_ABIL_TOOLTIP_NORMAL = 'atp1'  # string
FIELD_ABIL_TOOLTIP_NORMAL_EXTENDED = 'aub1'  # string
FIELD_ABIL_EDITOR_SUFFIX = 'ansf'
FIELD_ABIL_HOTKEY = 'ahky'  # string
FIELD_ABIL_HOTKEY_TURN_OFF = 'auhk'  # string
FIELD_ABIL_HOTKEY_LEARN = 'arhk'  # string
FIELD_ABIL_ICON_NORMAL = 'aart'  # string
FIELD_ABIL_ICON_TURN_OFF = 'auar'  # string
FIELD_ABIL_ICON_RESEARCH = 'arar'  # string
FIELD_ABIL_BUTTON_POSITION_NORMAL_X = 'abpx'
FIELD_ABIL_BUTTON_POSITION_NORMAL_Y = 'abpy'
FIELD_ABIL_BUTTON_POSITION_DISABLE_X = 'aubx'
FIELD_ABIL_BUTTON_POSITION_DISABLE_Y = 'auby'
FIELD_ABIL_BUTTON_POSITION_RESEARCH_X = 'arpx'
FIELD_ABIL_BUTTON_POSITION_RESEARCH_Y = 'arpy'
FIELD_ABIL_REQUIREMENTS = 'areq'  # string
FIELD_ABIL_REQUIREMENTS_LEVELS = 'arqa'  # string
FIELD_ABIL_EFFECT_SOUND = 'aefs'  # string
FIELD_ABIL_ART_CASTER = 'acat'  # string
FIELD_ABIL_STATS_CASTING_TIME = 'acas'  # unreal
FIELD_ABIL_STATS_CAST_RANGE = 'aran'  # unreal
FIELD_ABIL_STATS_DURATION_NORMAL = 'adur'  # unreal
FIELD_ABIL_STATS_LEVELS = 'alev'
FIELD_ABIL_STATS_IS_HERO_ABILITY = 'aher'
FIELD_ABIL_STATS_IS_ITEM_ABILITY = 'aite'
FIELD_ABIL_TECH_CHECK_DEPENDENCIES = 'achd'
FIELD_ABIL_DATA_CHARGE_GOLD_AND_LUMBER_BASE_ORDER_ID = 'Ans5'
FIELD_ABIL_DATA_CHARGE_GOLD_AND_LUMBER_CHARGE_OWNING_PLAYER = 'Ans6'
FIELD_ABIL_DATA_CHARGE_GOLD_AND_LUMBER_GOLD_COST = 'Ndt1'
FIELD_ABIL_DATA_CHARGE_GOLD_AND_LUMBER_LUMBER_COST = 'Ndt2'
FIELD_ABIL_DATA_CROW_FORM_ALTERNATE_FORM_UNIT = 'Emeu'  # string
FIELD_ABIL_DATA_CROW_FORM_NORMAL_FORM_UNIT = 'Eme1'  # string
FIELD_ABIL_DATA_CROW_FORM_MORPHING_FLAGS = 'Eme2'  # integer
FIELD_ABIL_DATA_CROW_FORM_ALTITUDE_ADJUSTMENT_DURATION = 'Eme3'  # unreal
FIELD_ABIL_DATA_CROW_FORM_LANDING_DELAY_TIME = 'Eme4'  # unreal
FIELD_ABIL_DATA_CHANNEL_OPTIONS = 'Ncl3'  # integer
FIELD_ABIL_DATA_CHANNEL_ART_DURATION = 'Ncl4'  # unreal
FIELD_ABIL_DATA_CHANNEL_DISABLE_OTHER_ABILITIES = 'Ncl5'  # integer
FIELD_ABIL_DATA_CHANNEL_BASE_ORDER_ID = 'Ncl6'  # string
FIELD_ABIL_DATA_SPELL_BOOK_SPELL_LIST = 'spb1'
FIELD_ABIL_DATA_SPELL_BOOK_SHARED_COOLDOWN = 'spb2'
FIELD_ABIL_DATA_SPELL_BOOK_MIN_SPELLS = 'spb3'
FIELD_ABIL_DATA_SPELL_BOOK_MAX_SPELLS = 'spb4'
FIELD_ABIL_DATA_ROBO_GOBLIN_STRENGTH_BONUS = 'Nrg5'
FIELD_ABIL_DATA_ROBO_GOBLIN_DEFENSE_BONUS = 'Nrg6'

## Items
FIELD_ITEM_NAME = 'unam'  # string
FIELD_ITEM_TOOLTIP_BASIC = 'utip'  # string
FIELD_ITEM_TOOLTIP_EXTENDED = 'utub'  # string
FIELD_ITEM_DESCRIPTION = 'ides'  # string
FIELD_ITEM_INTERFACE_ICON = 'iico'  # string
FIELD_ITEM_MODEL_USED = 'ifil'  # string
FIELD_ITEM_ABILITIES = 'iabi'  # string

## Units
FIELD_UNIT_ABILITIES_NORMAL = 'uabi'  # string
FIELD_UNIT_ABILITIES_DEFAULT = 'udaa'  # string
FIELD_UNIT_ATTACK_1_ATTACK_TYPE = 'ua1t'  # string
FIELD_UNIT_ATTACK_1_DAMAGE_BASE = 'ua1b'  # integer
FIELD_UNIT_ATTACK_1_DAMAGE_NUM_DICE = 'ua1d'  # integer
FIELD_UNIT_ATTACK_1_PROJECTILE_ART = 'ua1m'  # string
FIELD_UNIT_ATTACK_1_PROJECTILE_SPEED = 'ua1z'  # integer
FIELD_UNIT_ATTACK_1_RANGE = 'ua1r'  # integer
FIELD_UNIT_ATTACK_1_WEAPON_TYPE = 'ua1w'  # string
FIELD_UNIT_BALANCE_DEFENSE_BASE = 'udef'  # integer
FIELD_UNIT_BALANCE_SPEED_BASE = 'umvs'  # integer
FIELD_UNIT_GENERAL_EDITOR_SUFFIX = 'unsf'
FIELD_UNIT_GENERAL_NAME = 'unam'  # string
FIELD_UNIT_GENERAL_TOOLTIP_BASIC = 'utip'  # string
FIELD_UNIT_GENERAL_STRUCTURES_BUILT = 'ubui'  # string
FIELD_UNIT_STATS_BUILD_TIME = 'ubld'
FIELD_UNIT_STATS_FOOD_COST = 'ufoo'
FIELD_UNIT_STATS_FOOD_PRODUCED = 'ufma'
FIELD_UNIT_STATS_FORMATION_RANK = 'ufor'
FIELD_UNIT_STATS_GOLD_BOUNTY_BASE = 'ubba'
FIELD_UNIT_STATS_GOLD_BOUNTY_NUM_DICE = 'ubdi'
FIELD_UNIT_STATS_GOLD_BOUNTY_SIDES_PER_DIE = 'ubsi'
FIELD_UNIT_STATS_GOLD_COST = 'ugol'
FIELD_UNIT_STATS_HIT_POINTS_MAXIMUM = 'uhpm'
FIELD_UNIT_STATS_HIT_POINTS_REGENERATION_RATE = 'uhpr'
FIELD_UNIT_STATS_HIT_POINTS_REGENERATION_TYPE = 'uhrt'
FIELD_UNIT_STATS_IS_BUILDING = 'ubsi'
FIELD_UNIT_STATS_LEVEL = 'ulev'
FIELD_UNIT_STATS_LUMBER_BOUNTY_BASE = 'ulba'
FIELD_UNIT_STATS_LUMBER_BOUNTYNUM_DICE = 'ulbd'
FIELD_UNIT_STATS_LUMBER_BOUNTY_SIDES_PER_DIE = 'ulbs'
FIELD_UNIT_STATS_LUMBER_COST = 'ulum'
FIELD_UNIT_STATS_MANA_INITIAL_AMOUNT = 'umpi'
FIELD_UNIT_STATS_MANA_MAXIMUM = 'umpm'
FIELD_UNIT_STATS_MANA_REGENERATION = 'umpr'
FIELD_UNIT_STATS_POINT_VALUE = 'upoi'
FIELD_UNIT_STATS_PRIORITY = 'upri'
FIELD_UNIT_STATS_RACE = 'urac'
FIELD_UNIT_STATS_REPAIR_GOLD_COST = 'ugor'
FIELD_UNIT_STATS_REPAIR_LUMBER_COST = 'ulur'
FIELD_UNIT_STATS_REPAIR_TIME = 'urtm'
FIELD_UNIT_STATS_SIGHT_RADIUS_DAY = 'usid'  # integer
FIELD_UNIT_STATS_SIGHT_RADIUS_NIGHT = 'usin'  # integer
FIELD_UNIT_STATS_SLEEPS = 'usle'  # integer
FIELD_UNIT_STATS_STOCK_MAXIMUM = 'usma'
FIELD_UNIT_STATS_STOCK_REPLENISH_INTERVAL = 'usrg'
FIELD_UNIT_STATS_STOCK_START_DELAY = 'usst'
FIELD_UNIT_STATS_TRANSPORTED_SIZE = 'ucar'
FIELD_UNIT_STATS_UNIT_CLASSIFICATION = 'utyp'
FIELD_UNIT_UI_MODEL_FILE = 'umdl'  # string
FIELD_UNIT_UI_SCALING_VALUE = 'usca'  # float
FIELD_UNIT_UI_TINT_BLUE = 'uclb'  # integer
FIELD_UNIT_UI_TINT_GREEN = 'uclg'  # integer
FIELD_UNIT_UI_TINT_RED = 'uclr'  # integer

## Upgrades
FIELD_UPGRADE_NAME = 'gnam'  # string

# Paths
## Missiles
PATH_MODEL_PRIEST_MISSILE = r'Abilities\Weapons\PriestMissile\PriestMissile.mdl'
PATH_MODEL_SORCERESS_MISSILE = r'Abilities\Weapons\SorceressMissile\SorceressMissile.mdl'
"""Also used by Spirit Walker"""
PATH_MODEL_GRYPHON_RIDER_MISSILE = r'Abilities\Weapons\GryphonRiderMissile\GryphonRiderMissile.mdl'
PATH_MODEL_SPELL_BREAKER_MISSILE = r'Abilities\Weapons\BloodElfSpellThiefMISSILE\BloodElfSpellThiefMISSILE.mdl'
PATH_MODEL_DRAGONHAWK_RIDER_MISSILE = r'Abilities\Weapons\DragonHawkMissile\DragonHawkMissile.mdl'
PATH_MODEL_GUARD_TOWER_MISSILE = r'Abilities\Weapons\GuardTowerMissile\GuardTowerMissile.mdl'
"""Also used by Watch Tower"""
PATH_MODEL_CANNON_TOWER_MISSILE = r'Abilities\Weapons\CannonTowerMissile\CannonTowerMissile.mdl'
PATH_MODEL_ARCANE_TOWER_MISSILE = r'Abilities\Spells\Undead\OrbOfDeath\OrbOfDeathMissile.mdl'
PATH_MODEL_ARCHMAGE_MISSILE = r'Abilities\Weapons\FireBallMissile\FireBallMissile.mdl'
"""Also used by Orc Warlock, Forest Troll Priests, Centaur Sorcerers"""
PATH_MODEL_BLOOD_MAGE_MISSILE = r'Abilities\Weapons\BloodElfMissile\BloodElfMissile.mdl'
PATH_MODEL_WATER_ELEMENTAL_MISSILE = r'Abilities\Weapons\WaterElementalMissile\WaterElementalMissile.mdl'
PATH_MODEL_PHOENIX_MISSILE = r'Abilities\Weapons\PhoenixMissile\Phoenix_Missile.mdl'
PATH_MODEL_BATTLESHIP_MISSILE = r'Abilities\Weapons\BoatMissile\BoatMissile.mdl'
"""Also used by Frigates"""
PATH_MODEL_SKY_FURY_TOWER_MISSILE = r'Abilities\Weapons\AncestralGuardianMissile\AncestralGuardianMissile.mdl'
PATH_MODEL_DEATH_TOWER_MISSILE = r'Abilities\Spells\NightElf\CorrosiveBreath\CorrosiveBreathMissile.mdl'

PATH_MODEL_TROLL_HEADHUNTER_MISSILE = r'abilities\weapons\huntermissile\huntermissile.mdl'
"""Also used by Orc Burrow"""
PATH_MODEL_DEMOLISHER_MISSILE = r'abilities\weapons\DemolisherMissile\DemolisherMissile.mdl'
"""Spiky ball"""
PATH_MODEL_DEMOLISHER_BURNING_OIL_MISSILE = r'Abilities\Weapons\DemolisherFireMissile\DemolisherFireMissile.mdl'
PATH_MODEL_CATAPULT_MISSILE = r'Abilities\Weapons\AncientProtectorMissile\AncientProtectorMissile.mdl'
"""Also used by Draenei Demolisher, Advanced Boulder Tower"""
PATH_MODEL_KODO_BEAST_MISSILE = r'Abilities\Weapons\Axe\AxeMissile.mdl'
"""Also used by Trolls"""
PATH_MODEL_WYVERN_MISSILE = r'abilities\weapons\WyvernSpear\WyvernSpearMissile.mdl'
PATH_MODEL_TROLL_BATRIDER_MISSILE = r'Abilities\Weapons\BatTrollMissile\BatTrollMissile.mdl'
PATH_MODEL_TROLL_WITCH_DOCTOR_MISSILE = r'Abilities\Weapons\WitchDoctorMissile\WitchDoctorMissile.mdl'
PATH_MODEL_FAR_SEER_MISSILE = r'Abilities\Weapons\FarseerMissile\FarseerMissile.mdl'
"""Also used by Shaman, Obsidian Statue, Naga Tidal Guardian, Gnoll Warden, Harpy Storm-Hag, Energy Tower, etc"""
PATH_MODEL_SHADOW_HUNTER_MISSILE = r'Abilities\Weapons\ShadowHunterMissile\ShadowHunterMissile.mdl'
PATH_MODEL_SERPENT_WARD_MISSILE = r'Abilities\Weapons\ShadowHunterMissile\ShadowHunterMissile.mdl'
PATH_MODEL_REXXAR_MISSILE = r'Abilities\Weapons\RexxarMissile\RexxarMissile.mdl'
PATH_MODEL_SHOCKWAVE_MISSILE = r'Abilities\Spells\Orc\Shockwave\ShockwaveMissile.mdl'

PATH_MODEL_CRYPT_FIEND_MISSILE = r'Abilities\Weapons\CryptFiendMissile\CryptFiendMissile.mdl'
PATH_MODEL_GARGOYLE_MISSILE = r'Abilities\Weapons\GargoyleMissile\GargoyleMissile.mdl'
PATH_MODEL_MEAT_WAGON_MISSILE = r'Abilities\Weapons\MeatwagonMissile\MeatwagonMissile.mdl'
PATH_MODEL_BANSHEE_MISSILE = r'Abilities\Weapons\GargoyleMissile\GargoyleMissile.mdl'
PATH_MODEL_NECROMANCER_MISSILE = r'Abilities\Weapons\NecromancerMissile\NecromancerMissile.mdl'
"""Also used by Naga Sirens"""
PATH_MODEL_FROST_WYRM_MISSILE = r'Abilities\Weapons\FrostWyrmMissile\FrostWyrmMissile.mdl'
"""Also used by Blue Dragons"""
PATH_MODEL_SPIRIT_TOWER_MISSILE = r'Abilities\Weapons\ZigguratMissile\ZigguratMissile.mdl'
PATH_MODEL_NERUBIAN_TOWER_MISSILE = r'Abilities\Weapons\ZigguratFrostMissile\ZigguratFrostMissile.mdl'
PATH_MODEL_LICH_MISSILE = r'Abilities\Weapons\LichMissile\LichMissile.mdl'
PATH_MODEL_SKELETAL_MAGE_MISSILE = r'Abilities\Weapons\SkeletalMageMissile\SkeletalMageMissile.mdl'
PATH_MODEL_DESTROYER_MISSILE = r'Abilities\Weapons\AvengerMissile\AvengerMissile.mdl'
"""Also used by Nether Dragons"""
PATH_MODEL_DEATH_COIL_MISSILE = r'Abilities\Spells\Undead\DeathCoil\DeathCoilMissile.mdl'
PATH_MODEL_CARRION_SWARM_MISSILE = r'Abilities\Spells\Undead\CarrionSwarm\CarrionSwarmMissile.mdl'

PATH_MODEL_ARCHER_MISSILE = r'Abilities\Weapons\Arrow\ArrowMissile.mdl'
PATH_MODEL_HUNTRESS_MISSILE = r'Abilities\Weapons\SentinelMissile\SentinelMissile.mdl'
PATH_MODEL_DRYAD_MISSILE = r'Abilities\Weapons\Dryadmissile\Dryadmissile.mdl'
PATH_MODEL_GLAIVE_THROWER_MISSILE = r'Abilities\Weapons\GlaiveMissile\GlaiveMissile.mdl'
PATH_MODEL_DRUID_OF_THE_TALON_MISSILE = r'Abilities\Weapons\DruidoftheTalonMissile\DruidoftheTalonMissile.mdl'
PATH_MODEL_CHIMAERA_LIGHTNING_MISSILE = r'Abilities\Weapons\ChimaeraLightningMissile\ChimaeraLightningMissile.mdl'
"""Also used by Bronze Dragons"""
PATH_MODEL_CHIMAERA_ACID_MISSILE = r'Abilities\Weapons\ChimaeraAcidMissile\ChimaeraAcidMissile.mdl'
PATH_MODEL_FAERIE_DRAGON_MISSILE = r'Abilities\Weapons\FaerieDragonMissile\FaerieDragonMissile.mdl'
"""Also used by spitting spider, Searinox"""
PATH_MODEL_ANCIENT_PROTECTOR_MISSILE = r'Abilities\Weapons\AncientProtectorMissile\AncientProtectorMissile.mdl'
"""Also used by Golems, Boulder Tower, Dragon Turtle"""
PATH_MODEL_KEEPER_OF_THE_GROVE_MISSILE = r'Abilities\Weapons\KeeperGroveMissile\KeeperGroveMissile.mdl'
PATH_MODEL_PRIESTESS_OF_THE_MOON_MISSILE = r'Abilities\Weapons\MoonPriestessMissile\MoonPriestessMissile.mdl'
"""Also used by Sylvanas (alive)"""
PATH_MODEL_DEMON_HUNTER_MISSILE = r'Abilities\Weapons\DemonHunterMissile\DemonHunterMissile.mdl'
"""Also used by Archimonde, Doom Guard"""
PATH_MODEL_AVATAR_OF_VENGEANCE_MISSILE = r'Abilities\Weapons\SpiritOfVengeanceMissile\SpiritOfVengeanceMissile.mdl'
PATH_MODEL_SPIRIT_OF_VENGEANCE_MISSILE = r'Abilities\Weapons\VengeanceMissile\VengeanceMissile.mdl'
PATH_MODEL_SENTINEL_MISSILE = r'Units\NightElf\Owl\Owl.mdl'
PATH_MODEL_FAN_OF_KNIVES_MISSILE = r'Abilities\Spells\NightElf\FanOfKnives\FanOfKnivesMissile.mdl'
PATH_MODEL_SEARING_ARROWS_MISSILE = r'Abilities\Weapons\SearingArrow\SearingArrowMissile.mdl'
PATH_MODEL_SHADOW_STRIKE_MISSILE = r'Abilities\Spells\NightElf\shadowstrike\ShadowStrikeMissile.mdl'

PATH_MODEL_COUATL_MISSILE = r'Abilities\Weapons\WingedSerpentMissile\WingedSerpentMissile.mdl'
PATH_MODEL_SNAP_DRAGON_MISSILE = r'Abilities\Weapons\snapMissile\snapMissile.mdl'
PATH_MODEL_NAGA_SEA_WITCH_MISSILE = r'Abilities\Weapons\NagaArrowMissile\NagaArrowMissile.mdl'

PATH_MODEL_RED_DRAGON_MISSILE = r'Abilities\Weapons\RedDragonBreath\RedDragonMissile.mdl'
"""Also used by Black Dragons, Infernal Contraptions, Earth-Fury Towers"""
PATH_MODEL_GREEN_DRAGON_MISSILE = r'Abilities\Weapons\GreenDragonMissile\GreenDragonMissile.mdl'
PATH_MODEL_HARPY_MISSILE = r'Abilities\Weapons\HarpyMissile\HarpyMissile.mdl'
"""Also used by Arachnathids"""
PATH_MODEL_BANDIT_MISSILE = r'Abilities\Weapons\Banditmissile\Banditmissile.mdl'
PATH_MODEL_REEF_ELEMENTAL_MISSILE = r'Abilities\Weapons\SeaElementalMissile\SeaElementalMissile.mdl'
PATH_MODEL_GNOLL_ASSASSIN_MISSILE = r'Abilities\Weapons\PoisonArrow\PoisonArrowMissile.mdl'
PATH_MODEL_MAKRURA_MISSILE = r'Abilities\Weapons\MakuraMissile\MakuraMissile.mdl'
PATH_MODEL_QUILLBOARD_MISSILE = r'Abilities\Weapons\BristleBackMissile\BristleBackMissile.mdl'
PATH_MODEL_SATYR_SHADOWDANCER_MISSILE = r'Abilities\Weapons\BlackKeeperMissile\BlackKeeperMissile.mdl'
"""Doesn't preview?"""
PATH_MODEL_SLUDGE_FLINGER_MISSILE = r'Abilities\Weapons\SludgeMissile\SludgeMissile.mdl'
PATH_MODEL_TUSKARR_MISSILE = r'abilities\weapons\TuskarSpear\TuskarSpear.mdl'
PATH_MODEL_VOIDWALKER_MISSILE = r'Abilities\Weapons\VoidWalkerMissile\VoidWalkerMissile.mdl'
"""Looks like a purple version of Necromancer missile"""
PATH_MODEL_GOBLIN_ALCHEMIST_MISSILE = r'Abilities\Weapons\BrewmasterMissile\BrewmasterMissile.mdl'
PATH_MODEL_FIRELORD_MISSILE = r'Abilities\Weapons\LordofFlameMissile\LordofFlameMissile.mdl'
PATH_MODEL_LAVA_SPAWN_MISSILE = r'Abilities\Weapons\LavaSpawnMissile\LavaSpawnMissile.mdl'

PATH_MODEL_ENSNARE_MISSILE = r'Abilities\Weapons\LavaSpawnMissile\LavaSpawnMissile.mdl'

## Missile Impacts
PATH_MODEL_SIEGE_ENGINE_IMPACT = r'Abilities\Weapons\SteamTank\SteamTankImpact.mdl'
PATH_MODEL_RIFLEMAN_IMPACT = r'Abilities\Weapons\Rifle\RifleImpact.mdl'
PATH_MODEL_GOBLIN_BLASTER_IMPACT = r'Abilities\Weapons\FragDriller\FragDriller.mdl'
PATH_MODEL_DEATH_COIL_IMPACT = r'Abilities\Spells\Undead\DeathCoil\DeathCoilSpecialArt.mdl'
PATH_MODEL_HEALING_WAVE_IMPACT = r'Abilities\Spells\Orc\HealingWave\HealingWaveTarget.mdl'
PATH_MODEL_DEATH_AND_DECAY_IMPACT = r'Abilities\Spells\Undead\DeathandDecay\DeathandDecayDamage.mdl'
PATH_MODEL_POLYMORPH_IMPACT = r'Abilities\Spells\Human\Polymorph\PolyMorphDoneGround.mdl'
PATH_MODEL_CHAIN_LIGHTNING_IMPACT = r'Abilities\Weapons\Bolt\BoltImpact.mdl'
PATH_MODEL_ABOLISH_MAGIC_IMPACT = r'Abilities\Spells\Human\DispelMagic\DispelMagicTarget.mdl'

PATH_MODEL_FROST_NOVA_TARGET = r'Abilities\Spells\Undead\FrostNova\FrostNovaTarget.mdl'
PATH_MODEL_INFERNO_TARGET = r'Units\Demon\Infernal\InfernalBirth.mdl'
PATH_MODEL_DEATH_AND_DECAY_EFFECT = r'Abilities\Spells\Undead\DeathandDecay\DeathandDecayTarget.mdl'
PATH_MODEL_STARFALL_EFFECT = r'Abilities\Spells\NightElf\Starfall\StarfallCaster.mdl'
PATH_MODEL_TRANQUILITY_EFFECT = r'Abilities\Spells\NightElf\Tranquility\Tranquility.mdl'
PATH_MODEL_DOOM_EFFECT = r'Abilities\Spells\Other\Doom\DoomTarget.mdl'
PATH_MODEL_INCINERATE_EFFECT = r'Abilities\Spells\Other\Incinerate\IncinerateBuff.mdl'

# Base Order IDs
BASE_ORDER_IDS = [
    'absorb',
    'acidbomb',
    'acolyteharvest',
    'AImove',
    'ambush',
    'ancestralspirit',
    'ancestralspirittaarget',
    'animatedead',
    'antimagicshell',
    # 'attack',
    # 'attackground',
    # 'attackonce',
    'attributemodskill',
    'auraunholy',
    'auravampiric',
    'autodispel',
    'autodispeloff',
    'autodispelon',
    'autoentangle',
    'autoentangleinstant',
    'autoharvestgold',
    'autoharvestlumber',
    'avatar',
    'avengerform',
    'awaken',
    'banish',
    'barkskin',
    'bakrkskinoff',
    'bakrskinon',
    'battleroar',
    'battlestations',
    'bearform',
    'berserk',
    'blackarrow',
    'blackarrowoff',
    'blackarrowon',
    'blight',
    'blink',
    'blizzard',
    'bloodlust',
    'bloodlustoff',
    'bloodluston',
    # 'board',
    'breathoffire',
    'breathoffrost',
    'build',
    'burrow',
    'cannibalize',
    'carrionscarabs',
    'carrionscarabsinstant',
    'carrionscarabson',
    'carrionscarabsoff',
    'carrionswarm',
    'chainlightning',
    'channel',
    'charm',
    'chemicalrage',
    'cloudoffog',
    'clusterrockets',
    'coldarrows',
    'coldarrowstarg',
    'controlmagic',
    'corporealform',
    'corrosivebreath',
    'coupleinstant',
    'coupletarget',
    'creepanimatedead',
    'creepdevour',
    'creepheal',
    'creephealoff',
    'creephealon',
    'creepthunderbolt',
    'creepthunderclap',
    'cripple',
    'curse',
    'curseoff',
    'curseon',
    'cyclone',
    'darkconversion',
    'darkportal',
    'darkritual',
    'darksummoning',
    'deathanddecay',
    'deathcoil',
    'deathpact',
    'decouple',
    'defend',
    'detectaoe',
    'detonate',
    'devour',
    'devourmagic',
    'disassociate',
    'disenchant',
    'dismount',
    'dispel',
    'divineshield',
    'doom',
    'drain',
    'dreadlordinferno',
    # 'dropitem',
    'drunkenhaze',
    'earthquake',
    'eattree',
    'elementalfury',
    'ensnare',
    'ensnareoff',
    'ensnareon',
    'entangle',
    'entangleinstant',
    'entanglingroots',
    'etherealform',
    'evileye',
    'faeriefire',
    'faeriefireoff',
    'faeriefireon',
    'fanofknives',
    'farsight',
    'fingerofdeath',
    'firebolt',
    'flamestrike',
    'flamingarrows',
    'flamingarrowstarg',
    'flamingattack',
    'flamingattacktarg',
    'flare',
    'forceboard',
    'forceofnature',
    'forkedlightning',
    'freezingbreath',
    'frenzy',
    'frenzyoff',
    'frenzyon',
    'frostarmor',
    'frostarmoroff',
    'frostarmoron',
    'frostnova',
    # 'getitem',
    'gold2lumber',
    'grabtree',
    # ...
]
