
# Abilities
ABIL_CHANNEL = 'ANcl'  # Abilities/Neutral Hostile/Heroes
ABIL_SPELL_BOOK = 'Aspb'  # Abilities/Special/Items

## Human
ABIL_AERIAL_SHACKLES = 'Amls'
ABIL_BARRAGE = 'Aroc'
ABIL_CALL_TO_ARMS_TOWN_HALL = 'Amic'
ABIL_CALL_TO_ARMS_PEASANT = 'Amil'
ABIL_CARGO_HOLD_TANK = 'Sch4'
ABIL_CHAOS = 'Srtt'  # Turns siege engines into AA siege engines
ABIL_CLOUD = 'Aclf'
ABIL_CONTROL_MAGIC = 'Acmg'
ABIL_DEFEND = 'Adef'
ABIL_DISPEL_MAGIC = 'Adis'
ABIL_FEEDBACK_ARCANE_TOWER = 'Afbt'
ABIL_FEEDBACK_SPELL_BREAKER = 'Afbk'
ABIL_FLAK_CANNONS = 'Aflk'
ABIL_FLARE = 'Afla'
ABIL_FLYING_MACHINE_BOMBS = 'Agyb'
ABIL_FRAGMENTATION_SHARDS = 'Afsh'
ABIL_HEAL = 'Ahea'
ABIL_INNER_FIRE = 'Ainf'
ABIL_INVISIBILITY = 'Aivs'
ABIL_MAGIC_DEFENSE = 'Amdf'  # Unused spell breaker ability
ABIL_MAGIC_SENTRY_HUMAN_TOWERS = 'Adts'
ABIL_PHOENIX_FIRE = 'Apxf'
ABIL_PHOENIX_MORPHING_EGG_RELATED = 'Aphx'
ABIL_POLYMORPH = 'Aply'
ABIL_REPAIR_HUMAN = 'Ahrp'
ABIL_REVEAL = 'AHta'
ABIL_SLOW = 'Aslo'
ABIL_SPELL_STEAL = 'Asps'
ABIL_SPHERE = 'Asph'  # ???
ABIL_STORM_HAMMERS = 'Asth'
ABIL_TRUE_SIGHT_FLYING_MACHINE = 'Agyv'

ABIL_AVATAR = 'AHav'
ABIL_BANISH = 'AHbn'
ABIL_BASH = 'AHbh'
ABIL_BLIZZARD = 'AHbz'
ABIL_BRILLLIANCE_AURA = 'AHab'
ABIL_DEVOTION_AURA = 'AHad'
ABIL_DIVINE_SHIELD = 'AHds'
ABIL_FLAME_STRIKE = 'AHfs'
ABIL_HOLY_LIGHT = 'AHhb'
ABIL_MASS_TELEPORT = 'AHmt'
ABIL_PHOENIX = 'AHpx'
ABIL_RESURRECTION = 'AHre'
ABIL_SIPHON_MANA = 'AHdr'
ABIL_STORM_BOLT = 'AHtb'
ABIL_SUMMON_WATER_ELEMENTAL = 'AHwe'
ABIL_THUNDER_CLAP = 'AHtc'

## Orc
ABIL_ANCESTRAL_SPIRIT = 'Aast'
ABIL_BATTLE_STATIONS = 'Abtl'
ABIL_BATTLE_STATIONS_CHAOS_ORC_BURROW = 'Sbtl'
ABIL_BERSERK = 'Absk'
ABIL_BERSERKER_UPGRADE = 'Sbsk'
ABIL_BLOODLUST = 'Ablo'
ABIL_BURNING_OIL = 'Abof'
ABIL_CARGO_HOLD_ORC_BURROW = 'Abun'
ABIL_CHAOS_GROM = 'Sca6'
ABIL_CHAOS_GRUNT = 'Sca1'
ABIL_CHAOS_KODO_BEAST = 'Sca4'
ABIL_CHAOS_PEON = 'Sca5'
ABIL_CHAOS_RAIDER = 'Sca2'
ABIL_CHAOS_SHAMAN = 'Sca3'
ABIL_CHAOS_CARGO_HOLD = 'Achl'
ABIL_CORPOREAL_FORM = 'Acpf'
ABIL_DETECTOR_SENTRY_WARD = 'Adt1'
ABIL_DEVOUR = 'Adev'
ABIL_DEVOUR_CARGO = 'Advc'
ABIL_DISENCHANT = 'Adcn'
ABIL_DISENCHANT_OLD = 'Adch'
ABIL_ENSNARE = 'Aens'
ABIL_ENVENOMED_SPEARS = 'Aven'
ABIL_ETHEREAL_FORM = 'Aetf'
ABIL_HEALING_WARD_WITCH_DOCTOR = 'Ahwd'
ABIL_HEALING_WARD_AURA_HEALING_WARD = 'Aor'
ABIL_LIGHTNING_SHIELD = 'Alsh'
ABIL_LIQUID_FIRE = 'Aliq'
ABIL_LOAD_ORC_BURROW = 'Sloa'
ABIL_PACK_MULE = 'Apak'
ABIL_PILLAGE = 'Asal'
ABIL_PULVERIZE = 'Awar'
ABIL_PURGE = 'Apg2'
ABIL_PURGE_OLD = 'Aprg'
ABIL_REINFORCED_BURROWS_UPGRADE = 'Arbr'
ABIL_REPAIR_ORC = 'Arep'
ABIL_SENTRY_WARD = 'Aeye'
ABIL_SPIKED_BARRICADES = 'Aspi'
ABIL_SPIRIT_LINK = 'Aspl'
ABIL_STAND_DOWN = 'Astd'
ABIL_STASIS_TRAP = 'Asta'
ABIL_UNSTABLE_CONCOCTION = 'Auco'
ABIL_WAR_DRUMS = 'Aakb'

ABIL_BIG_BAD_VOODOO = 'AOvd'
ABIL_BLADESTORM = 'AOww'
ABIL_CHAIN_LIGHTNING = 'AOcl'
ABIL_CRITICAL_STRIKE = 'AOcr'
ABIL_EARTHQUAKE = 'AOeq'
ABIL_ENDURANCE_AURA = 'AOae'
ABIL_ENDURANCE_AURA_CAIRNE = 'AOr2'
ABIL_FAR_SIGHT = 'AOfs'
ABIL_FERAL_SPIRIT = 'AOsf'
ABIL_HEALING_WAVE = 'AOhw'
ABIL_HEALING_WAVE_ROKHAN = 'ANhw'
ABIL_HEX = 'AOhx'
ABIL_HEX_ROKHAN = 'ANhx'
ABIL_MIRROR_IMAGE = 'AOmi'
ABIL_REINCARNATION = 'AOre'
ABIL_REINCARNATION_CAIRNE = 'AOr3'
ABIL_SERPENT_WARD = 'AOsw'
ABIL_SERPEND_WARD_ROKHAN = 'Arsw'
ABIL_SHOCKWAVE = 'AOsh'
ABIL_SHOCKWAVE_CAIRNE = 'AOs2'
ABIL_VOODOO_SPIRITS = 'AOIs'
ABIL_WAR_STOMP = 'AOws'
ABIL_WAR_STOMP_CAIRNE = 'AOw2'
ABIL_WIND_WALK = 'AOwk'

## Undead

ABIL_ANIMATE_DEAD = 'AUan'
ABIL_CARRION_BEETLES = 'AUcb'
ABIL_CARRION_SWARM = 'AUcs'
ABIL_DARK_RITUAL = 'AUdr'
ABIL_DEATH_AND_DECAY = 'AUdd'
ABIL_DEATH_COIL = 'AUdc'
ABIL_DEATH_PACT = 'AUdp'
ABIL_FROST_ARMOR = 'AUfa'
ABIL_FROST_ARMOR_AUTOCAST = 'AUfu'
ABIL_FROST_NOVA = 'AUfn'
ABIL_IMPALE = 'AUim'
ABIL_INFERNO = 'AUin'
ABIL_LOCUST_SWARM = 'AUls'
ABIL_SLEEP = 'AUsl'
ABIL_UNHOLY_AURA = 'AUau'
ABIL_VAMPIRIC_AURA = 'AUav'

## Night Elf

ABIL_BLINK = 'AEbl'
ABIL_BLINK_NEUTRAL = 'ANbl'
ABIL_ENTANGLING_ROOTS = 'AEer'
ABIL_EVASION = 'AEev'
ABIL_FAN_OF_KNIVES = 'AEfk'
ABIL_FORCE_OF_NATURE = 'AEfn'
ABIL_IMMOLATION = 'AEim'
ABIL_MANA_BURN = 'AEmb'
ABIL_METAMORPHOSIS = 'AEme'
ABIL_SCOUT = 'AEst'
ABIL_SEARING_ARROWS = 'AHfa'
ABIL_SHADOW_STRIKE = 'AEsh'
ABIL_STARFALL = 'AEsf'
ABIL_THORNS_AURA = 'AEah'
ABIL_TRANQUILITY = 'AEtq'
ABIL_TRUESHOT_AURA = 'AEar'
ABIL_VENGEANCE = 'AEsv'

## Neutral Hostile
ABIL_CROW_FORM_MEDIVH = 'Amrf'

## Neutral Passive
ABOL_ABOLISH_MAGIC_NEUTRAL = 'Andm'
ABIL_BUILDING_DAMAGE_AURA_TORNADO = 'Atdg'
ABIL_CYCLONE_NEUTRAL = 'Acny'
ABIL_ENSNARE_NEUTRAL = 'ANen'
ABIL_FROST_ARMOR_NEUTRAL = 'ACfu'
ABIL_HARDENED_SKIN_NEUTRAL = 'Ansk'
ABIL_PARASITE = 'ANpa'
ABIL_SLOW_AURA_TORNADO = 'Aasl'
ABIL_SUMMONING_RITUAL = 'Ahnl'
ABIL_TORNADO_SPIN = 'Atsp'
ABIL_TORNADO_WANDER = 'Atwa'

## Special
ABIL_AOE_DAMAGE_ON_DEATH_BIG_MINE = 'Amnz'
ABIL_AOE_DAMAGE_ON_DEATH_GOBLIN_MINE = 'Amnx'
ABIL_AOE_DAMAGE_ON_DEATH_SAPPER = 'Adda'
ABIL_BLIGHT_DISPEL_LARGE = 'Abdl'
ABIL_BLIGHT_DISPEL_SMALL = 'Abds'
ABIL_BURROW_DETECTION_FLIERS = 'Abdt'
ABIL_CARGO_HOLD_GOBLIN_ZEPPELIN = 'Sch3'
ABIL_CARGO_HOLD_SHIP = 'Sch5'
ABIL_CARGO_HOLD_DEATH_NEUTRAL_HOSTILE = 'Achd'
ABIL_GOLD_MINE = 'Agld'
ABIL_HARVEST_GOLD_AND_LUMBER = 'Ahar'
ABIL_HARVEST_NEUTRAL = 'ANha'
ABIL_INVENTORY_HERO = 'AInv'
ABIL_INVULNERABLE_NEUTRAL = 'Avul'
ABIL_LOAD_GOBLIN_ZEPPELIN = 'Aloa'
ABIL_LOAD_SHIP = 'Slo3'
ABIL_MINE_EXPLODING_GOBLIN_LAND_MINE = 'Amin'
ABIL_PERMANENT_IMMOLATION_NEUTRAL_HOSTILE_1 = 'ANpi'
ABIL_PERMANENT_IMMOLATION_NEUTRAL_HOSTILE_2 = 'Apig'
ABIL_PERMANENT_INVISIBILITY = 'Apiv'
ABIL_PHOENIX_FIRE_FLYER = 'Apmf'
ABIL_POISON_STING = 'Apoi'
ABIL_RALLY = 'Aral'
ABIL_RETURN_GOLD = 'Argd'
ABIL_RETURN_GOLD_AND_LUMBER = 'Argl'
ABIL_RETURN_LUMBER = 'Arlm'
ABIL_REVENGE = 'Arng'
ABIL_REVIVE_HERO = 'Arev'
ABIL_REVIVE_HERO_INSTANTLY = 'Aawa'
ABIL_SELECT_HERO = 'Aneu'
ABIL_SELECT_UNIT = 'Ane2'
ABIL_SELL_ITEMS = 'Asid'
ABIL_SELL_UNITS = 'Asud'
ABIL_SHOP_PURCHASE_ITEM = 'Apit'
ABIL_SHOP_SHARING = 'Aall'
ABIL_TRUE_SIGHT_NEUTRAL_1 = 'Adtg'
ABIL_TRUE_SIGHT_NEUTRAL_2 = 'ANtr'
ABIL_UNIT_INVENTORY_HUMAN = 'Aihn'
ABIL_UNIT_INVENTORY_NIGHT_ELF = 'Aien'
ABIL_UNIT_INVENTORY_ORC = 'Aion'
ABIL_UNIT_INVENTORY_UNDEAD = 'Aiun'
ABIL_UNLOAD_AIR_TRANSPORTS = 'Adro'
ABIL_UNLOAD_SEA_TRANSPORTS = 'Sdro'
ABIL_UNLOAD_INSTANT_ENTANGLED_MINE = 'Wdri'
ABIL_WANDER_NEUTRAL = 'Wwan'
ABIL_WAYGATE_ABILITY = 'Awrp'

ABIL_AVATAR_NEUTRAL = 'ANav'
ABIL_SHOCKWAVE_NEUTRAL = 'ANsh'

# Buffs + Effects
## Human
BUFF_AVATAR = 'BHav'
BUFF_BANISH = 'BHbn'
BUFF_BLIZZARD = 'BHbd'
BUFF_BLIZZARD_CASTER = 'BHbz'
BUFF_BRILLIANCE_AURA = 'BHab'
BUFF_DEVOTION_AURA = 'BHad'
BUFF_DIVINE_SHIELD = 'BHds'
BUFF_DRAIN_LIFE_AND_MANA_CASTER = 'Bdcb'
BUFF_DRAIN_LIFE_AND_MANA_TARGET = 'Bdtb'
BUFF_DRAIN_LIFE_CASTER = 'Bdcl'
BUFF_DRAIN_LIFE_TARGET = 'Bdtl'
BUFF_DRAIN_MANA_CASTER = 'Bdcm'
BUFF_DRAIN_MANA_TARGET = 'Bdtm'
BUFF_FLAME_STRIKE = 'BHfs'
BUFF_THUNDER_CLAP = 'BHtc'
BUFF_WATER_ELEMENTAL = 'BHwe'
BUFF_AERIAL_SHACKLES = 'Bmlt'
BUFF_AERIAL_SHACKLES_CASTER = 'Bmlc'
BUFF_CLOUD = 'Bclf'
BUFF_CONTROL_MAGIC = 'Bcmg'
BUFF_HEAL = 'Bhea'
BUFF_INNER_FIRE = 'Binf'
BUFF_INVISIBILITY = 'Binv'
BUFF_INVISIBILITY_EXTRA = 'Bivs'
BUFF_MILITIA = 'Bmil'
BUFF_PHOENIX = 'Bphx'
BUFF_PHOENIX_FIRE = 'Bpxf'
BUFF_POLYMORPH = 'Bply'
BUFF_SLOW = 'Bslo'

EFFECT_BLIZZARD = 'XHbz'
EFFECT_FLAME_STRIKE = 'XHfs'
EFFECT_BUILDING_DAMAGE_HUMAN_LARGE = 'Xfhl'
EFFECT_BUILDING_DAMAGE_HUMAN_MEDIUM = 'Xfhm'
EFFECT_BUILDING_DAMAGE_HUMAN_SMALL = 'Xfhs'
EFFECT_CLOUD = 'Xclf'
EFFECT_FLARE = 'Xfla'

## Orc
BUFF_BIG_BAD_VOODOO = 'BOvd'
BUFF_BIG_BAD_VOODOO_CASTER = 'BOvc'
BUFF_BLADESTORM_CASTER = 'BOww'
BUFF_COMMAND_AURA = 'BOac'
BUFF_EARTHQUAKE = 'BOeq'
BUFF_EARTHQUAKE_CASTER = 'BOea'
BUFF_ENDURANCE_AURA = 'BOae'
BUFF_FERAL_SPIRIT = 'BOsf'
BUFF_HEX = 'BOhx'
MIRROR_IMAGE = 'BOmi'
BUFF_SHOCKWAVE_CASTER = 'BOsh'
BUFF_WARD = 'BOwd'
BUFF_WIND_WALK = 'BOwk'
BUFF_BERSERK = 'Bbsk'
BUFF_BLOODLUST = 'Bblo'
BUFF_BURNING_OIL = 'Bbof'
BUFF_DEVOUR = 'Bdvv'
BUFF_DEVOUR_CASTER = 'Bdig'
BUFF_ENSNARE_AIR = 'Bena'
BUFF_ENSNARE_GENERAL = 'Bens'
BUFF_ENSNARE_GROUND = 'Beng'
BUFF_HEALING_WARD = 'Bhwd'
BUFF_HEALING_WARD_AURA = 'Boar'
BUFF_LIGHTNING_SHIELD = 'Blsh'
BUFF_LIGHTNING_SHIELD_CASTER = 'Blsa'
BUFF_LIQUID_FIRE = 'Bliq'
BUFF_MANA_REGENERATION_AURA = 'Barm'
BUFF_PURGE = 'Bprg'
BUFF_SENTRY_WARD = 'Beye'
BUFF_SPIRIT_LINK = 'Bspl'
BUFF_STASIS_TRAP = 'Bstt'
BUFF_WAR_DRUMS = 'Bakb'

EFFECT_EARTHQUAKE = 'XOeq'
EFFECT_REINCARNATION = 'XOre'
EFFECT_BUILDING_DAMAGE_ORC_LARGE = 'Xfol'
EFFECT_BUILDING_DAMAGE_ORC_MEDIUM = 'Xfom'
EFFECT_BUILDING_DAMAGE_ORC_SMALL = 'Xfos'
EFFECT_BURNING_OIL = 'Xbof'

## Undead

## Night Elf

## Special

# Upgrades
## Human
UPGRADE_ANIMAL_WAR_TRAINING = 'Rhan'
UPGRADE_BACKPACK_HUMAN = 'Rhpm'
UPGRADE_BARRAGE = 'Rhrt'
UPGRADE_BLACK_GUNPOWDER = 'Rhra'
UPGRADE_CLOUD = 'Rhcd'
UPGRADE_CONTROL_MAGIC = 'Rhss'
UPGRADE_DEFEND = 'Rhde'
UPGRADE_FLAK_CANNONS = 'Rhfc'
UPGRADE_FLARE = 'Rhfl'
UPGRADE_FLYING_MACHINE_BOMBS = 'Rhgb'
UPGRADE_FRAGMENTATION_SHARDS = 'Rhfs'
UPGRADE_IMPROVED_LUMBER_HARVESTING = 'Rhlh'
UPGRADE_IMPROVED_MASONRY = 'Rhac'
UPGRADE_IRON_FORGED_SWORDS = 'Rhme'
UPGRADE_IRON_PLATING = 'Rhar'
UPGRADE_LONG_RIFLES = 'Rhri'
UPGRADE_MAGIC_SENTRY = 'Rhse'
UPGRADE_PRIEST_ADEPT_TRAINING = 'Rhpt'
UPGRADE_SORCERESS_ADEPT_TRAINING = 'Rhst'
UPGRADE_STORM_HAMMERS = 'Rhhb'
UPGRADE_STUDDED_LEATHER_ARMOR = 'Rhla'

## Orc
UPGRADE_BACKPACK_ORC = 'Ropm'
UPGRADE_BERSERKER_STRENGTH = 'Robs'
UPGRADE_BERSERKER_UPGRADE = 'Robk'
UPGRADE_BURNING_OIL = 'Robf'
UPGRADE_ENSNARE = 'Roen'
UPGRADE_ENVENOMED_SPEARS = 'Rovs'
UPGRADE_LIQUID_FIRE = 'Rolf'
UPGRADE_PILLAGE = 'Ropg'
UPGRADE_PULVERIZE = 'Rows'
UPGRADE_REINFORCED_DEFENSES = 'Rorb'
UPGRADE_SHAMAN_ADEPT_TRAINING = 'Rost'
UPGRADE_SPIKED_BARRICADES = 'Rosp'
UPGRADE_SPIRIT_WALKIER_ADEPT_TRAINING = 'Rowt'
UPGRADE_STEEL_ARMOR = 'Roar'
UPGRADE_STEEL_MELEE_WEAPONS = 'Rome'
UPGRADE_STEEL_RANGED_WEAPONS = 'Rora'
UPGRADE_TROLL_REGENERATION = 'Rotr'
UPGRADE_WAR_DRUMS_DAMAGE_INCREASE = 'Rwdm'
UPGRADE_WITCH_DOCTOR_ADEPT_TRAINING = 'Rowd'

## Undead
UPGRADE_BACKPACK_UNDEAD = 'Rupm'
UPGRADE_BANSHEE_ADEPT_TRAINING = 'Ruba'
UPGRADE_BURROW = 'Rubu'
UPGRADE_CANNIBALIZE = 'Ruac'
UPGRADE_CREATURE_ATTACK = 'Rura'
UPGRADE_CREATURE_CARAPACE = 'Rucr'
UPGRADE_DESTROYER_FORM = 'Rusp'
UPGRADE_DISEASE_CLOUD = 'Dupc'
UPGRADE_EXHUME_CORPSES = 'Ruex'
UPGRADE_FREEZING_BREATH = 'Rufb'
UPGRADE_GHOUL_FRENZY = 'Rugf'
UPGRADE_NECROMANCER_ADEPT_TRAINING = 'Rune'
UPGRADE_SKELETAL_LONGEVITY = 'Rusl'
UPGRADE_SKELETAL_MASTERY = 'Rusm'
UPGRADE_STONE_FORM = 'Rusf'
UPGRADE_UNHOLY_ARMOR = 'Ruar'
UPGRADE_UNHOLY_STRENGTH = 'Rume'
UPGRADE_WEB = 'Ruwb'

## Night Elf
UPGRADE_ABOLISH_MAGIC = 'Resi'
UPGRADE_BACKPACK_NIGHT_ELF = 'Repm'
UPGRADE_CORROSIVE_BREATH = 'Recb'
UPGRADE_DRUID_OF_THE_CLAW_ADEPT_TRAINING = 'Redc'
UPGRADE_DRUID_OF_THE_TALON_ADEPT_TRAINING = 'Redt'
UPGRADE_HARDENED_SKIN = 'Rehs'
UPGRADE_HIPPOGRYPH_TRAINING = 'Reht'
UPGRADE_IMPROVED_BOWS = 'Reib'
UPGRADE_MARK_OF_THE_CLAW = 'Reeb'
UPGRADE_MARK_OF_THE_TALON = 'Reec'
UPGRADE_MARKSMANSHIP = 'Remk'
UPGRADE_MOON_ARMOR = 'Rema'
UPGRADE_NATURES_BLESSING = 'Renb'
UPGRADE_REINFORCED_HIDES = 'Rerh'
UPGRADE_RESISTANT_SKIN = 'Rers'
UPGRADE_SENTINEL = 'Resc'
UPGRADE_STRENGTH_OF_THE_MOON = 'Resm'
UPGRADE_STRENGTH_OF_THE_WILD = 'Resw'
UPGRADE_ULTRAVISION = 'Reuv'
UPGRADE_MOON_GLAIVE = 'Remb'
UPGRADE_VORPAL_BLADES = 'Repb'
UPGRADE_WELL_SPRING = 'Rews'

## Special
UPGRADE_ABOLISH_MAGIC_NEUTRAL = 'Rnsi'
UPGRADE_CHAS = 'Roch'
UPGRADE_CORAL_BLADES = 'Rnat'
UPGRADE_CORAL_SCALES = 'Rnam'
UPGRADE_ENSNARE = 'Rnen'
UPGRADE_GLYPH_OF_FORTIFICATION = 'Rgfo'
UPGRADE_GLYPH_OF_ULTRAVISION = 'Rguv'
UPGRADE_NAGA_SIREN_ADEPT_TRAINING = 'Rnsw'
UPGRADE_SUBMERGE = 'Rnsb'

# Destructibles
DESTRUCTIBLE_ASHENVALE_TREE_WALL = 'ATtr'
DESTRUCTIBLE_BARRENS_TREE_WALL = 'BTtw'
DESTRUCTIBLE_BLACK_CITADEL_TREE_WALL = 'KTtw'
DESTRUCTIBLE_CITYSCAPE_FALL_TREE_WALL = 'YTft'
DESTRUCTIBLE_CITYSCAPE_RUINED_TREE_WALL = 'JTct'
DESTRUCTIBLE_CITYSCAPE_SNOWY_TREE_WALL = 'YTst'
DESTRUCTIBLE_CITYSCAPE_SUMMER_TREE_WALL = 'YTct'
DESTRUCTIBLE_CITYSCAPE_WINTER_TREE_WALL = 'YTwt'
DESTRUCTIBLE_DALARAN_RUINS_TREE_WALL = 'JTtw'
DESTRUCTIBLE_DUNGEON_TREE_WALL = 'FTtw'
DESTRUCTIBLE_FALL_TREE_WALL = 'FTtw'
DESTRUCTIBLE_FELWOOD_TREE_WALL = 'CTtr'
DESTRUCTIBLE_ICECROWN_TREE_WALL = 'ITtw'
DESTRUCTIBLE_NORTHREND_TREE_WALL = 'NTtw'
DESTRUCTIBLE_OUTLAND_TREE_WALL = 'OTtw'
DESTRUCTIBLE_RUINS_TREE_WALL = 'ZTtw'
DESTRUCTIBLE_SNOWY_TREE_WALL = 'WTst'
DESTRUCTIBLE_SUMMER_TREE_WALL = 'LTlt'
DESTRUCTIBLE_UNDERGROUND_TREE_WALL = 'GTsh'
DESTRUCTIBLE_VILLAGE_TREE_WALL = 'VTlt'
DESTRUCTIBLE_WINTER_TREE_WALL = 'WTtw'
DESTRUCTIBLE_ASHENVALE_CANOPY_TREE = 'ATtc'
DESTRUCTIBLE_BARRENS_CANOPY_TREE = 'BTtc'
DESTRUCTIBLE_FELWOOD_CANOPY_TREE = 'CTtc'
DESTRUCTIBLE_ICECROWN_CANOPY_TREE = 'ITtc'
DESTRUCTIBLE_NORTHREND_CANOPY_TREE = 'NTtc'
DESTRUCTIBLE_RUINS_CANOPY_TREE = 'ZTtc'
DESTRUCTIBLE_BARREL = 'LTbx'
DESTRUCTIBLE_BARREL_2 = 'LTbs'
DESTRUCTIBLE_BARREL_3 = 'LTbr'
DESTRUCTIBLE_BARREL_OF_EXPLOSIVES = 'LTex'
DESTRUCTIBLE_BARRICADE = 'LTba'
DESTRUCTIBLE_BUILDING = 'XTbd'
DESTRUCTIBLE_CAGE = 'LOcg'
DESTRUCTIBLE_CITY_ENTRANCE = 'YTcx'
DESTRUCTIBLE_CITY_ENTRANCE_2 = 'YTce'
DESTRUCTIBLE_CLIFF_CAVE_GATE_1 = 'DTc1'
DESTRUCTIBLE_CLIFF_CAVE_GATE_2 = 'DTc2'
DESTRUCTIBLE_CRATES = 'LTcr'
DESTRUCTIBLE_DALARAN_VIOLET_CITADEL = 'XTvt'
DESTRUCTIBLE_DEMON_STORM = 'OTds'
DESTRUCTIBLE_DEMONIC_GATE_DIAGONAL_1 = 'ATg2'
DESTRUCTIBLE_DEMONIC_GATE_DIAGONAL_2 = 'ATg4'
DESTRUCTIBLE_DEMONIC_GATE_HORIZONTAL = 'ATg1'
DESTRUCTIBLE_DEMONIC_GATE_VERTICAL = 'ATg3'
DESTRUCTIBLE_DUNGEON_GATE_DIAGONAL_1 = 'DTg2'
DESTRUCTIBLE_DUNGEON_GATE_DIAGONAL_2 = 'DTg4'
DESTRUCTIBLE_DUNGEON_GATE_HORIZONTAL = 'DTg1'
DESTRUCTIBLE_DUNGEON_GATE_VERTICAL = 'DTg3'
DESTRUCTIBLE_DUNGEON_SPIKES = 'DTsp'
DESTRUCTIBLE_EGG_SACK = 'DTes'
DESTRUCTIBLE_ELVEN_GATE_DIAGONAL_1 = 'LTe2'
DESTRUCTIBLE_ELVEN_GATE_DIAGONAL_2 = 'LTe4'
DESTRUCTIBLE_ELVEN_GATE_HORIZONTAL = 'LTe1'
DESTRUCTIBLE_ELVEN_GATE_VERTICAL = 'LTe3'

DESTRUCTIBLE_LEVER = 'DTlv'

DESTRUCTIBLE_LINE_OF_SIGHT_BLOCKER = 'YTlb'
DESTRUCTIBLE_LINE_OF_SIGHT_BLOCKER_LARGE = 'Ytlc'
DESTRUCTIBLE_PATHING_BLOCKER_AIR = 'YTab'
DESTRUCTIBLE_PATHING_BLOCKER_AIR_LARGE = 'YTac'
DESTRUCTIBLE_PATHING_BLOCKER_BOTH = 'YTfb'
DESTRUCTIBLE_PATHING_BLOCKER_BOTH_LARGE = 'YTfc'
DESTRUCTIBLE_PATHING_BLOCKER_GROUND = 'YTpb'
DESTRUCTIBLE_PATHING_BLOCKER_GROUND_LARGE = 'YTpc'

# Fields
## Abilities
FIELD_ABIL_NAME = 'anam'  # string
FIELD_ABIL_TOOLTIP_NORMAL = 'atp1'  # string
FIELD_ABIL_TOOLTIP_NORMAL_EXTENDED = 'aub1'  # string
FIELD_ABIL_EDITOR_SUFFIX = 'ansf'
FIELD_ABIL_HOTKEY = 'ahky'  # string
FIELD_ABIL_HOTKEY_TURN_OFF = 'auhk'  # string
FIELD_ABIL_HOTKEY_LEARN = 'arhk'  # string
FIELD_ABIL_ICON_NORMAL = 'aart'  # string
FIELD_ABIL_ICON_TURN_OFF = 'auar'  # string
FIELD_ABIL_ICON_RESEARCH = 'arar'  # string
FIELD_ABIL_BUTTON_POSITION_NORMAL_X = 'abpx'
FIELD_ABIL_BUTTON_POSITION_NORMAL_Y = 'abpy'
FIELD_ABIL_BUTTON_POSITION_DISABLE_X = 'aubx'
FIELD_ABIL_BUTTON_POSITION_DISABLE_Y = 'auby'
FIELD_ABIL_BUTTON_POSITION_RESEARCH_X = 'arpx'
FIELD_ABIL_BUTTON_POSITION_RESEARCH_Y = 'arpy'
FIELD_ABIL_REQUIREMENTS = 'areq'  # string
FIELD_ABIL_REQUIREMENTS_LEVELS = 'arqa'  # string
FIELD_ABIL_EFFECT_SOUND = 'aefs'  # string
FIELD_ABIL_ART_CASTER = 'acat'  # string
FIELD_ABIL_STATS_CASTING_TIME = 'acas'  # unreal
FIELD_ABIL_STATS_CAST_RANGE = 'aran'  # unreal
FIELD_ABIL_STATS_DURATION_NORMAL = 'adur'  # unreal
FIELD_ABIL_STATS_LEVELS = 'alev'
FIELD_ABIL_STATS_IS_HERO_ABILITY = 'aher'
FIELD_ABIL_STATS_IS_ITEM_ABILITY = 'aite'
FIELD_ABIL_TECH_CHECK_DEPENDENCIES = 'achd'
FIELD_ABIL_DATA_CROW_FORM_ALTERNATE_FORM_UNIT = 'Emeu'  # string
FIELD_ABIL_DATA_CROW_FORM_NORMAL_FORM_UNIT = 'Eme1'  # string
FIELD_ABIL_DATA_CROW_FORM_MORPHING_FLAGS = 'Eme2'  # integer
FIELD_ABIL_DATA_CROW_FORM_ALTITUDE_ADJUSTMENT_DURATION = 'Eme3'  # unreal
FIELD_ABIL_DATA_CROW_FORM_LANDING_DELAY_TIME = 'Eme4'  # unreal
FIELD_ABIL_DATA_CHANNEL_OPTIONS = 'Ncl3'  # integer
FIELD_ABIL_DATA_CHANNEL_ART_DURATION = 'Ncl4'  # unreal
FIELD_ABIL_DATA_CHANNEL_DISABLE_OTHER_ABILITIES = 'Ncl5'  # integer
FIELD_ABIL_DATA_CHANNEL_BASE_ORDER_ID = 'Ncl6'  # string
FIELD_ABIL_DATA_SPELL_BOOK_SPELL_LIST = 'spb1'
FIELD_ABIL_DATA_SPELL_BOOK_SHARED_COOLDOWN = 'spb2'
FIELD_ABIL_DATA_SPELL_BOOK_MIN_SPELLS = 'spb3'
FIELD_ABIL_DATA_SPELL_BOOK_MAX_SPELLS = 'spb4'
FIELD_ABIL_DATA_ROBO_GOBLIN_STRENGTH_BONUS = 'Nrg5'
FIELD_ABIL_DATA_ROBO_GOBLIN_DEFENSE_BONUS = 'Nrg6'

## Items
FIELD_ITEM_NAME = 'unam'  # string
FIELD_ITEM_TOOLTIP_BASIC = 'utip'  # string
FIELD_ITEM_TOOLTIP_EXTENDED = 'utub'  # string
FIELD_ITEM_DESCRIPTION = 'ides'  # string
FIELD_ITEM_INTERFACE_ICON = 'iico'  # string
FIELD_ITEM_MODEL_USED = 'ifil'  # string
FIELD_ITEM_ABILITIES = 'iabi'  # string

## Units
FIELD_UNIT_ABILITIES_NORMAL = 'uabi'  # string
FIELD_UNIT_ABILITIES_DEFAULT = 'udaa'  # string
FIELD_UNIT_ATTACK_1_ATTACK_TYPE = 'ua1t'  # string
FIELD_UNIT_ATTACK_1_DAMAGE_BASE = 'ua1b'  # integer
FIELD_UNIT_ATTACK_1_DAMAGE_NUM_DICE = 'ua1d'  # integer
FIELD_UNIT_ATTACK_1_PROJECTILE_ART = 'ua1m'  # string
FIELD_UNIT_ATTACK_1_PROJECTILE_SPEED = 'ua1z'  # integer
FIELD_UNIT_ATTACK_1_RANGE = 'ua1r'  # integer
FIELD_UNIT_ATTACK_1_WEAPON_TYPE = 'ua1w'  # string
FIELD_UNIT_BALANCE_DEFENSE_BASE = 'udef'  # integer
FIELD_UNIT_BALANCE_SPEED_BASE = 'umvs'  # integer
FIELD_UNIT_GENERAL_EDITOR_SUFFIX = 'unsf'
FIELD_UNIT_GENERAL_NAME = 'unam'  # string
FIELD_UNIT_GENERAL_TOOLTIP_BASIC = 'utip'  # string
FIELD_UNIT_GENERAL_STRUCTURES_BUILT = 'ubui'  # string
FIELD_UNIT_STATS_BUILD_TIME = 'ubld'
FIELD_UNIT_STATS_FOOD_COST = 'ufoo'
FIELD_UNIT_STATS_FOOD_PRODUCED = 'ufma'
FIELD_UNIT_STATS_FORMATION_RANK = 'ufor'
FIELD_UNIT_STATS_GOLD_BOUNTY_BASE = 'ubba'
FIELD_UNIT_STATS_GOLD_BOUNTY_NUM_DICE = 'ubdi'
FIELD_UNIT_STATS_GOLD_BOUNTY_SIDES_PER_DIE = 'ubsi'
FIELD_UNIT_STATS_GOLD_COST = 'ugol'
FIELD_UNIT_STATS_HIT_POINTS_MAXIMUM = 'uhpm'
FIELD_UNIT_STATS_HIT_POINTS_REGENERATION_RATE = 'uhpr'
FIELD_UNIT_STATS_HIT_POINTS_REGENERATION_TYPE = 'uhrt'
FIELD_UNIT_STATS_IS_BUILDING = 'ubsi'
FIELD_UNIT_STATS_LEVEL = 'ulev'
FIELD_UNIT_STATS_LUMBER_BOUNTY_BASE = 'ulba'
FIELD_UNIT_STATS_LUMBER_BOUNTYNUM_DICE = 'ulbd'
FIELD_UNIT_STATS_LUMBER_BOUNTY_SIDES_PER_DIE = 'ulbs'
FIELD_UNIT_STATS_LUMBER_COST = 'ulum'
FIELD_UNIT_STATS_MANA_INITIAL_AMOUNT = 'umpi'
FIELD_UNIT_STATS_MANA_MAXIMUM = 'umpm'
FIELD_UNIT_STATS_MANA_REGENERATION = 'umpr'
FIELD_UNIT_STATS_POINT_VALUE = 'upoi'
FIELD_UNIT_STATS_PRIORITY = 'upri'
FIELD_UNIT_STATS_RACE = 'urac'
FIELD_UNIT_STATS_REPAIR_GOLD_COST = 'ugor'
FIELD_UNIT_STATS_REPAIR_LUMBER_COST = 'ulur'
FIELD_UNIT_STATS_REPAIR_TIME = 'urtm'
FIELD_UNIT_STATS_SIGHT_RADIUS_DAY = 'usid'  # integer
FIELD_UNIT_STATS_SIGHT_RADIUS_NIGHT = 'usin'  # integer
FIELD_UNIT_STATS_SLEEPS = 'usle'  # integer
FIELD_UNIT_STATS_STOCK_MAXIMUM = 'usma'
FIELD_UNIT_STATS_STOCK_REPLENISH_INTERVAL = 'usrg'
FIELD_UNIT_STATS_STOCK_START_DELAY = 'usst'
FIELD_UNIT_STATS_TRANSPORTED_SIZE = 'ucar'
FIELD_UNIT_STATS_UNIT_CLASSIFICATION = 'utyp'
FIELD_UNIT_UI_MODEL_FILE = 'umdl'  # string
FIELD_UNIT_UI_SCALING_VALUE = 'usca'  # float
FIELD_UNIT_UI_TINT_BLUE = 'uclb'  # integer
FIELD_UNIT_UI_TINT_GREEN = 'uclg'  # integer
FIELD_UNIT_UI_TINT_RED = 'uclr'  # integer

## Upgrades
FIELD_UPGRADE_NAME = 'gnam'  # string

# Base Order IDs
BASE_ORDER_IDS = [
    'absorb',
    'acidbomb',
    'acolyteharvest',
    'AImove',
    'ambush',
    'ancestralspirit',
    'ancestralspirittaarget',
    'animatedead',
    'antimagicshell',
    # 'attack',
    # 'attackground',
    # 'attackonce',
    'attributemodskill',
    'auraunholy',
    'auravampiric',
    'autodispel',
    'autodispeloff',
    'autodispelon',
    'autoentangle',
    'autoentangleinstant',
    'autoharvestgold',
    'autoharvestlumber',
    'avatar',
    'avengerform',
    'awaken',
    'banish',
    'barkskin',
    'bakrkskinoff',
    'bakrskinon',
    'battleroar',
    'battlestations',
    'bearform',
    'berserk',
    'blackarrow',
    'blackarrowoff',
    'blackarrowon',
    'blight',
    'blink',
    'blizzard',
    'bloodlust',
    'bloodlustoff',
    'bloodluston',
    # 'board',
    'breathoffire',
    'breathoffrost',
    'build',
    'burrow',
    'cannibalize',
    'carrionscarabs',
    'carrionscarabsinstant',
    'carrionscarabson',
    'carrionscarabsoff',
    'carrionswarm',
    'chainlightning',
    'channel',
    'charm',
    'chemicalrage',
    'cloudoffog',
    'clusterrockets',
    'coldarrows',
    'coldarrowstarg',
    'controlmagic',
    'corporealform',
    'corrosivebreath',
    'coupleinstant',
    'coupletarget',
    'creepanimatedead',
    'creepdevour',
    'creepheal',
    'creephealoff',
    'creephealon',
    'creepthunderbolt',
    'creepthunderclap',
    'cripple',
    'curse',
    'curseoff',
    'curseon',
    'cyclone',
    'darkconversion',
    'darkportal',
    'darkritual',
    'darksummoning',
    'deathanddecay',
    'deathcoil',
    'deathpact',
    'decouple',
    'defend',
    'detectaoe',
    'detonate',
    'devour',
    # ...
]
