# Warcraft 3 Minimap Info File (.mmp)
# See mmp.py for type definitions

file_format_version = 0

[[icons]]
icon_type = "House"
x = 185
y = 107
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "House"
x = 155
y = 182
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "GoldMine"
x = 246
y = 156
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "House"
x = 220
y = 135
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "House"
x = 163
y = 51
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "GoldMine"
x = 169
y = 86
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "GoldMine"
x = 17
y = 94
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "House"
x = 57
y = 58
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "House"
x = 205
y = 169
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "House"
x = 144
y = 125
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "House"
x = 94
y = 112
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "GoldMine"
x = 194
y = 148
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "GoldMine"
x = 92
y = 208
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 263
y = 211
colour_blue = 0
colour_green = 192
colour_red = 32
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 71
y = 156
colour_blue = 129
colour_green = 0
colour_red = 84
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 263
y = 211
colour_blue = 151
colour_green = 150
colour_red = 149
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 263
y = 211
colour_blue = 241
colour_green = 191
colour_red = 126
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 263
y = 211
colour_blue = 4
colour_green = 42
colour_red = 78
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 263
y = 211
colour_blue = 70
colour_green = 98
colour_red = 16
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 3
y = 198
colour_blue = 185
colour_green = 230
colour_red = 28
colour_alpha = 255