# Warcraft 3 Sound file (.w3s)
# See w3s.py for type definitions

version = 1

[[sounds]]
name = 'gg_snd_U08Archimonde19'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Archimonde19.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Archimonde20'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Archimonde20.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Archimonde22'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Archimonde22.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Archimonde24'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Archimonde24.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Arthas01'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Arthas01.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Arthas04'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Arthas04.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Arthas06'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Arthas06.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Arthas11'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Arthas11.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Arthas25'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Arthas25.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08KelThuzad07'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08KelThuzad07.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08KelThuzad08'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08KelThuzad08.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08KelThuzad09'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08KelThuzad09.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08KelThuzad18'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08KelThuzad18.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08KelThuzad26'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08KelThuzad26.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Necromancer10'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Necromancer10.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Tichondrius03'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Tichondrius03.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Tichondrius21'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Tichondrius21.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08Tichondrius23'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08Tichondrius23.mp3'
effects = ''
flags = "NONE"
fade_in = 12700
fade_out = 12700
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_U08KelThuzad02'
file = 'Sound\Dialogue\UndeadCampaign\Undead08\U08KelThuzad02.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_Hint'
file = 'Sound\Interface\Hint.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_SteamTankPissed1'
file = 'Units\Human\SteamTank\SteamTankPissed1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_HippoGryphReady1'
file = 'Units\NightElf\HippoGryph\HippoGryphReady1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_KnightNoRiderWhat2'
file = 'Units\Human\KnightNoRider\KnightNoRiderWhat2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_HorseLoop2'
file = 'Units\Human\Knight\HorseLoop2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_HorseLoop1'
file = 'Units\Human\Knight\HorseLoop1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_HorseLoop3'
file = 'Units\Human\Knight\HorseLoop3.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_BattleNetWooshStereo1'
file = 'Sound\Interface\BattleNetWooshStereo1.wav'
effects = 'DefaultEAXON'
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_LargeCityGateOpen1'
file = 'Sound\Ambient\DoodadEffects\LargeCityGateOpen1.wav'
effects = 'DefaultEAXON'
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_NecropolisUpgrade2'
file = 'Buildings\Undead\Necropolis\NecropolisUpgrade2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_SacrificialPitWhat1'
file = 'Buildings\Undead\SacrificialPit\SacrificialPitWhat1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_DarkSummoningTarget1'
file = 'Abilities\Spells\Undead\DarkSummoning\DarkSummoningTarget1.wav'
effects = 'SpellsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_CityScapeMagicRunesLoop1'
file = 'Sound\Ambient\DoodadEffects\CityScapeMagicRunesLoop1.wav'
effects = 'DoodadsEAX'
flags = "Looping|Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 2000.0
max_distance = 4294967296.0
distance_cutoff = 2000.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_FrostmourneLoopUndead01'
file = 'Sound\Ambient\DoodadEffects\FrostmourneLoopUndead01.wav'
effects = 'DoodadsEAX'
flags = "Looping|Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 2000.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_AntiMagicShellBirth1'
file = 'Abilities\Spells\Undead\AntiMagicShell\AntiMagicShellBirth1.wav'
effects = 'SpellsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_CrippleTarget1'
file = 'Abilities\Spells\Undead\Cripple\CrippleTarget1.wav'
effects = 'SpellsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_BuildingDeathLargeOrc'
file = 'Sound\Buildings\Death\BuildingDeathLargeOrc.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_BuildingDeathLargeHuman'
file = 'Sound\Buildings\Death\BuildingDeathLargeHuman.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_OrcHumanMediumBuildingFire1'
file = 'Sound\Buildings\Fire\OrcHumanMediumBuildingFire1.wav'
effects = 'SpellsEAX'
flags = "Looping|Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_LightningShieldTarget'
file = 'Abilities\Spells\Orc\LightningShield\LightningShieldTarget.wav'
effects = 'SpellsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_WaterLakeLoop1'
file = 'Sound\Ambient\DoodadEffects\WaterLakeLoop1.wav'
effects = 'DoodadsEAX'
flags = "Looping|Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1

[[sounds]]
name = 'gg_snd_WarlockAppears'
file = 'Sound\Ambient\DoodadEffects\WarlockAppears.wav'
effects = 'DefaultEAXON'
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
file_format = -1
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0
unknown4 = -1