# Warcraft 3 Minimap Info File (.mmp)
# See mmp.py for type definitions

file_format_version = 0

[[icons]]

icon_type = "House"
x = 11
y = 59
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 187
y = 186
colour_blue = 255
colour_green = 66
colour_red = 0
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 9
y = 113
colour_blue = 241
colour_green = 191
colour_red = 126
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 71
y = 176
colour_blue = 129
colour_green = 0
colour_red = 84
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 51
y = 45
colour_blue = 0
colour_green = 192
colour_red = 32
colour_alpha = 255

[[icons]]

icon_type = "PlayerStart"
x = 94
y = 150
colour_blue = 185
colour_green = 230
colour_red = 28
colour_alpha = 255