# Warcraft 3 Minimap Info File (.mmp)
# See mmp.py for type definitions

file_format_version = 0

[[icons]]
icon_type = "GoldMine"
x = 186
y = 170
colour_blue = 255
colour_green = 255
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 40
y = 200
colour_blue = 241
colour_green = 191
colour_red = 126
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 205
y = 15
colour_blue = 14
colour_green = 138
colour_red = 254
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 130
y = -13
colour_blue = 0
colour_green = 192
colour_red = 32
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 28
y = 26
colour_blue = 129
colour_green = 0
colour_red = 84
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 78
y = 140
colour_blue = 255
colour_green = 66
colour_red = 0
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 74
y = 86
colour_blue = 185
colour_green = 230
colour_red = 28
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 173
y = 179
colour_blue = 3
colour_green = 3
colour_red = 255
colour_alpha = 255

[[icons]]
icon_type = "PlayerStart"
x = 172
y = 163
colour_blue = 70
colour_green = 98
colour_red = 16
colour_alpha = 255